---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: kube-prometheus-stack-kube-controller-manager-static
  namespace: kube-system
  labels:
    kubernetes.io/service-name: kube-prometheus-stack-kube-controller-manager
addressType: IPv4
ports:
  - name: http-metrics
    port: 10257
    protocol: TCP
endpoints:
  - addresses:
      - 10.0.0.51
    conditions:
      ready: true
  - addresses:
      - 10.0.0.52
    conditions:
      ready: true
  - addresses:
      - 10.0.0.53
    conditions:
      ready: true
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: kube-prometheus-stack-kube-scheduler-static
  namespace: kube-system
  labels:
    kubernetes.io/service-name: kube-prometheus-stack-kube-scheduler
addressType: IPv4
ports:
  - name: http-metrics
    port: 10259
    protocol: TCP
endpoints:
  - addresses:
      - 10.0.0.51
    conditions:
      ready: true
  - addresses:
      - 10.0.0.52
    conditions:
      ready: true
  - addresses:
      - 10.0.0.53
    conditions:
      ready: true
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: kube-prometheus-stack-kube-etcd-static
  namespace: kube-system
  labels:
    kubernetes.io/service-name: kube-prometheus-stack-kube-etcd
addressType: IPv4
ports:
  - name: http-metrics
    port: 2381
    protocol: TCP
endpoints:
  - addresses:
      - 10.0.0.51
    conditions:
      ready: true
  - addresses:
      - 10.0.0.52
    conditions:
      ready: true
  - addresses:
      - 10.0.0.53
    conditions:
      ready: true
