---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-db-secret
  namespace: observability
type: Opaque
stringData:
  password: "<POSTGRES_PASSWORD>"
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-oauth-secret
  namespace: observability
type: Opaque
stringData:
  client_secret: "<GRAFANA_OAUTH_CLIENT_SECRET>"
