
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - alertmanager-config/custom-alerts.yaml
  - alertmanager-config/loki-log-alerts.yaml
  - ingress/grafana-ingressroute.yaml
  - pve-exporter/service.yaml
  - pve-exporter/deployment.yaml
  - pve-exporter/servicemonitor.yaml
  - ntfy.yaml
  - ntfy-cache-pvc.yaml
  - ingress/ntfy-ingressroute.yaml
  - control-plane-endpointslices.yaml
  - truenas-exporters.yaml

generators:
  - secrets/ksops-generator.yaml

helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    version: "87.21.0"
    releaseName: kube-prometheus-stack
    namespace: observability
    valuesFile: prometheus-values.yaml
    includeCRDs: false
  - name: loki
    repo: https://grafana.github.io/helm-charts
    version: "7.3.0"
    releaseName: loki
    namespace: observability
    valuesFile: loki-values.yaml
    includeCRDs: false
  - name: promtail
    repo: https://grafana.github.io/helm-charts
    version: "6.17.1"
    releaseName: promtail
    namespace: observability
    valuesFile: promtail-values.yaml
    includeCRDs: false
