
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - alertmanager-config/custom-alerts.yaml
  - alertmanager-config/tls-alerts.yaml
  - alertmanager-config/loki-log-alerts.yaml
  - ingress/grafana-ingressroute.yaml
  - pve-exporter/service.yaml
  - pve-exporter/deployment.yaml
  - pve-exporter/servicemonitor.yaml
  - ntfy.yaml
  - ntfy-cache-pvc.yaml
  - ingress/ntfy-ingressroute.yaml
  - control-plane-endpointslices.yaml
  - truenas-exporters.yaml

generators:
  - secrets/ksops-generator.yaml

helmCharts:
  - name: prometheus-blackbox-exporter
    repo: https://prometheus-community.github.io/helm-charts
    version: "11.18.0"
    releaseName: blackbox-exporter
    namespace: observability
    valuesFile: blackbox-values.yaml
    includeCRDs: false
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    version: "91.7.0"
    releaseName: kube-prometheus-stack
    namespace: observability
    valuesFile: prometheus-values.yaml
    includeCRDs: false
  - name: loki
    repo: https://grafana.github.io/helm-charts
    version: "7.3.0"
    releaseName: loki
    namespace: observability
    valuesFile: loki-values.yaml
    includeCRDs: false
  - name: alloy
    repo: https://grafana.github.io/helm-charts
    version: "1.13.0"
    releaseName: alloy
    namespace: observability
    valuesFile: alloy-values.yaml
    includeCRDs: false
