apiVersion: v1
kind: Secret
metadata:
    name: airvpn-credentials
    namespace: servarr
type: Opaque
stringData:
    airusername: ENC[AES256_GCM,data:3vQ1QLxBDhE=,iv:54Tankomk+KorLig9rTMhGFNVxjSr/TZed28PJUQBWE=,tag:LO3/EPYEpa/QpROEVGBuHA==,type:str]
    airpassword: ENC[AES256_GCM,data:tO1r3Wj6xK+sd4IZ/9Fj,iv:W8TC5Eb6C6njB+ZG/Ed6vLdoY2C/lTBqVdwxPrXmfIM=,tag:1O1kgUNFJBE9MGo60dK0ig==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOSW94VWlLMGh3d0JYZ0tC
            RzJleGlUcDl6dWhvbE9zRXlKWWI2aXlTdmpNClNwT2w3Y1RlYmpXZUN3M3FwYjAr
            aCtXWGUreVhLbGtsMStZbTZZaXh2OEkKLS0tIGZ6aWU3S3lkQzRiQlBhdzVvVlNy
            SnBNY0ViT2tkZEoycExrQm5heW13RUUKP/XHQG+S+xWdQnEubBJ9IyfTTaA42FIv
            d2W6+aT4tRLb2fiuzqZsChd+nHNMduJoTCfItg7MUhlk+RZLqcu5/g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1586thf5vkcdf5lcn3zwjpu8ltkwyq8efrhj8lr0vdrrt9k5f3qgsxeg7gx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-30T19:21:40Z"
    mac: ENC[AES256_GCM,data:p/iXxdD2XQKr0nN1bC/ev5O9oIzVi0RU27U+/73vV+wFU7h5hCDKPX9wwJCVeQbBXkQ7HjUqhsMQBiWuffb3X3cWOPm2KcBhSGUJ1RM+mTIqb8riViYOj80GrK9Gf6EMYEqqatcY59ZL48fo0k0mYLmKaU5UM+V+yNAho63r6V4=,iv:Jk+lxC/0LStIC2+p7fSQv6Dd7m3ul6S1qG+/6Ha+gK0=,tag:wNuWsr+bJo5WlP8sRbLswg==,type:str]
    version: 3.13.3
