apiVersion: v1
kind: Secret
metadata:
    name: airvpn-api-key
    namespace: servarr
type: Opaque
stringData:
    airvpn_api_key: ENC[AES256_GCM,data:ieYKhU2YVfJcY85wzAB1nwQfq30ipZVW0Mwf8cyBhHClKq0LsBDnGZXGxCAsN9BkQfQQGFF/lxoTi4nrlz7JQw==,iv:VEL2TFaEgSH2RnAI8VAko+PR8rkCWoC3JUO2ylu977A=,tag:19+fiRuZQ0Lf7UwveGSmXg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQVVRGaElmeUkydzNSRlRV
            SEVrZHJ1K21lRzhta3JNTXdQN0VNd29xYUZZCmlKSjMyZTdRa0VCOWZuV3l5YW02
            dm82a0IrZDVvMzBtVUpqaUVoaEt2RjAKLS0tIHN6dk9FZWNmSzFVa2ZvZ243aGxr
            Sk1oTWJpbjcvMC9MNldmTExteTB0UkUKvria9ypXqafkIUXhwiyxqxuDot34g14Z
            PFnRwyubAuzznYDS0lUUlZp3A63O6HRJphci5Mvu2XGRmWIxii4kCA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1586thf5vkcdf5lcn3zwjpu8ltkwyq8efrhj8lr0vdrrt9k5f3qgsxeg7gx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-02T01:34:01Z"
    mac: ENC[AES256_GCM,data:HJVMFt0psoP1Jh96dSjXzO4nw26Wx3ehleg4Wzg/VnXKSZUALXQD8+0/M23Y9ETkFMerxLCHRUzQCxYW50wyfqz4Q+ImGhFcwFLoLlb2aNrJ+PlctYrvdxyVm320vDd5+kDq28vIZpWjNPX2K3/qhXzm6wm9wVn8iOrpsaM8T6o=,iv:JjhrTC1TjRFF5+R1VZYJiUevT/+VSFvONqWnlEQeWGs=,tag:ZH9Oe5ncUgWai4t37U+gyg==,type:str]
    version: 3.13.3
