apiVersion: v1
kind: Secret
metadata:
    name: airvpn-credentials
    namespace: servarr
type: Opaque
stringData:
    airusername: ENC[AES256_GCM,data:3vQ1QLxBDhE=,iv:54Tankomk+KorLig9rTMhGFNVxjSr/TZed28PJUQBWE=,tag:LO3/EPYEpa/QpROEVGBuHA==,type:str]
    airpassword: ENC[AES256_GCM,data:rP9lTUDNs0Fpp5SRmyY=,iv:9xrN492Rm6RzteHa0HezT8SlGgdkx/8kibex6SKALf0=,tag:yigeouKo1rrlrcuzhK+Wmw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOSW94VWlLMGh3d0JYZ0tC
            RzJleGlUcDl6dWhvbE9zRXlKWWI2aXlTdmpNClNwT2w3Y1RlYmpXZUN3M3FwYjAr
            aCtXWGUreVhLbGtsMStZbTZZaXh2OEkKLS0tIGZ6aWU3S3lkQzRiQlBhdzVvVlNy
            SnBNY0ViT2tkZEoycExrQm5heW13RUUKP/XHQG+S+xWdQnEubBJ9IyfTTaA42FIv
            d2W6+aT4tRLb2fiuzqZsChd+nHNMduJoTCfItg7MUhlk+RZLqcu5/g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1586thf5vkcdf5lcn3zwjpu8ltkwyq8efrhj8lr0vdrrt9k5f3qgsxeg7gx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-03T07:47:43Z"
    mac: ENC[AES256_GCM,data:p+aUjbrkimZEve59y7KS3IlxWEbVW5CCWO+e1gg3HbQPW40WHKdPhfhyWXtlWK2WuuzWkfvl4wRcih9pv37TbpP/m+e0ZKcQ0c+nJMsLltuS8nLxlwWGzBZA1LA596CRwb63mrmwpU4Az/C2FsB+Asw3/x55igtPNRmh1cEefrU=,iv:vsGN0fXobgTrh0VRYsJ+lMDTC3wdnh+f/K8VlXc8o4A=,tag:tqReFqGW/11jUu5c2/maiQ==,type:str]
    version: 3.13.3
