apiVersion: v1
kind: Secret
metadata:
    name: bazarr-autotranslate-secret
    namespace: servarr
type: Opaque
stringData:
    BAZARR_API_KEY: ENC[AES256_GCM,data:VKUIR6EIsIwV6xIhp0Nd5t6Q8OP6u7j3vMaBF9Q5qMM=,iv:g0RAqmWTkPOewjDPBZRmY05ZtUwptm/Ppa9tawJsi6M=,tag:cgZuytFaLXg0f/lilGRD3A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoOXRVQUEreUpMZktlUHFC
            ZXhlRmMrU1BQRzFwTTNIS0ZJWTdERFp4Y200Cm85NkxaZElGRmkxdGk0WUpJa0JV
            bDRibjFTVnJKdUthSy9ONVBNNkc4Q1kKLS0tIFUwNGlEdWlTQmU1M0ZQcHZ5eHUw
            WEZaR1c3aitJb2RqOC8xNWRhNE1NcDgKia/jFhoZUaA1EOmD84km9vPtGcpBtCSp
            J9m7tBcwplz2gdncWs6YmdKmf7IJWZ2cnrNgRsmx3t8YBTVN2VpuSA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1586thf5vkcdf5lcn3zwjpu8ltkwyq8efrhj8lr0vdrrt9k5f3qgsxeg7gx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-09T23:29:55Z"
    mac: ENC[AES256_GCM,data:0qmR6L/NQbYkTsc81Zyf8jFBGfuehNIKx7RAhXPQQvTtWZP/b5I6HI8+z+nhpNyyf9R3u+Y7+U3D7wir/MUel9l8aLqs9YAzEz8w41460hOtAJnDjYs7+bTqZz7vC9QBtzj+Dop3a1iRKaB/GMD+5E1zoOMvNgaJ9dJVvkTEC5w=,iv:xrRGKd+MlYzJ1+JY/pC4+rNMS+KaecI3ghbf4xZrMls=,tag:6qZmBT1EA7iKJBmFFl6dyg==,type:str]
    version: 3.13.3
