apiVersion: v1
kind: Secret
metadata:
    name: bazarr-autotranslate-secret
    namespace: servarr
type: Opaque
stringData:
    BAZARR_API_KEY: ENC[AES256_GCM,data:GvoVMixevL4vyeyf70Y+mVzv7rnH5hjX8axJyuCedyA=,iv:FpaRZg5+x7Pw6n9LKtv3tntPKG7TNm+Lbis0fhDijgQ=,tag:Ugxq8vKd3kD3p9s6nsGXuQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsNkRvS1lnVHpINmlsVnRW
            eGpVMExUU1d3WEZNTEhLRUkyRWRJNVVRR2hrClB6dnZCaFQ0TE4wLzlLYUUwR2tU
            RkpJTjdQejh1L0RSZTM4SzhGUTB5UncKLS0tIHpiQzI3cWV0RnI4b1V4Qktra09O
            VWY0RHR5UVNPL0VSMWtlVWJnRS8vMTAKMAN0SDIuDdf4Uq+h8hYSbfnG6IDkDLJx
            dd4+dJ6WB16X6gtv1BG6qZ/0GKStL2kKg/WFS949kGyB6xfqvpPQFA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1586thf5vkcdf5lcn3zwjpu8ltkwyq8efrhj8lr0vdrrt9k5f3qgsxeg7gx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-13T16:47:36Z"
    mac: ENC[AES256_GCM,data:6yGBXjKzb3KdRbjCQ3T9cd3JiTKCA5tWz2WoUxtdQCCo5pO3JZRqynHrKL5lFHbTnd0Qg7HpTA++pQysRTRwzc7w8SBz68xZfjRMu66ThbXX2D3el2eD2nHfm8KVkmbY/GEg1kQXJwTSCZYzXtMGD4kUoT7I29UmLdYbGYu8kZU=,iv:lKqBtjIw3rZVAaaGgCDFFbomWviDlcgk5jhyqweq60g=,tag:5IndLFa3bdOYGbEzJeueWA==,type:str]
    version: 3.13.1
