apiVersion: v1
kind: Secret
metadata:
    name: bazarr-autotranslate-secret
    namespace: servarr
type: Opaque
stringData:
    BAZARR_API_KEY: ENC[AES256_GCM,data:kSNFeJYHvD6lYJh7ectf2GGLok1YKSIgsvEQyIE14XI=,iv:E8oVM2DIatjpyw3Vgt+GdzDoUo2QSa8f8hsRWId6rO4=,tag:+JQZjFCMHfvXWFlxsfpP1Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoOXRVQUEreUpMZktlUHFC
            ZXhlRmMrU1BQRzFwTTNIS0ZJWTdERFp4Y200Cm85NkxaZElGRmkxdGk0WUpJa0JV
            bDRibjFTVnJKdUthSy9ONVBNNkc4Q1kKLS0tIFUwNGlEdWlTQmU1M0ZQcHZ5eHUw
            WEZaR1c3aitJb2RqOC8xNWRhNE1NcDgKia/jFhoZUaA1EOmD84km9vPtGcpBtCSp
            J9m7tBcwplz2gdncWs6YmdKmf7IJWZ2cnrNgRsmx3t8YBTVN2VpuSA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1586thf5vkcdf5lcn3zwjpu8ltkwyq8efrhj8lr0vdrrt9k5f3qgsxeg7gx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-13T17:29:30Z"
    mac: ENC[AES256_GCM,data:b5huUa152STLTJ8dwex4iRE7fuapvRMZ9g5jOp/MQ5q5+uk6kYoAXVvtqKGuK9OaqMOz3Q+vXniuXP1KAy5QyISH0zhRqjoggGq7vvHzdB9W2mwmBNgX4V7sXPSs8GWntOyd/80y9OXApUB4tNjIE11g7o+rXPozWL4z89XM60U=,iv:OCPTZbATOTQ6BnZLm4k9RNvb4P9BT+UNJ61IaFWvdiY=,tag:xIYvz6gNX+w20fMih+YcnQ==,type:str]
    version: 3.13.1
