apiVersion: v1
kind: Secret
metadata:
    name: cleanuparr-blocklist-seed
    namespace: servarr
type: Opaque
stringData:
    custom-blocklist-sonarr.txt: ENC[AES256_GCM,data:7VZh07jct8NUvN40hWw5W6P79kQb2bCJK5Kr353S5fzdrPHYQNsAe6dUlG12HYbDva6/0B2FErB6NzoYqBOBVr0XWdD2TTWu7UnyE+r60c0n6g9Y4nzTwRel7LHGiw+ofi2Dre4zaWlWlAPJavMpWMhSUROB2Aqv+YePn+A9oQnGb9Qbze57cQxLH8udaGwumIMmutCVG0WWy7iY301GA3w6ZQTCv/EzXKEOGsP1rMFujMz5+IAhN1j7nAtQSM1eDa8wYi5zCkV+AVA1KedAXMuNKMMDYIvEg2jNCcQHT0jAl30Ial4hmivjZmVEKCHlTvTDBK6hwh3eQUnHc5LJJ4uQ/4P4/nfg4IX2CmsrIcnIrNrBTOYKiSOX5f8jVOJwKDLr13TnP2HbE2ZDwqF6AzxhHamgiwSC7gA3gJPub1t+enTXVncGTlizYCIYVhYMdN5SeJ1ahz0YDqm5dqzos8AReM9xQeDDBXSk5NeGWdkteQLfQ7MVRKaMBcFGNuID9pagQTyPmxJvc1rWwWbCq5GNg2pHER/qDhGj4kRHnQQ9IIZGMbeJteMFpA3ySW/9U2UKZXq9KnC0CkwHmw3yCj3T5GPU0eEBZOlOl0GHKzcqxsvHEzGj1A==,iv:wFmW2gr0DYFQ/l+6r0oaLAY31NJCJSU1N0YywJmNmXA=,tag:qxpTv2gm4WjLhJ1/NzQzEQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4MHRRUTNVclhEMHkwQklL
            MnpzNFRiVUN1MGk5WVUvZE9Ob3VmcGV1K0hZCnUrbXZkZXJPaEgyUnhzNm9NYWRw
            RHRwUTB0b1cyTmRNa0dSMkw3bEV4ZlUKLS0tIEhBbDNsTmFZK2xFQmxZMnpReDlj
            eVRCU2l3OE90Ky9kOEg2NnhYUTBubWsKfKYdMx6C366MbvoUMds4ifldlaMAmnoP
            3tp8k74XV2TGQix2ykFYF2XpFGOuqDzO0o18A4Sa03cdobnAYlvlYA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1586thf5vkcdf5lcn3zwjpu8ltkwyq8efrhj8lr0vdrrt9k5f3qgsxeg7gx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-13T09:25:34Z"
    mac: ENC[AES256_GCM,data:Yr3al5dinIn+2jGBzx35fBLhGXBn4h8AbvDfXQOhr0+0SyVfGPFGrfjJdpEYGu45gmmyvi7Seizgp8UYuXoZpkg84FVsMWJzy/HGQXcEjrkWZ+uJS1Cz7xsX1rXUBrAOFH0MeWPrVu7GrqeulMynKFHFTyCBiH+AtM53GH9j6yc=,iv:IguXPmDxN5jGQgbeOR2yQYfN/D0TN/lc7X/vJeEl8Bg=,tag:Bi+fPbFW9UV6DK8pZhQdSw==,type:str]
    version: 3.13.1
