apiVersion: v1
kind: Secret
metadata:
    name: homarr-secret
    namespace: servarr
type: Opaque
stringData:
    SECRET_ENCRYPTION_KEY: ENC[AES256_GCM,data:iepNZ+YYSTLLrLXVg7RjaSy5hb7lqLNQHT/GfvuvevTYdHUb9VbQkL1JTNEaIKbodaKkdtK17p1AWDBdWJahyw==,iv:A5UHvTyqIFqzuWIVxk3zgvGBep9S59YaCRGVQilOzeg=,tag:sMDNDtAxHvAJ1xLzcUGizA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlRDFXZ3h6aW4wWGlMdDhK
            TU5CdTRJMTBjSnA0bWxvckJrOHBLS2dZQUFJCmRON3dxODFyMmpnd3VwV2RFNG5C
            QUtPRFlRWXk3eWlicVErSjRZRTNWM1kKLS0tIGIyaGFWUDZQNzBUT1NQMzlpdFZq
            WDZOU3o5SFo2SndlUW53a1RSMk9iaVkK/4qmNQ3XeTKfZdwWe7JuF8abz8Duhe0K
            tXZcElREpkgNOySIB9zOOWv1AkxDDy+Di5qrxonzYWgjE4UciP41Gg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1586thf5vkcdf5lcn3zwjpu8ltkwyq8efrhj8lr0vdrrt9k5f3qgsxeg7gx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-01T00:53:57Z"
    mac: ENC[AES256_GCM,data:KTVEQxWVQhmhu55WVMJ6qx01+I9sLzheiUV8/dRBmSvs2osYfRaeT6G9Pc8217tvil9pjcnZKTJL0MUmowgJeAsk/p2dWBE+gJ4mulofCqXiD6rraphDCX2svhwEYsrIxJlI8sTJ6fqd0+YJzjsI8iFEGiiX3MNAry2DWHZ8yM0=,iv:SDPpIaezuK5O7PFBqnBfzFsHpV2sz9uBTLcwsZhYe/w=,tag:Zohffmpk6gYskby0CM8pEQ==,type:str]
    version: 3.13.3
