apiVersion: v1
kind: Secret
metadata:
    name: jellyfin-metadata-healer
    namespace: servarr
type: Opaque
stringData:
    apiKey: ENC[AES256_GCM,data:YXy5FJl6FdpnIqtsc779eStcHPSlYrxoc8dlH5kyp6U=,iv:VKiO5EDo5z7q2G6We8QIMk4JfIqte2lYh4VEScowKP0=,tag:1jsCI0Hx/NSovbIgEqIowg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtS05ZQlVnWUpURGNNMHB4
            aWd3WkZyTE9PeEVXczdRRkdxSG5USlNYbjBjCjVBRTVzaENWemdxck1JOHZZR0Rt
            YVFHSktTdUJNSjEva1JqRlI4amJVTGMKLS0tIEZRN2VFVGdDdUpTcWh0R2cyQ2pG
            T05kZVRyL1NyaWV0MUVLNEx3Ymx6QXcKZB613C97XgUqmSlYQK8qodYFh9R+nh16
            T56ZKAtEjBqaChjiiZbZQZojats9i4nu7Fd0fThfuNxIrVDIbrsKiA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1586thf5vkcdf5lcn3zwjpu8ltkwyq8efrhj8lr0vdrrt9k5f3qgsxeg7gx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-29T20:17:00Z"
    mac: ENC[AES256_GCM,data:AFZZ2h7Q43OYLIlOr6rsQ/BoUwxkIw94IuL9sjr6ugOONJoGg6kR8SVPqvFlZfGOA3fDeCxlhJ6Pr6np0WseDxnLyh9VFgKSHzYuqDW3Z/IPwc0o1qG6qlwaebyDJNCXPOKUKpdg48IizHIPJ+AD8ztlGBQ+gaf1D2iQX5BrtAs=,iv:jhcsHnFWJ0bYTlNnTPT4mEuG6NC4vrSPV7aq+Ez/w84=,tag:+Eybxsf0MepBsCsuCwsS1A==,type:str]
    version: 3.13.3
