apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: servarr-secrets
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - _shared/secrets/servarr-postgres.enc.yaml
  - _shared/secrets/neutarr-config-seed.enc.yaml
  - _shared/secrets/seerr-config-seed.enc.yaml
  - _shared/secrets/cleanuparr-blocklist-seed.enc.yaml
  - _shared/secrets/unpackerr-secret.enc.yaml
  - _shared/secrets/bazarr-autotranslate-secret.enc.yaml
  - _shared/secrets/airvpn-credentials.enc.yaml
  - _shared/secrets/airvpn-api-key.enc.yaml
  - _shared/secrets/qbittorrent-webapi-key.enc.yaml
  - _shared/secrets/qbittorrent-webui-credentials.enc.yaml
  - _shared/secrets/prowlarr-api-key.enc.yaml
  - _shared/secrets/cleanuparr-api-key.enc.yaml
