apiVersion: v1
kind: Secret
metadata:
    name: lingarr-cliproxy-api-key
    namespace: servarr
type: Opaque
stringData:
    omp-api-key: ENC[AES256_GCM,data:9OX7J+Sd1LK+C4gOO+56XSqTFmaRvdRZ4sQ2M0yRIY2IrdNT3t5vifGU6Fokwlfy5uYdZBdPWqgTMcKl,iv:P5lknv1vvOpfDOA3vYA1PVCl3Kzd6Cx/y5LGNlMopHE=,tag:AAv+XG2NjbOViDakG8QfCA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzUVUwclVuV3ZwVHJQRk1I
            NnVoaHBsNnlTQXlNL2dmUXNjZEk1Q1lJNTEwCmVnR01kb0k5RWQ3cE5Ed21PMjlu
            MXdYTjZKZ3ZYeDV6WmRvRXl3Q0JoM3cKLS0tIEduWUlKaHhyUjdEUU5UZmo3eVo4
            QmZlVFBNOXZDdGRCNTVHQkRVVVVkekEKeBCyAZ9zKsjJ/yIMNRFwqO4rcZ++wWi4
            ig+qU359zFY8114FpDqYsUdjr878k0+2G/7k/smc0+8qV4FJoMghnw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1586thf5vkcdf5lcn3zwjpu8ltkwyq8efrhj8lr0vdrrt9k5f3qgsxeg7gx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-21T08:48:35Z"
    mac: ENC[AES256_GCM,data:pOE0oEHr4mNjz2qMABItuz/I0XDpHBV4y7YdOvvY1vdFdJZgtjn0+5owd1fDjkhIERQZ/js7iI1zNezkGc3CWscPs+lB4Xji993cm6lsfN/eK0xhJo8BRD+mpR9LA6ZdoJo5RAlDduj2rH71P/zNOLW7F67ZZe7FQ3ExH8BaPj4=,iv:inevR/0kI9Ckm0AZw8TkW6tMloOcNhvQI6Eebiu2SM4=,tag:9pijD+crXdx0mU1tDJqzaA==,type:str]
    version: 3.13.3
