apiVersion: v1
kind: Secret
metadata:
    name: lingarr-cliproxy-api-key
    namespace: servarr
type: Opaque
stringData:
    omp-api-key: ENC[AES256_GCM,data:kjULLee8H1yXfNUB2S1IuJDpTww6Nwunl0U3E7iLGssx8T7pw9vVwTeMyJ5PVw==,iv:BxsejNdbCiBnAoqkoqtfyCb3G4WdzUCbeH87pwWkR6w=,tag:vG8SZC/V4+Aig43EDptgtg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAySXRSc2w0TUV4SW5wT1hr
            MzQyOVN0bDNIRmlUdUdZUHJsdk9adDNyK2pvCmVpYVBrSitBdzhSbjc5aCtxem5F
            ZnVpQTRodUd0K1lDRGNSTlhjRktuL1EKLS0tIGIzVkxVNHEzdkRtL1JBelZBSXRi
            cy93TTIyQkV1ZTd3QXRhTDJFN2FvR1UKngEbOGYkKQAYUh1j4kDQK6KYqR6qxUOr
            vNBhzoZCGFYjj8gmxBAd9Yf5A9CfFVPN0l3doUzx+IyciwmFaelXuA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1586thf5vkcdf5lcn3zwjpu8ltkwyq8efrhj8lr0vdrrt9k5f3qgsxeg7gx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-06T00:28:30Z"
    mac: ENC[AES256_GCM,data:+o9IQm4g9uXOMc2wdfD2TgsqMHxOqC7kfsqjH7C8AsXvOgF50RRo6nFCeghXQIpQCL5YKjhxUEKx5yA9CQFAhH8Wod9rx3yvhmcMNe1LrOAVRW2UmZf64SZ80e8UOMmA9WytYiF9KzpR9a5lE6UOHpp7MkMy+2i8XssLpFFVEl8=,iv:FUMYrZqwtKiMnOIxPfL6QFdSr0IEsh6VcLTaMHy1HwQ=,tag:GHhwC+vmHN1fKJsb1Sm/FQ==,type:str]
    version: 3.13.3
