apiVersion: v1
kind: Secret
metadata:
    name: lingarr-cliproxy-api-key
    namespace: servarr
type: Opaque
stringData:
    omp-api-key: ENC[AES256_GCM,data:mn90RxArdoTyinqx93HX5TwPuOav4/VvDbt0x5FkrK2+WhybZhhHWj5GBptqFMi79CXs4g3YcwnrT+9A,iv:TAspTiQdHpTrVU2b6UPi+yRzP9zkY2HT7EvyHjduqGM=,tag:u/z9KQl4mjwRDATt473umQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWQmVNd2w5N0d1amZ5NmFX
            dXFwbk85OGg3MlJKd3RzU2JzSkdzZTMxeERvCkhKcGw2TDF1ZjQ0OWNCaWh2UzVE
            VEEvblMyZUZlL1dJMm5QMzQzT3BmdFEKLS0tIGV1b3FIdjRXWEk3K0dCbjNvMExF
            MFZSeVlUSzJvREluWjZHQUJ4NFZvQWMKe8DBssYqu79fGx59wD/BNz3QU0TGxWju
            d6f7fvz1GT51mRuSG3JNQwhy1zXZHn/tQ+v74ZtHB75LoRB84g4Qxg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1586thf5vkcdf5lcn3zwjpu8ltkwyq8efrhj8lr0vdrrt9k5f3qgsxeg7gx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-21T08:24:46Z"
    mac: ENC[AES256_GCM,data:Eo7wl7K2Thf9iREQj78V23tI/W1WawQNLCqh49p9JF28PX3WpPuQagVAVFRXPiKvS1NzGQWIIrC6ozi32rbnqpUB6+KBQqExWgcc5nPKCIuydW0e29070lQ0hHKKkR8qKfWbMx2sZo7fvSmDTQZa0haqpaLpRT4LHrEYFrP19eI=,iv:AF9elfP+ZVgj1Cvaye6TvEjhXuUle00wgQ3X2sqiq/s=,tag:APAsSjrlohAO54Z0oCuuTQ==,type:str]
    version: 3.13.3
