apiVersion: v1
kind: Secret
metadata:
    name: servarr-postgres
    namespace: servarr
type: Opaque
stringData:
    bazarr-database: ENC[AES256_GCM,data:NfqV31mU9M7Jask=,iv:DgB4lcIlsVkGZazOhDBKKp+vvtAT5Nzok19l/yIrGsg=,tag:YIaTVSf7BIbaIDe0HhVGaw==,type:str]
    bazarr-host: ENC[AES256_GCM,data:Dklv3x39NHqNaXQjqjI=,iv:qlFEhWT1hBpnqZb0FZ6WntxbolkQKkbLlSosn5NQg8s=,tag:l7ttcobFWp3/xAeHBB7lRA==,type:str]
    bazarr-password: ENC[AES256_GCM,data:Ztras7WizZ1XHKMhBZ5c2koEckc=,iv:w6U3Vle2+aEfrFTNzu3XdaP3NUL4LfSGCiSX1pHUoxM=,tag:HpeuzUqhdidM5lSSOuLBaA==,type:str]
    bazarr-port: ENC[AES256_GCM,data:f2UjsQ==,iv:4UWp0wnIwrO9hZYp8spkFyeqbfFFlOfuWx9Lu4T9Qic=,tag:6Y4xClZsF0tv14EHpcocqA==,type:str]
    bazarr-user: ENC[AES256_GCM,data:PnEZgKkh,iv:GKoQhFhEa1U6MCgCsRG2dx9+W0pd4CeKxHIf02uXOpM=,tag:EGajsszMe4l0crvKUr1eRg==,type:str]
    jellyseerr-database: ENC[AES256_GCM,data:UkH1Ir5TN8RLuA==,iv:1lahqhAGsEDDNwydtlSqTlL5U/ehIhwIcKKimUnFLSA=,tag:dKQGoBWAAayxVTCySrPIhg==,type:str]
    jellyseerr-host: ENC[AES256_GCM,data:huN+bWO3mU91ss4PWcY=,iv:XvHJu6XgRa/+N5mWZr96Bi+WLimN3djzo7o2kPAyg9k=,tag:I1EFQtzjTUdDmyH/eibF7w==,type:str]
    jellyseerr-password: ENC[AES256_GCM,data:TsMKGtRZZJvuFr1XgJC3CftoaB8=,iv:eg376a0FGjQissavS8php9QHDttOq4PdnFqf1Aj816E=,tag:Ic8iZF1zlazQ0B+idnkkMw==,type:str]
    jellyseerr-port: ENC[AES256_GCM,data:PxNUIw==,iv:vTXPfpMqMIyA5PFumasIWUqtq8FQpadAdEcvk9sxe7A=,tag:iyqBdNi7c0trQcs0+1xwJg==,type:str]
    jellyseerr-user: ENC[AES256_GCM,data:p3yRhTmTI9181A==,iv:2XBKgVRvjlIXjdGkOiNtKgG5UAzh5Jn2eUckXMZ2N5w=,tag:9WZd/KC7AQMzUBABJJlHxA==,type:str]
    lingarr-database: ENC[AES256_GCM,data:vuAwG8Rd1y6hZfgt,iv:Rt+DorCea+50rAbV4hxQB7yEs2fSCJdXWGYwDE5ouKU=,tag:Sy5+46ixqsa1LEocLi1R6g==,type:str]
    lingarr-host: ENC[AES256_GCM,data:pLLrWT5NOX0dsEBX1GE=,iv:zpoJJCUdURW9iOP7RDFlanaHjCuG2Kpe3YUnn+2eakQ=,tag:FhVe6oOmBDUZztwfMmcSAQ==,type:str]
    lingarr-password: ENC[AES256_GCM,data:M7rFecLA8cr9lnbGCh4FNCuWYp8NHX9F+Sz5,iv:C6b9U2DnIyP4iY0/e5d5OifmlqAK0tSUUmeFYi+w100=,tag:1gmSeKBOgYl1OCqTVpMULw==,type:str]
    lingarr-port: ENC[AES256_GCM,data:I8fSkg==,iv:8bFqpSKWAhZzaMDcbls0Rnl6KU9JoU9AYp3lyWmU/Zk=,tag:x5Xg1TiJCtm6J8qKTR3OOw==,type:str]
    lingarr-user: ENC[AES256_GCM,data:zKTsPPCj4w==,iv:+UZBh7bUMIDiOQwoD/YA2vPE6Lx9h63fMacIRrq09/w=,tag:rdVc85cYCdCZLqYFIWL2mw==,type:str]
    prowlarr-database: ENC[AES256_GCM,data:f6HMEoI9C2w3PRjDyw==,iv:nJ7EXK98LJg79ax9wPHUfJGvpbwDIL5le6aEBVzygxQ=,tag:F323KrxzZx3AVWfpPFv6zA==,type:str]
    prowlarr-host: ENC[AES256_GCM,data:yMSy867ehNfUjby1/jQ=,iv:y7/CTqh1vYaahNtgBrLwUCP8RWPLk6agBenrfWuLr/s=,tag:bDZXcxCkX+3EaAxBynTyAA==,type:str]
    prowlarr-password: ENC[AES256_GCM,data:nP2tjLZzifYSO5mxkznxNxPr4PY=,iv:0OV9tx7f12CDTyiCOOH3oKXQWZsRCBCApsbSXRT0x/o=,tag:DtNbi5HoFxkn0DiRO1Al2A==,type:str]
    prowlarr-port: ENC[AES256_GCM,data:RijpVA==,iv:S8R3qzGflRnJewkkqbZ4v4pMpZho228hOTMWhLtETAI=,tag:fc8NkFvEcGlHth/+ec/UjQ==,type:str]
    prowlarr-user: ENC[AES256_GCM,data:z85eg7HswuA=,iv:ZYtnahJvwI0v4qrWDCQgbljrkJc4HSliy7HRPEeh3F4=,tag:g4nEDXSFe5BQiSlrIKghAw==,type:str]
    radarr-database: ENC[AES256_GCM,data:r9SJw/xl9UO3EZE=,iv:cCLLcGuGadmycRBAgSEtzmU88T0F05zguBpVKorOEdY=,tag:jpLGwEmqaLmViFwaC5xDtw==,type:str]
    radarr-host: ENC[AES256_GCM,data:RDBx43/xJJV8sQYqbeQ=,iv:8axEEVSypsToi/N5MU0N6LDUTk0GouaMUv2WUANPO4I=,tag:C2qZfJ5tCHvN5ZwrxoD1IA==,type:str]
    radarr-password: ENC[AES256_GCM,data:QFRY99Ozh8aUZmrLEJtlzi2pt3Y=,iv:hgejN59qCmjcfb1XbePC+iMshzHDUmBz8SITKWb0ehk=,tag:8x0MwH88Ck5y/A9PtgxOIQ==,type:str]
    radarr-port: ENC[AES256_GCM,data:EkAZOw==,iv:Izvyb2+TJrNT/ajQmnbyTJTw+lXysmhEsX1QJY+agTQ=,tag:rrlD9f+UMO7weamYqLH1/A==,type:str]
    radarr-user: ENC[AES256_GCM,data:Q0zvdC4H,iv:zshVfG5refppkdew8DK7BwIlFGN6Psjo8YgJYiVVrTo=,tag:uuUjoTXuI0LaV9cMNoyPEg==,type:str]
    sonarr-database: ENC[AES256_GCM,data:yxMyduQVdeEQIIY=,iv:oGpZmMlJnIfaXMzKPp9GQ4bwKDpQa7A47QoXgjF0RGM=,tag:rx7xbFD9CNGcRhatOsva8A==,type:str]
    sonarr-host: ENC[AES256_GCM,data:pegOPZ7ajmDexVcKsSM=,iv:UEmnGCBmZTTlxTcRAVXkU2J2eODC87Bsc9Nn//OeDkY=,tag:KJWBgKhDVy1pVYxlQNI5eA==,type:str]
    sonarr-password: ENC[AES256_GCM,data:9zby1Cg0EG9PDvZLwKpSIk1D5HM=,iv:dMe7RY3zHn4hqNH/5ZqBVjM1g5gwtdE784U3KgJrFDw=,tag:NiD1e0zGtCD4aPRdbsuy3Q==,type:str]
    sonarr-port: ENC[AES256_GCM,data:ad8aQg==,iv:khjACK8cXSNw+mBnNKBDzE5pbAB1bWGAUU1PXgPyDgk=,tag:ecdEJUPWwnWog3BVyAKsSg==,type:str]
    sonarr-user: ENC[AES256_GCM,data:ef4obl+Q,iv:2XGBv1ySaUW9qUBVknfTdmF9CWDQUJeTkRKywIT+b3E=,tag:kTfskL0M1bPIKEM6259ujQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNM0FKU2pqcHBjdnBhbnVy
            OURlMG5Yb3AwWDNzdHJTQVFhZWJ4ZXNZMUNvCk5hRTM2d2lsY0NNWXdOeUpsSDZq
            NER2ZGQybGM5TE93MGxUNTQwdEVTY0EKLS0tIGVWMWhhZFNqY1l3ekJDTklyYldD
            N00rbnZCejgwN0hjTFhoM3lCclNPN1EKbSA+A7y5KFpClPy/TcFqBXT7LMH0SGJT
            aaJhjCjrgzf04AxVSSV2XiL9L7r662iE8DMcFcM10rZKoonWeATgTA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1586thf5vkcdf5lcn3zwjpu8ltkwyq8efrhj8lr0vdrrt9k5f3qgsxeg7gx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-30T12:48:32Z"
    mac: ENC[AES256_GCM,data:be28dtaZMGc+7XD9DSs/vvdAHpLFePMfbROddMS0zzkx+Rt08uuMS+DJTXWNVqkH1qekG3Q+KZG7ofuEmsB8MdV4vjleB3F9CLAQTrjCMUu/4Bskb1tZX2cxsKesNpaAMXTFGeTh1rXrQEzUbqtzm/ZpQEojCwkJoOcPzNPo8d4=,iv:uQmb8i2YnFkTVWigORarqp0biXYkWXNcO27+peVkgz0=,tag:Q8Kmx/H4lnrE+erz+lZA9w==,type:str]
    version: 3.13.3
