apiVersion: v1
kind: Secret
metadata:
    name: servarr-postgres
    namespace: servarr
type: Opaque
stringData:
    bazarr-database: ENC[AES256_GCM,data:o1c+snTACk+OUQE=,iv:CEJ/Fx3BjGPjqoGdQKTK20tLEJdtT3QLrPdPh4H4aR4=,tag:DrGpvxq8Uk4gRdfp+N3mHg==,type:str]
    bazarr-host: ENC[AES256_GCM,data:bByi/xqfkcnA8aKF9RE=,iv:XuobCco679biIwY2KkV9s4zYU9FWth/dm4iGY5+8oPM=,tag:knEQv3IRw2JgDN8iFbQrLQ==,type:str]
    bazarr-password: ENC[AES256_GCM,data:hWpOZORykZNg0YnZgjShERs/U9Y=,iv:YQ4jJZTFpnPulO4z9fJi1SAZGaDalSZWjNsGdyzD/og=,tag:+L+ZsdjMQpnAcSxcwOYFsQ==,type:str]
    bazarr-port: ENC[AES256_GCM,data:ZO2ojw==,iv:NoJOyFvXOXtyKiqMiDkqhFc7Tm80+oBJGYzDrZwEfTA=,tag:gKn/rQbGfdojkA+/7uSqcg==,type:str]
    bazarr-user: ENC[AES256_GCM,data:OAL0tgo9,iv:aGiHaujDwHY2Fnl+7JalPVoF3Owe2KeB6l6Aq/TSxEs=,tag:D3CaUXRqD3M4kts2K2EXkg==,type:str]
    jellyseerr-database: ENC[AES256_GCM,data:j4Ft99EoApzclg==,iv:Gxw9/WriMKGzirLKZBPtmG2JMYnune+zKn+eN+BqXQ4=,tag:jSmQTi3EgfOEm6zYTqmFsA==,type:str]
    jellyseerr-host: ENC[AES256_GCM,data:u2cLP61nqtzRtNcOpHI=,iv:C3+an9tsJ9pYpozIJOMq0kxJUg1UMb8yV6Q2gkXQHIo=,tag:M7/ylW/cqP9pIGpjQpMyUw==,type:str]
    jellyseerr-password: ENC[AES256_GCM,data:9YCIagcc9ZlYM6jTp+VNGqi3gp8=,iv:IiuJez9lju8V3Bh87syCU8ucrLxpVflk5tSparNhENc=,tag:qYNvCG9Zg12O5mj76iN0Lw==,type:str]
    jellyseerr-port: ENC[AES256_GCM,data:vCxa0Q==,iv:ZwA3eiHSiVvpqzz/1NDUYovySMF8tSfOGBAXmOILwHA=,tag:tuivQox+1VJ84ZF3EG9BKA==,type:str]
    jellyseerr-user: ENC[AES256_GCM,data:Dikcem1GmlONpA==,iv:o+dsJkOIrxSskCSknBdGPR9v4+Iy/7JxTGJ5zBdc8s4=,tag:d4K0ZAuEHs8gz4TrZJBXbw==,type:str]
    lingarr-database: ENC[AES256_GCM,data:vqA3E+qPgMgDCM8K,iv:c9I5HoZvWRl0bWxYwo8zISOJfIwsdXtXrqkOGD5njjA=,tag:Q9wQ3kfprlkGd0ty+3q9Sw==,type:str]
    lingarr-host: ENC[AES256_GCM,data:wFFq5Zf04OMIO1JXTxc=,iv:FJa4H9MhmzzeTSTqRcBenRy/DSAudRMfJ3OHMbggK4Y=,tag:QxDQA397ecziXHZVSphhvw==,type:str]
    lingarr-password: ENC[AES256_GCM,data:4eG4g49wmsgTs5xk2MUtItas0kQCV5b3mBy2,iv:ranlhvzxIsl29W/Wpec1pREqKnosEe9I56XXUSwCVmI=,tag:yP5DDGKhZfmedlCbR4VkzA==,type:str]
    lingarr-port: ENC[AES256_GCM,data:+src/w==,iv:eHwKKg03IqcD3G3K9eTAjdnkKIFgDXYZ4dLV8f03e8Y=,tag:ggQ4xtCq0UqRbWfwYPNitA==,type:str]
    lingarr-user: ENC[AES256_GCM,data:Oxet4cd1JQ==,iv:eme5pgsnAS2gibgtaeUJdclCwamqHTV1TCjJ+RVUrIo=,tag:QHKymgud8+uivCRDDxs2ig==,type:str]
    prowlarr-database: ENC[AES256_GCM,data:7AHl+2Pn9y2oc0M5Mw==,iv:0M8c0CXEclPtxoaVL4AhfxA9CbZhji7PddVl6gHiBCE=,tag:21SbE2a3rL5rMlR7yCf26Q==,type:str]
    prowlarr-host: ENC[AES256_GCM,data:eU7xMWShhuBjcqoDbZ8=,iv:2G1+WJy1dw3lvopV+M3Yqs4bzCmUqxbRpWuCebhPWrA=,tag:XPBQBRKdv9k5Mzjoc83oZg==,type:str]
    prowlarr-password: ENC[AES256_GCM,data:j8vM28iGxovXxX6qwWBiajYGCx8=,iv:SGxrow8vL4xvT2OnMc2n6KkpM3rbLqSj9xX3Amm8i+U=,tag:d/ILz/m9doKMyB8GiY8TIQ==,type:str]
    prowlarr-port: ENC[AES256_GCM,data:U6KVow==,iv:2My/oMnC36sx3nO9Z2SdSwp9EvWvQxgjRHpgzTl0LiE=,tag:dBSWcKPO++H5Gv7LmYEvXQ==,type:str]
    prowlarr-user: ENC[AES256_GCM,data:UIkbYq6aplA=,iv:7Kfv1jHqcWRRE10XduAHGRRHgTvVDYfNgibspsELqU0=,tag:AnlOwcJnrAIOeT2YWtlW5A==,type:str]
    radarr-database: ENC[AES256_GCM,data:zyxQqhDN5Au+7A0=,iv:2lJybM7uCq4iYYivaxhc0GIuKv+3XY6vsczl4f3NB08=,tag:ki4uVkFYY8lipk1hTwcE5w==,type:str]
    radarr-host: ENC[AES256_GCM,data:aYekuHHqYgma4U1RM70=,iv:B1bxrn+Em2zqVjCfF15QxZn4VkJw6JcuWzqrTeHsXEo=,tag:RbVBnNla7Z1m1pFJ4SIqdg==,type:str]
    radarr-password: ENC[AES256_GCM,data:A8zliY4khJlCm0jQ/zJTaCddjzo=,iv:BbSuA1aPC2EDQpQeU4vrQ5zkkca3ovjBKmcKMxJo/m8=,tag:njtzVQyqaWG5qtrAJA2W/Q==,type:str]
    radarr-port: ENC[AES256_GCM,data:oTCA2Q==,iv:gvq2+lmDEOL89GlE+48WyH6OgFD47am3d2xotQwwOkE=,tag:EbFOmqEcjjQmqtAYBoCC6A==,type:str]
    radarr-user: ENC[AES256_GCM,data:ofu7SSVG,iv:n2sgbxPGcGSQUjiJ2PNcIuLoMs9fZuukPZFkVlMmoeo=,tag:wohir5qpNkvaZSVUb1vBsg==,type:str]
    sonarr-database: ENC[AES256_GCM,data:H0bB+xsbZRjG45k=,iv:WyhBiSIfF8ffp+x+N6Yh0jiQMputYLxe6k8NFp0EDmE=,tag:WWlQHNIxBUHyh3rsJW2gwg==,type:str]
    sonarr-host: ENC[AES256_GCM,data:qC0HvI+XUP8B/NFljJI=,iv:Q3ReNA9ZGcyzefB7AquWiP0OZbgJigsFdnZl+mZwmRM=,tag:zeGoT2RQlVIAqudEZtcTJQ==,type:str]
    sonarr-password: ENC[AES256_GCM,data:1bpIOjhjYwkxJS/M2TEld5+Vtqg=,iv:9HHtsz0n34bWqXmuvsQ2ctkhLjjW2ziGRyMw9IF16t4=,tag:DuIsiTXGgi3zovDijYcYdA==,type:str]
    sonarr-port: ENC[AES256_GCM,data:QR7cRA==,iv:oar9FayjNvhxMy10r3uNwndmtqd45CZGxA4YUUhKaFY=,tag:WMniDq9+Zql2L/sE2hpJdA==,type:str]
    sonarr-user: ENC[AES256_GCM,data:7gzuypgX,iv:hwpQk8UZgWXl+5TjI5w19tnXaNSEJapqM8wPSgtyGDc=,tag:q3Jm1e4pYuzDPxwwZo+6cA==,type:str]
    sonarr2-database: ENC[AES256_GCM,data:LBJzHU5+qSjVfyZd,iv:3PQr2i17/f62tWJwPGu7cZrRnHI8pllnTbFooS4vxp0=,tag:qIpGuNsFVEPtEynrL4MzKA==,type:str]
    sonarr2-host: ENC[AES256_GCM,data:8lWZ3MFGJLaZkNXhPeM=,iv:bO71leVILJrdXq3IUINEe5fkuU4ol7hM9Q/omwLJelM=,tag:gRu8j66RBUaJy0HcK2gq6w==,type:str]
    sonarr2-password: ENC[AES256_GCM,data:dz/QoE4kpbNvLWvMBInYbNbqqtw=,iv:Qt7n+5WWSJgFfuwBjctQAWDmWh+kb25qw8/5Jc7Yf4o=,tag:bIc+87jd/RpCZ+LOFhCYyQ==,type:str]
    sonarr2-port: ENC[AES256_GCM,data:NtIP/Q==,iv:tz+O6KpVVvNWLbhCu6zT/O3tShcXIRiKEU4lVOGRzyk=,tag:jeoN0kwcjxvJlZr0Lf7CQw==,type:str]
    sonarr2-user: ENC[AES256_GCM,data:uRvg+80IPA==,iv:G5RGVQ0zWigU7Vjzah/yGKcqxbMVkXy10qajhKXEHxo=,tag:HMp8IQevKGjeNDFrav3Vxw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4THo1dUlSZW9uSjQrdGdm
            UzNjSjVrbXRqbnBCK2E0MHM3a3JZUkxvU3pVCnUxVUZ4cXVrQ01taFJwaEc0QUNF
            SWR6V0w0Qyt2aktTK3hwK0ZkeVcycTQKLS0tIGFac0g5aHpHNytKaGJOazJlQ01X
            MFk1bjd0cnNpVHZtUk1QZkdUeW11dGcK2Y+e/a3gA1KKnJg/HIIe3hpTSye8/ksi
            syHk12JVNaac/RdxsyEydeyfEv1sv6uiQG6cSEj9RuCZ11YZejnayA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1586thf5vkcdf5lcn3zwjpu8ltkwyq8efrhj8lr0vdrrt9k5f3qgsxeg7gx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-25T20:59:15Z"
    mac: ENC[AES256_GCM,data:4yMEaFjeMKAeZlI9G7i9vPebczaGJEbRVrb7Zo6x5YZ2lzVWfqMEcibSwtdmd9gFiA7vXt0dijhAyt9WhmK9WxJsTdbN83OC/lpol021ZUSpsnFxYrojeczYvooY6wNYVeeUlD6DA/kSuvbrdkdPKUrI5b7hl+yb70OEtOrucy0=,iv:fVK0tDzCzLbYbJKmivmOy1A9FvRNOjaCV0owFKhSChM=,tag:PRJjSMA7D4xOYKvljqPlQA==,type:str]
    version: 3.13.1
