apiVersion: v1
kind: Secret
metadata:
    name: servarr-postgres
    namespace: servarr
type: Opaque
stringData:
    bazarr-database: ENC[AES256_GCM,data:j5uW+T9kDa8F9QM=,iv:kuqsuEnibR6cb6W7MWR0w/ve58kTsOMvVcRfa/fbvhk=,tag:BxL7l+ladB0NcLyuc8ArUA==,type:str]
    bazarr-host: ENC[AES256_GCM,data:Daxb6+02+OTNljFt1KI=,iv:9deKgbfkMo42UewkUS8aOgMKAa1XstfMCFK3m9Pn9v8=,tag:EkTEW1PUkDtvO1IZSu/tkQ==,type:str]
    bazarr-password: ENC[AES256_GCM,data:zjubqQdlxK+yUHH4K97nsGs0eVI=,iv:fK6QIRe6lb9etw4QX+gwQmPR71oag0Jv8m5GNTfXyOQ=,tag:0Yg86MaL5fAttnw/BP2cwQ==,type:str]
    bazarr-port: ENC[AES256_GCM,data:Y/dPVQ==,iv:EgkimyN+H5noEGAlyenD77i2flcPmjXApJ3u7WS1C9Q=,tag:6fj6LemJ22XNbWtq1XAwlw==,type:str]
    bazarr-user: ENC[AES256_GCM,data:Zk6F3cXw,iv:cSyv2Wxow9unzRoujGnG+bIewY3SeZTgOvWRFj5RqK8=,tag:Povx3DnnrvHpyVQosJaI2g==,type:str]
    jellyseerr-database: ENC[AES256_GCM,data:jA6gvHNEBOIqaA==,iv:6lNZNpgS1z41gpcMf8l9iyh5eMknPXO2Rjml8t38rAg=,tag:8E3XL1PxdAqanNxOiNwbRQ==,type:str]
    jellyseerr-host: ENC[AES256_GCM,data:IgjzabEdZZk2bP0gIlw=,iv:jsVrTZmYcvUbl3zCM0ENWjEG99ekcDxW+riGFhqFbIA=,tag:PzOVCAClFGv2WmOL0FOByw==,type:str]
    jellyseerr-password: ENC[AES256_GCM,data:+q5py4CqeW1k8y1A4IV75mc2UXM=,iv:aSEUf0OExf9sfd5ZE/LObiznKpn5eAMuqlqeVBpelKI=,tag:uimSg3mEs3PuvfobbbZ9VQ==,type:str]
    jellyseerr-port: ENC[AES256_GCM,data:oIvbnw==,iv:67tSPvEiwK/fopsOqoQn7hyfCns6/sURvyzdsu60VD4=,tag:WPrxk852n3exVJe93XYkLg==,type:str]
    jellyseerr-user: ENC[AES256_GCM,data:x54L/5AftbkrLQ==,iv:Xyj01CS7X63EKTLh3MO2Sx91JEMDBR+K9+zcfm/rl/k=,tag:zrqFSXbZ8O4oh+WdMYqLVA==,type:str]
    jellysweep-database: ENC[AES256_GCM,data:ba+fho9e8yhspA==,iv:q+piNgc98pWLhFsIHo1AjUCqN1JeEHAONirawu+sUt8=,tag:TS2TLzJLRzYfQhUh+nswaQ==,type:str]
    jellysweep-host: ENC[AES256_GCM,data:zoGopkQj6jKX5jYh9FrCQZcq15uWNnG+parxKj/omp1E+uc5b9SHYJi3d2m0XoG/5yYDaEA=,iv:1afxUiLeQyTtM478yiW+YvPb6VxxUJ0MKvTMBlx4pxk=,tag:Hbuq39YyvXxN6YgLyoQ7Ug==,type:str]
    jellysweep-password: ENC[AES256_GCM,data:kRcVEam+ANB9utVCejTLU7cGEGNzvAsgd+H+JmXrPXkYYljda8Y+HTbiab4ThuxO,iv:2EJ7VUQjmMU1IzcU+/p9fPXF0ZQRlfUIK7PTYE6FVgw=,tag:gpNZwDlEyTl+DRRBG6crog==,type:str]
    jellysweep-port: ENC[AES256_GCM,data:5XHttg==,iv:LAzb9LOIsdilNrZuSEJNI520YC66zELZ2yMT4gso9rw=,tag:1GHH/zbftMQptirnIVEyvA==,type:str]
    jellysweep-user: ENC[AES256_GCM,data:jKtaAip/uo0xYw==,iv:cKvk/yVmECIShO1r+2W1m5ZWme+mCYRAxpSEQvZKibw=,tag:9oXWJT4ux6B/FHF40Rfu2g==,type:str]
    lingarr-database: ENC[AES256_GCM,data:mdk3xACSjSCrj3UI,iv:gNYgVpByY5IWKeXiFG8KIZ8ajrT0JKwvR8YWWKk8P/0=,tag:QWS8dV/V2aP1VPA98YxQdw==,type:str]
    lingarr-host: ENC[AES256_GCM,data:mBJAG3WwYaoJTVgy9Z0=,iv:ZvvlSuPX0NEW/m+FUIXtHCQFGja7Cz63RVIY31CCxoc=,tag:pxUAP6Ko90fuYiKBJ9wqGA==,type:str]
    lingarr-password: ENC[AES256_GCM,data:Iqgj6YVGqaK4Y14ithILK1TJ0bc9rs429BuT,iv:gApY1eoS9n8kr1UDUT9LWqJVhpoumCyGlqzmtgb4JMk=,tag:TcJOaaVwc/v8KU+47JjQug==,type:str]
    lingarr-port: ENC[AES256_GCM,data:4s+2/g==,iv:Rtpy0ypFprTZocapnRv2XnvAhX3apNc0+Pt/dP5qCQU=,tag:PTQdVKR75/Ic7EBBWvO40w==,type:str]
    lingarr-user: ENC[AES256_GCM,data:YRvrbhwrWg==,iv:Vc1yf3zzLMSn/xWI10cz4Ax9f/yBBVMXlXWhAK2qjHc=,tag:hB+KD8l7i2tffUedofzPHg==,type:str]
    prowlarr-database: ENC[AES256_GCM,data:54qXM9N2/9RdmebY/Q==,iv:aTIl08rPlz36XxQ5+0PW7fAf+MhQfz25cuMWRDZ2vC8=,tag:QZf/EQFRbKyam6K1Ke2b+A==,type:str]
    prowlarr-host: ENC[AES256_GCM,data:apb/NdzBGjsf+wcbBNI=,iv:/c6vKv45XT2kZGom6LpTrLfsAqbOlv+p/nO7Br/oirw=,tag:QLN6zTvw7WqLUDmKRM4JNA==,type:str]
    prowlarr-password: ENC[AES256_GCM,data:gXQnDy2PpL778UQIwhrIBn1z6s4=,iv:zwrMSk/Z8nFThQVl9BS8g89uK+AcJp0dw+u6TcHum4o=,tag:Y+wRQfSTtS6cr5SArIAysg==,type:str]
    prowlarr-port: ENC[AES256_GCM,data:BecqRw==,iv:je1Q0C2AkfytFsatfca6qnAQmdDXiOLyneFpddTxzgQ=,tag:2NlmXvuyRoDnyDvXfft4lw==,type:str]
    prowlarr-user: ENC[AES256_GCM,data:Kc0XVbBAkxU=,iv:wGor8PPCyA6A2vStbMQ7gZqIRHAgvBHsQza+T6tj5z0=,tag:9T105DmD9dcOH1RWAjP2Ew==,type:str]
    radarr-database: ENC[AES256_GCM,data:f/zZhL5GDKUaxCs=,iv:Zqrx2lkaA4sBy8Rjkur9r/Q0B23GkVATksFJDJxiF+o=,tag:iBSSQNTylMmzKx+1249K/g==,type:str]
    radarr-host: ENC[AES256_GCM,data:K2p5gGN3sVjZmZIatX4=,iv:LwE46q13zSpr+Nu1/qzuvTWPYSOsGa6PO1DRi9i0P8Q=,tag:5HW+0vTMxcJLfZewR/BAlg==,type:str]
    radarr-password: ENC[AES256_GCM,data:d1HndHr7zDNpdqnp0yj/GeNOA2M=,iv:ppQpMrnEqqn4ne7CmaM3uAWJzL6uAP18P7FCt6ETxl0=,tag:fHEMzfq0ZIM8RRkVCLN5DA==,type:str]
    radarr-port: ENC[AES256_GCM,data:/pwJIg==,iv:SAJ4ylFs4eN1oHW8ogWAQktV90nRjUESBV4iyRanpPk=,tag:vXrYjBsqcxDHDVXHSp/J9w==,type:str]
    radarr-user: ENC[AES256_GCM,data:ygFYRDAS,iv:9URDCOsaNv72hZ9E/wRxnmMQqdoWfo2DId1kn/mZMyA=,tag:wysjgCBK1eXMjkE5tNNQ/A==,type:str]
    sonarr-database: ENC[AES256_GCM,data:667uE8mbFxP+fHQ=,iv:naaR/w+HHZQK4DTMNEfxOBYIT5qlQlOU1fe+tvZ4JjA=,tag:fmJeXwbiB1xdzRAHVy7E+g==,type:str]
    sonarr-host: ENC[AES256_GCM,data:neyUnKK196V7SaqzL3k=,iv:BoOe3tyGKGqCgfAFMmeWv4IxrSXzZYdXNZ8MRRcvcto=,tag:BPJi7IcHg8VEaW09p4Xu5Q==,type:str]
    sonarr-password: ENC[AES256_GCM,data:CZvEKPtl8nPZXcZJaAvsa4IeqqI=,iv:mx3JdX3ruvOW+yV3hv+bhzTE87ZNNameGx2w/jPKpyg=,tag:dTehP/u/UE7rtx9AnLrsmw==,type:str]
    sonarr-port: ENC[AES256_GCM,data:07Rulw==,iv:3T52OXg/cuZruYHWur+ELY0XvA42VDdxeHxdfWF1X34=,tag://ShXZwRhRSIZFqfnu45ag==,type:str]
    sonarr-user: ENC[AES256_GCM,data:/c4hFxnC,iv:3fPz9OFX+J/8ZQnR3p5ejlSIgY1nQGMsbOwM53oujk8=,tag:im4GtEb+Iss0rQpMdkrLbQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4cUdaZ2Z6ajZLeUQwTDdy
            a2YzNlBIRHJMVXB0aWpRSjk1bjd0cUlGaWprCnpXNGhiTytxQVNPd3VRQlpteFpF
            dGFoSktCMHdwektaUFRIbmhzRkxZdGsKLS0tIDRVMlRCcjNackRabG5tYlI3VDRH
            UTdHaExyQks2a2s3YnpXSEtGK0lLbE0K6qXwVCBzeUlnmJIYTyMAfsQMoXI2wYvy
            eeU8gNEgrWDQa4/Ha0VANqGU61OySBtcZdhtuE8YipfiUdCVLsgkEw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1586thf5vkcdf5lcn3zwjpu8ltkwyq8efrhj8lr0vdrrt9k5f3qgsxeg7gx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-06T07:17:13Z"
    mac: ENC[AES256_GCM,data:EUn2imL5HUTgxjVEw8EDQ/dQPD4WICXlBqyirKMR8Sm29KSRTCtVJyTE4nl2DZurM+2HIF7Js3WEmunWGht8N3hf3ziWaLkA7PqM5gvPJQmtTuMTpK9bIbWtdQxqo2j+AZPjHwsd33k2jXS6zKoihynvrnrpCRDHrVRz9rW73ds=,iv:uTeOPlMYaqzPXM7Az/f30OlBi97BF5MMsWdBA3wbtJU=,tag:Bz0vqhA8axDX0JWZTqIJXQ==,type:str]
    version: 3.13.3
