apiVersion: v1
kind: Secret
metadata:
    name: unpackerr-secret
    namespace: servarr
type: Opaque
stringData:
    UN_SONARR_0_API_KEY: ENC[AES256_GCM,data:itDCCK+65hwZMBeUYH1yva8xE/99YoaYbECf/1ONZRo=,iv:He+e79AyblJTQnJMqdbA1v37Y8bN4x+zvULppQS3tPk=,tag:NnrbwQbqBPdEol+yksz3Ew==,type:str]
    UN_SONARR_1_API_KEY: ENC[AES256_GCM,data:NVNGPUsRYMJiF7iojpHdu2SuVoL9jwxu5ICNgsvceWg=,iv:vVO8qhrCS7A9vnIx6X7v2kjXChsoKUdeVclBLPxTomM=,tag:aH1N7GCPpcYLes4M0If3Xg==,type:str]
    UN_RADARR_0_API_KEY: ENC[AES256_GCM,data:oN+Nz1N+8QPWUWgonEkAPvhaElvOQBiHloYvL3bRACs=,iv:FJmulmGF3XSTnGhfiC/7QncQBdSTR1oEv6ZCfViyOIY=,tag:MzfPtGsJer7Knvk+VnCc/w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpT0c3cGs2L2NJd29vWkcv
            eEw4LzRONkI3a0w5SGwvVnhPcWdXRE1BYUE4ClMzL0xULzBud2ZuTnBpTzlOWEMx
            SkNJUDdpcis5SjNISzVldHRTNVYvNTAKLS0tIHBWb1BZd3oxQlc2OHgxaThQRXpG
            YXlRMmFUWGVzVjNDQ2dueU5KWU9tQmMKrGA/lpC3Dh4Jqe9XJbuBfRuqZz0+vssh
            ZjdN0sD6/eM1TFVWvhD985XbPY87dHz4hpQAezHwzoA37lsogfhuIg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1586thf5vkcdf5lcn3zwjpu8ltkwyq8efrhj8lr0vdrrt9k5f3qgsxeg7gx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-13T08:34:36Z"
    mac: ENC[AES256_GCM,data:crPnR1A8Rudso5+n3/kius0VAb336OWIkKvFCX+Mdl3rvsf/6jMcxKFTSr0j/tkbaNsa44CmB5kBvLxTjM2kMlruXx7odY3eA2EAdpwPOLqLU0cKi1i6XG2+DQfQMvv3gQitF9k0oNI6XiaNfHlREOoYUsY22uVbsON08ZBMwuM=,iv:RygOrLXCsZShceQ6K38PK+kQ0OpD9BIByKyVJtK7Ot8=,tag:a9ar8cVNNd360xK39HN5fQ==,type:str]
    version: 3.13.1
