apiVersion: v1
kind: Secret
metadata:
    name: unpackerr-secret
    namespace: servarr
stringData:
    UN_SONARR_0_API_KEY: ENC[AES256_GCM,data:h6+Z2muTOoGkF+6VFs4ThWwHXhIMkKzyI1RxUqUZDQ8=,iv:HWLh0QUmes7YubMBTvuKWtdVXyUweml59u6GvNPknc4=,tag:If8Y05e4ERw3G+UjoUVD1A==,type:str]
    UN_SONARR_1_API_KEY: ENC[AES256_GCM,data:NJiTEYT6CmmrJQKCd6Ldi2EK5eClpF3SDnlJiZsg2+I=,iv:FxnGDCmRLP7yRXymakICAWiyZqXtN4x0wkJs9VHn4pk=,tag:Za8PjRxcN0CFuFvM+ge3dA==,type:str]
    UN_RADARR_0_API_KEY: ENC[AES256_GCM,data:d5aQuwkjTEOwaS/IFjr9D4Oez5C33Wf8o+VzYZ377z0=,iv:VnTf+woWNnQkYaYEY2bTJaZy572y3K4WAZ7+1Mq3s8M=,tag:igIFaaeUREwdvlOiCn7LFw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLYW9yMVdJRjYvQlVjMDJV
            SHRXd0pOZXc1eG1QV1o4NnMyUGgvNFBmVjFZCi9vanRjSGZpTldud2FMeU0wYm1I
            azB6cmJBQWl1Nk9IcVI1a3BQd0lTaVUKLS0tIEpreWRHbzBmazI1T05LK25ZYkJZ
            NHBONlJVMldnVmsySWtJKzJEVEZyOVkKqfnuIw/jhJRvDuMJn36MVwwPo7F8mj6b
            kTk8+qh5sh7hpHv+eDKJTALO8S2URAHUmR71+mHhycUgfweP8skhAw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1586thf5vkcdf5lcn3zwjpu8ltkwyq8efrhj8lr0vdrrt9k5f3qgsxeg7gx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-04T07:36:44Z"
    mac: ENC[AES256_GCM,data:CNRK3g0RPnOkQm98ptueRm49vrqNR184TdiY/IfYUTxRp/SAZXhOyYtFBURpQlW+IzeC8629Em2T0sVs7Pwy16mxchf4OzO7r/Qk6rB7JH4pYK+dQHFmrFqXNsRQEIc3D6CTdi206+ImGvNgg6Qa3+MVev8zxKzAeDiyLP48/LA=,iv:ORZ/irV+OD3cYUYrTNZU0rGTAHHN/EYHGRQVm3vwltM=,tag:mVnkcZ6rgq1B+yDNrxaV2Q==,type:str]
    version: 3.13.3
