apiVersion: v1
kind: Secret
metadata:
    name: unpackerr-secret
    namespace: servarr
stringData:
    UN_SONARR_0_API_KEY: ENC[AES256_GCM,data:dR87LEPlNhPLc3Ku47MOcdp1+QMaAuAQNuLVNtdcpwo=,iv:h5f23AY/7wpiaR31Gs32ijt7Ry83SRPsdva5XT8Qf+8=,tag:0L2QpT9xzwgibnn6n45YEg==,type:str]
    UN_RADARR_0_API_KEY: ENC[AES256_GCM,data:oVZ0xebAInglV4CzGiCSnzRUsiatYLjRKiwNKxYMYtg=,iv:/GJTQ73C6Zyq7zoYMVzKrurDCowuP8JGHM/xNG5/2EU=,tag:TXaO3OMTDCP0sm8/83h89w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Z2dLL0dhL1k0SHhNeFNU
            bmJUcC9zbG1ySlVvQzZFOEJkcEZXeHREbnd3CjIzclkxczhCcFVna0VqVCtscEJ4
            ZDIyRThjQmFDYTEzeHZxK1ZXRWlaMWMKLS0tIDl2a2VOaXlkdTdKSjFQNzJjV1hR
            ZmdQOFlWbVVYZS9mN1Z2SmVvQTl1QVUKWFWHNlbKOxZBgsw7fu1n4Uc0f3ytVb9N
            c+PFOybubgNrWARGlM5rqWo/5jsd5LukAJuUgT2Y+32sEuNXTzB5kg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1586thf5vkcdf5lcn3zwjpu8ltkwyq8efrhj8lr0vdrrt9k5f3qgsxeg7gx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-30T12:49:01Z"
    mac: ENC[AES256_GCM,data:BvSxs1a187tLqTMYODx4xnoAoMTLfay+MhcDI3Dov8qbOmuD3iH7orLSVXGPBoMY8vfXcWC0BBAsTsEUCnIP4Kuq2YaWDr0VntPDYBsQniEnuCDhbC/fKbqbn5a8EtgvN8uJXeJeftyhdSYqXuKOyz5cV5qMEEW3dfESna6N82A=,iv:WXw3rLog3mAIPsmjJjdC9Gl0WwSFrj0VirU3RzKdaRw=,tag:2+caEP7XrL5QqtqQ9jRUOw==,type:str]
    version: 3.13.3
