apiVersion: v1
kind: Secret
metadata:
    name: vpn-picker-intake-token
    namespace: servarr
type: Opaque
stringData:
    intake_token: ENC[AES256_GCM,data:M1/JlrzO53xAOav4j99XTFuR4kDhfayCYZgIMNdJsbWviAovUrw+G+2uUA==,iv:LGUvEJ0n78DOVNfcANMYuiBJbusiU0dsmjV1yiIUzb8=,tag:RVZnXXufTDreu5aX0MKAlw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzV0s4UzlvWlJnL1N1ZXUz
            RmJCdWpiR2JsUzE5bC9XelEveTZEYXdyazF3CnkxdVQ1QW05V0E0SFQ0N09pY1VQ
            OENhNGJjZDNpbG1BOXZiM2FMRW9lZk0KLS0tIDlwY0dUTFRvNW5sQ2g2VFprbjJU
            SUwrSEFlMnM0TVAwOWhpa052amtnU00KscZ2V1rxI6MwRSXem+yr2+QT/2x1/0z7
            rU9BEHvXgO40wAA1g8HyXJQlwsAckjgnAkzK+n8u6EifI75nGj/ytQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1586thf5vkcdf5lcn3zwjpu8ltkwyq8efrhj8lr0vdrrt9k5f3qgsxeg7gx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-06T00:01:56Z"
    mac: ENC[AES256_GCM,data:7zU4LQRVIxh/R3EtDYoXpHybuBGU3ua2F0U1BqhjKj02y8BV1No8A+6hia7TpOkhaMi12YiJKFnDYyV9PaCjByub23IDStvzHw49q9D6QZD/KbWJus72gCBV/aycMQgSz6gYarZ7CmkDkjih7utjlcRySN0/XYnj/rZce/kIkBE=,iv:QZpj/CPujF9Bfurcyqxob15ape8QYBPUPggqrWm+Hok=,tag:aGZDt9Ikwywy8tp/9IIzEA==,type:str]
    version: 3.13.3
