apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: cliproxy-free-config
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - cliproxy-free/config.enc.yaml
