apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - storage.yaml
  - deployment.yaml

generators:
  - ksops-generator.yaml

images:
  - name: ghcr.io/actions/actions-runner
    newTag: 2.337.0@sha256:e5496277be5d09bc968b3d64911b74e219ac4a3f2edce956a3ecf9271bea1ef4
