apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - storage.yaml
  - deployment.yaml

generators:
  - ksops-generator.yaml

images:
  - name: ghcr.io/actions/actions-runner
    newTag: 2.338.0@sha256:4ffadc0002b2581327e06101fc8c06cd189232baf79fe561fac9caeb76f5e807
