apiVersion: v1
kind: Secret
metadata:
    name: gh-runner-secrets
    namespace: gh-runner
    labels:
        app.kubernetes.io/name: gh-runner
type: Opaque
stringData:
    access_token: ENC[AES256_GCM,data:7rTdh67/dDA6FG0cvsuoqarfl9qxzQQ2a0dQ0bY=,iv:33oFUWjwEH27bODRRqAmtwgn5ePm8FX5GfHMDTCDmRo=,tag:ZKv9+qAnob850l5Kz4NLDw==,type:str]
    id_ed25519: ENC[AES256_GCM,data:hOzneFsRabdTTCcaio12FYB9PApawVdmR0WGaxuralpHSLZwQSVGO/EmYIWIdoNY0/PIOzEF/u1ea+ICIAdKvJuB9MCMx9FZfGVfXj0oygApoJ9BVRiwwBWtLageSYwru1TKd/gTp8610mMc/a+2yMbwfYSGpCOKLdatNHz/0NCpauEeYptaXc51iN5gG8yyCf7R/Sf3/FcwvffUvz+EpGaTj+jBx5R4XcCHv93wEwKF3K2m8Kx7QV3keUfDKXiWZGXpr56bGB8Co1XsfDoHSkj1/zE1HXuewLUQZaOjAMpFiE/DFyfiLNcws0BqrIbHJrm/8VpIZ9MIsdG89nixKIDwv+UIkTXWONCEYMNyf+Qre4iGRniH0jEbVm3WSSrLlooW0P80q7xZ9iyHRDCJN+zmWaCuZWmHL/3E44R/rTLMp45ICwD3rpCt3HJC0ahz8Vfmk3OgGNybXMJZASFc8WKmn9KdP4pbtSdjA+hn76OPv00rIjLDW5SgNUN7D9WyAiGB7tCaG0bNj22c/+mwbtMOM9ImNvpAOYzHFNN1hPuvXpS8FXTW9YJcLlMSENrN,iv:fFl6/lz//OYT7TkfH5FeqMz29UZKBiu9u70fCUIblBk=,tag:fplsffp9zLWzuMw9i4C8MQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3WktFeWJ2b1owYXF4Y3hG
            YnVUWDIwY1F0eDdYTmRLR1BqeUdWYkcrdTFFCm9Ic1RmSGIrQ3pVWlVjaTBpSC9Q
            T2E2dXBPK09jM0JZbXdGZzJDdXdMbEEKLS0tIDZGTFNnUXBCUHpqMjFtQWF0WTg3
            blhZSk5GTHBRUlRUcDJaTnFWWnYzekUK32JSCnOYlH0Y8ZBlTzBgWgEcPE4FP5Yk
            hs7YMQBHjoSRE7o9DEUE1epYR/6Rxb8ADDuZZZ2F9vd0TB3WdN+bXA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1586thf5vkcdf5lcn3zwjpu8ltkwyq8efrhj8lr0vdrrt9k5f3qgsxeg7gx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-20T07:33:55Z"
    mac: ENC[AES256_GCM,data:v2AJit+Unco+9l3ZcHr5wwRuCPSVeUoxdMZIXkELv5zOBodFuYMDxjImkMV3cv8ONssxmOkEnZeeaVwlNlv5sFOMEFtAxDYc26caoGFdYBRv45NheVpYTH7pvQkjPl7yRJoRDh+rMH3FBIdaNNygK/EK1UQ+RVTMbcOIQzD1U+w=,iv:uHr2OVh+LkbqfRkGqlHDKNQF/vGGZ7fRcgR9XJAZxcY=,tag:PWNwSijlfbN+HoSx4cDtpg==,type:str]
    version: 3.13.3
