apiVersion: v1
kind: Secret
metadata:
    name: t3code-v2-mcp
    namespace: t3code
    annotations:
        mcp-hub.epaflix.com/revision: 20260930T193743Z
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:9ww7a+nStOIefP3JvfXxKy8SuQnpt1tkGtVRlFP67FbS1nwbrXzC28WSVA==,iv:ma0bGy2+fz7vpBedoGh+46a67Y+OPBSza64zT993Z2s=,tag:hN6vrNKN83SlJwXGo7G8XA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGZHAybTIrYnM0ZC9Lcmo0
            cEp0K3FsQUxIamwvWjhpS1hGYnhVVEgxVmtrCksxWWRRaXVGN1hBb1liZFpqVGlo
            bHZWYTN4cFNiWFlzVVJuVDhFSk9FcDQKLS0tIGJOVklwaEdXYjJXNFJhcmRySzdH
            RlFIaVBJNWRiTHFCWW1oMDY2S1UwUEEKLCislZZOHCLEat5Mrt8mjLm3owqjXBn8
            M0J+DnSd/ghyOZ6BPs+uiZVrG5eRFT2+SEWaNhVOm4LoKWNyG+onMA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1586thf5vkcdf5lcn3zwjpu8ltkwyq8efrhj8lr0vdrrt9k5f3qgsxeg7gx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-30T19:37:43Z"
    mac: ENC[AES256_GCM,data:s3ethER9OGTU2pNTd4uo/lTbxoXoe2D0UwFZNwbY5nV5OkH4t5TMBGHhsr8nG7dI77Djrgx6ITwzTB5TkeGBMDEVzYY1xi3gsuk5exY+ANn40MuCbfvIcIBv+CQosxPtMb1CqGYCBii7Hqlt/RrMLWNz4UaY1RKWgXLKQrpoit8=,iv:/7JolbRlQDHiL3qjFBwHCdNGDMmIwSRPTCdu5I8S3v0=,tag:gA3XtzF6vjPvCbV2c92yYw==,type:str]
    version: 3.13.3
