creation_rules:
  - path_regex: ^\.github/instructions/secrets\.enc\.yaml$
    age: age1586thf5vkcdf5lcn3zwjpu8ltkwyq8efrhj8lr0vdrrt9k5f3qgsxeg7gx

  - path_regex: \.enc\.yaml$
    encrypted_regex: ^(data|stringData)$
    age: age1586thf5vkcdf5lcn3zwjpu8ltkwyq8efrhj8lr0vdrrt9k5f3qgsxeg7gx
