services:
  node-exporter:
    image: docker.io/prom/node-exporter:v1.12.1
    restart: unless-stopped
    network_mode: host
    pid: host
    command:
      - --path.rootfs=/host
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --web.listen-address=:9100
    volumes:
      - /:/host:ro,rslave
