---

apiVersion: v1
kind: Secret
metadata:
  name: seerr-oidc-secret
  namespace: servarr
  labels:
    app: seerr
    component: oidc-auth
type: Opaque
stringData:
  client-id: "<AUTHENTIK_CLIENT_ID>"

  client-secret: "<AUTHENTIK_CLIENT_SECRET>"

---
