apiVersion: v1
kind: Secret
metadata:
    name: ddns-updater-config
    namespace: ddns-updater
stringData:
    CONFIG: ENC[AES256_GCM,data:we2tvRz/HIFWAmCzala8xnbcEfaTnpbr8iFNKR/qTNwaLzAtzcJu2ukMGpouASg76Ty/cs4og4yc1Z2jywtfh7s5f2pPD5otgLr2hpMr/3x5BzIqFytFtUW/FFoAe9kAvCG9vykjQkorWliVBvmnE5lXpJPMqIfoztgc3SU9ueEhGMFc6FiM2Pj0Y8fz4Slsttui6ZcCtgqkUyROphT7sT+TaZmna309MOCS8dd0DQoPw2qeVtBz6vOu1+j34bBi3tXKbMkWNNFrlSPtnxRXzyZZQyoIxmXi3mdyQhZyY+HK/LCcoD75Cs9bdd+0mr9HUXDCBDiNYpiyGreoIh3LfcHHZIKJgbaewV1euou32UiWQ0UgiPIG36U8VIlBsQgTFfSqR4MqZrjeNiQ4/hE4EtdetsOq7rnOdmKfdMxQ1b7B3Ee/jEhXheh6Dg==,iv:S2OGX1f5zRdbk4TakhS8g7zaBRM8QNANfPgrGNY49T4=,tag:qlPXDt2+hSoBh5wiMqYqmw==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqRENPZk9ubjdOV24yQitD
            UVN4eVhvZTdwbDNwZzRTNVJLWm9haWFCWVU4ClpIRVhRNExEdG9HZ2RrWlVyRXR2
            Y09YTjVxQldQano1RmxEL0pMN250djgKLS0tIHhWTWtqbElqSUNOY3dZaDNMTm1K
            RTJ1NTJudXhCSDJvNW1CczR1MmFncUEKAtF/G8b+LEtH5Ee8L2lkbjy3i9g8jH99
            4NoPh3QcNvKLolGXj8wDHSUlY46vDrmF3SrNXtGVcGKHa2QZ6Cxwsg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1586thf5vkcdf5lcn3zwjpu8ltkwyq8efrhj8lr0vdrrt9k5f3qgsxeg7gx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-10T09:38:43Z"
    mac: ENC[AES256_GCM,data:I/ORRQ0fDl6ZC92btNEqMp2CdpryQcuAFmtRakbOpHYqHuuD8cMeyr7oPtw///RWOG0paaNeQjDbjIV1kOZxDLZxOLAx0vdOURl911bWQt1AHLEG09wSIVJOvgFFMJrVlA3VOZN18r+ndRMDFOYaDeUbfWZqL3fsjMxmh6yQiQY=,iv:ll+N+iMBlr0XUfFr+TrHyP7DiOiCaum2Fp8KsYFkTYw=,tag:Z/f/IT1Xb/zy6Q1P+nQpyg==,type:str]
    version: 3.13.3
