apiVersion: v1
kind: Secret
metadata:
    name: ddns-updater-config
    namespace: ddns-updater
stringData:
    CONFIG: ENC[AES256_GCM,data:4KI3f0LVl/al65+SwyibL7EH+rJOtY/F9A7lT1u/Nk6eSIAowLM0P+Sd8S6LyttPgWqbiL8Clp4XBwjmGZoZ6LfYTTshIPEerpq0qYLYbP/uDXFzOJbyg5C9jo/K5aeav2EyDGWrwpNawDL3IXqQVRjB0OLvKxGfOi7A2JSc04JK/PaJIQ3AO+TfyGggy9mCMMzr3eGriU1i6f+xhLpWAhr4l6m83w2OiXF75J3OwY6HMj+P5lHJAg39RmqvfaK3VATWxQJhheG1Vj3IjsvWBPJ15GBepShOhcSjsttWATQZT/L3gVa6UehP6B33M1Vn/G9zewaLBKpIHJeYHYLs5EleFwW25h2zS9YkiF4PYcnr9g7heq8nrPPj7s9Jnyo+KXwPxjYpOoQs9bi3mjiFWh5/ft647kSONvj/o4xRyfu5yier8O01qcsE9FevrezU7aKzyjStTCHHaPD65JE4UH4MVR9iyGIJgQIY591iUhfgfAim+t/088tuYaiXpxTy96ckQ8CbvzvmeQAGIdKaOJa+RDaLwESR7ifkG6C58N4fJgqWWGeC+/AzSo4rQpKQRdQFAMVxCUmp6zIR8DCxNsjXxigfQV/Im4VfVpNpXjp32SslKRcIkXZ33d/5fu3yGqWZA3zFz84QarkEBBOHSt6jjDMSkds2EwcTm/MSeVO3c1xkVF3XVn5rwGEgVxWi6cmov8kpf21IDkRvEvXVjmq83BKCg/lr9E8JLKXB+yV9iCrbRQbyd4O3Uh095ujLy6f2hnaM7dEn98XqQQhMEk6g9kNdO+zh65EoD9fI4xXc3qqCC06HjJLentP6KIzDj1/7nUQIlsqzhA8/PqzJHCE=,iv:xD3TltHr+QpqQWOZd2tQRzYbLOJWkRHgpLlx5f7KhHU=,tag:qCjGGlQu9ls/hirh2JoINQ==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqRENPZk9ubjdOV24yQitD
            UVN4eVhvZTdwbDNwZzRTNVJLWm9haWFCWVU4ClpIRVhRNExEdG9HZ2RrWlVyRXR2
            Y09YTjVxQldQano1RmxEL0pMN250djgKLS0tIHhWTWtqbElqSUNOY3dZaDNMTm1K
            RTJ1NTJudXhCSDJvNW1CczR1MmFncUEKAtF/G8b+LEtH5Ee8L2lkbjy3i9g8jH99
            4NoPh3QcNvKLolGXj8wDHSUlY46vDrmF3SrNXtGVcGKHa2QZ6Cxwsg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1586thf5vkcdf5lcn3zwjpu8ltkwyq8efrhj8lr0vdrrt9k5f3qgsxeg7gx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-05T07:11:29Z"
    mac: ENC[AES256_GCM,data:pSrsYNdbBayTNhgXFxaX9o6n1v2bRGpTUjUgkz4GbX1vufTl8UbU2QQjlbSjiKvKdwc+07VTjAlwlVtYZVak+Jiq0JvdkiVou1M1zZ8RA65Mou4PFZaLuCFjVzcaaNAMo7ne8rusiZk6Qd0leMAbBADf/yi/nVy9taFjAcr9Wcg=,iv:nuNYUdcdXhM2Bd1xulQxMbieeWnZtxXB1wc6TPbo6Rc=,tag:uDxyQQowEzOpfW3+cBNWTA==,type:str]
    version: 3.13.3
