apiVersion: v1
kind: Secret
metadata:
    name: ddns-updater-config
    namespace: ddns-updater
type: Opaque
stringData:
    CONFIG: ENC[AES256_GCM,data:a8LQD8rGR0l2ioU7USgfctsWL7Gz9zBv/hRc+8+bvaBcRh5y566xkA5jmyEFyzR8en+XoFMHH+NFXDJomwv5njintP5Bc7/55thB0VWLz896BNViDa1KMwYp1Ujta//K/U2o7SLXwFmZOdp+aEjKB16Xrn3r0xmGzW9GkTtN6EjP5gv1BIFGwK0u2JqIhGmtL3K37RbldjEO+Ym5mlv3cSnWg8mHpeV6yNDmMVIH5BSPQvaU1wE7rdhWgTbVFMoWxgMFmsob/d28jrhQZQ==,iv:2fc1MfWKmHDzVe8CVE3ZGoclyAa+CgsDCKSxRATsKl8=,tag:ePzqt7nf61u/LQk/lbXzgQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhSkRQbGdneWh6OGRWU21P
            bnFrR1pCaTJnRFJJdmg4VTlaUGl2TzRCS1FvCkp0WW5ObTNUcTAwMFhHdHl1azMr
            aE4xRW9SZmFya3B5NHJrNURkK3R6MVkKLS0tIHBPOEwwOHQySCtNR3VtZS9yeVhz
            TU00TVBlR1hyNklFd0xYK2hpR2twaTQKPhz1ZScnXJvWxqZrnhZbddGeldr0LY9o
            u5aFm/xInF1gfa0XkvfWRf8nvfiFAHXWLkUVdaDxOGKU1WTqDVKuaA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1586thf5vkcdf5lcn3zwjpu8ltkwyq8efrhj8lr0vdrrt9k5f3qgsxeg7gx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-30T17:19:46Z"
    mac: ENC[AES256_GCM,data:TCCbHGlwYNnR69DKa4Kph9Q47kk4KAYdQMo/ho96xEnq4OKVIbRkqS13MOvDa8hGBm6FRf1XCPefcqzhGCIv/VqGSlESVzz65Vu1dnmxewRNgXa3GbOyWWYC0agxD7is3Sns9TdCwbOWo20J0z/3ZyqXibGXDq5X4QiCIDKI2dk=,iv:Q/3VRFu19tXU6EaxQmhVDakDsMYMdmvFu/nsyyGXU0A=,tag:AZO5aSvLg7YHd3s1srHmlQ==,type:str]
    version: 3.13.3
