apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: ddns-updater-secrets
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ddns-updater-secret.enc.yaml
