apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - storage.yaml
  - deployment.yaml
  - service.yaml
  - ingressroute.yaml

images:
  - name: ghcr.io/qdm12/ddns-updater
    newTag: v2.10.0

generators:
  - ksops-generator.yaml
