apiVersion: v1
kind: Secret
metadata:
    name: cliproxy-client-key
    namespace: odysseus
    labels:
        app.kubernetes.io/name: cliproxy
        app.kubernetes.io/component: client-key
type: Opaque
stringData:
    ANTHROPIC_AUTH_TOKEN: ENC[AES256_GCM,data:vp4iSBGNuI2OWSYFqsFfCHfBN5OXEgPqeKV9zic2aY6X5R70dzZfIi/s4U6UBgXOS5RlPw==,iv:50An6N3u8Ff41MdREhrrmp7c9a7QG+kZ9TxcajJJYUQ=,tag:d7Zj/67NxdbdOevIRg+70g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlSStFN3dvQTgveVFCWWZP
            cWZKU25naCtjdnRPKy9hQi9GTCtOZG8vSVU0CmlFK282djh0RU0xS01FZnlZUUpE
            Qnp4UmpLckFJMnM2OE11Y1FWcWdQdEUKLS0tIFhZTFJQcDRHNlU5bEwxd0IvTThJ
            UVhoNGorSDExSm1YMCtiV0FJZzdKeEUKdtn55CAkNGiAyuS7FluY6aNR/PVhUrJA
            kEKw9fSzaGnT6N/xDisJCRwopKsXrxsZJvs5MhN2HF4J+wB6zod/Cg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1586thf5vkcdf5lcn3zwjpu8ltkwyq8efrhj8lr0vdrrt9k5f3qgsxeg7gx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-10T16:58:23Z"
    mac: ENC[AES256_GCM,data:J2L2dR8KCGI1ePJthlyTCfecqlFRtjuIjaV7Bs0ccJwaoNEaWHqJtGUjvTnrxpL1m8DbajESI8QdGLmhRINBeMHdnrplV7jpazt4FE4RLs1hteyQft+/rU4Ehj9gXuFc1iFb2YG8geqqQKMne0yWOJE+8FbrHWIf6DAYBadbr98=,iv:JyfkwQRKOd5/K5Mk7mjXYFFmJVRzKMOCa27O9/2vYDU=,tag:n9Jt/+Xsag1/RD2CUkcFLQ==,type:str]
    version: 3.13.3
