apiVersion: v1
kind: Secret
metadata:
    name: cliproxy-client-key
    namespace: odysseus
    labels:
        app.kubernetes.io/name: cliproxy
        app.kubernetes.io/component: client-key
type: Opaque
stringData:
    ANTHROPIC_AUTH_TOKEN: ENC[AES256_GCM,data:PeZNJS24+kS6IwXxMQg1zfYDFMpH/qivbZW1U/xJj+WtJFYo5dOzbg4zkEYNSA==,iv:WC/q5/Hwz1k36sY2OpM5+zOppoGAckPLrICXayJxzus=,tag:ByVNQ0uv8EGFUAS2eP32YQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlSStFN3dvQTgveVFCWWZP
            cWZKU25naCtjdnRPKy9hQi9GTCtOZG8vSVU0CmlFK282djh0RU0xS01FZnlZUUpE
            Qnp4UmpLckFJMnM2OE11Y1FWcWdQdEUKLS0tIFhZTFJQcDRHNlU5bEwxd0IvTThJ
            UVhoNGorSDExSm1YMCtiV0FJZzdKeEUKdtn55CAkNGiAyuS7FluY6aNR/PVhUrJA
            kEKw9fSzaGnT6N/xDisJCRwopKsXrxsZJvs5MhN2HF4J+wB6zod/Cg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1586thf5vkcdf5lcn3zwjpu8ltkwyq8efrhj8lr0vdrrt9k5f3qgsxeg7gx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-03T09:57:38Z"
    mac: ENC[AES256_GCM,data:MVz04HsqT57rG68AgBpTNveRqX4Z2jk7cPGIJDXlrkPOR+/Kftzuc9hnHL6dw1qOQacAv4fMbytHcPPoiW8JqtLu8tV8v/8PiH5kLM9vp193mArCwD2EvFt9v3RFC2k/gEyd/vizXwXbryx4gd/z4QJixWaJkr79xSaYso9/h2s=,iv:3P8EKa4rPaJf3b+3cRGdy8YMNj6ltnGAmwe/8CTZqjo=,tag:nXgTvj3YCD39RD6pjg4+fA==,type:str]
    version: 3.13.3
