apiVersion: v1
kind: Secret
metadata:
    name: odysseus-secrets
    namespace: odysseus
type: Opaque
stringData:
    ODYSSEUS_ADMIN_PASSWORD: ENC[AES256_GCM,data:qOVP1L6/5950BGrQuXyiEeBMr11JBg==,iv:kyBzsjVMScwUK1Z6unwvL18TgbrdERQ9Q2DON7sd9nU=,tag:NpkpBh90mELQjXsO89RTDw==,type:str]
    SEARXNG_SECRET: ENC[AES256_GCM,data:sjceL3dvBYspBWF25svpC3m6UyodNDwq9TgBxwClnxiSwaAigiPkQt/vTqlOCCZuvmlE4/Dm7GuCTHXiOJWABg==,iv:5vKl1Io6FtjSHEpDD3Z+Xm0850i/f0Iy9en/SNjQCNo=,tag:z8JZ7O0KmxiMSF2NgtTOOA==,type:str]
    OPENAI_API_KEY: ""
    HF_TOKEN: ""
    ODYSSEUS_BASTION_SSH_KEY: ENC[AES256_GCM,data:iemcuPG9WG6C3aAUbL0BXbQkN+9Wj3AMr2PmV4UZXNmt+jT4jTkwKGqEbIdSLnEy2QKVtRl8+lwUXw8cDQqx0WD5XFOtTVGmAxRmm9GK2yS0EEtS9EFM3wzxzr56fup2aTr8FeMSUFjLm/KDOq4QhWq8Kr6xh8i5JgoGb58fnjIpGUSYwuqfVjlglxrpfe5/B27m5swx2ORcTLow1m68GWiVPm5+LwMUNamUjV7o0n5opTKm00nBD3XzMePifAqn94vJ6W2Nw9w76k3+GDWNoZBo5TJYlIqHiwqOYJscDd8BA7O1nAgnq/94bJEfKqIBbd3pAP4Ymd+fdGjwMD663s1sdutxlAowJdE6PaGPGsfnJtkkuBPT76FZdDZjnBvtmE9HRFloYjMnqYJCPJ/J68Xl1AgV0xylZhnKYbH3QNSKeIXeMd7VAKyODkolNVP0yO65UthGpivYjurzz24bRgT+l3+fU0ZTtkqYF7RtLGYppja5G/nmSKC2qg3mLBOVY2RUcx9EGyXYkTecfEf9ksoqvdbKkO7QR6yH,iv:aRPA+MHjnVn8gYMPkIVP+DBs7A6mbE5R24xu2Lb5fwg=,tag:IEEVF0I57fewOmw4cMOaCA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXeFhhRXhua0VXTmQzYldV
            RkNkaVVZVXJvb0RSL3FXeGZjS2Nqdk42MlNRCmZQTURMSnVSdGh6YnVBMGpnTEJo
            QWhYemNPWHlKakhacFVBTkpiVGZBT3MKLS0tIHhJV3paVmdTOXR4SlhObUs5UUtx
            YmRPNlRFY2l5VWtKTFZTeHg2RExyMzgKO+FUj2Yz48YbTxNcyXirGgYQR21K8zHE
            LjauIUQ8YwnG07bfUYe6RoGbrWpJgbahSgxqG+0mwZKDOJ1WQ11KbQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1586thf5vkcdf5lcn3zwjpu8ltkwyq8efrhj8lr0vdrrt9k5f3qgsxeg7gx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-14T07:23:48Z"
    mac: ENC[AES256_GCM,data:xbR+SjYJdk4fWrrsoXtZLW86IPNzbgTiglJ7yUef6Lb3RDErl6uwD5re5VMqg/L/prA5DGK132Ul7qIV8uSEwnJmaei26M2vv94nXAH4zP3vew7DZQYao4fHncwrXLnjoGUXQS1doJnsRlA1L4nPbuUOuAm3UNS2LL1kz+o8TJI=,iv:Z5nqRWmJNsfbc6KEv1YGApfC2N34q03n9l6ctAvtSNQ=,tag:8JBXFv4/FwCAm30ESrv6rA==,type:str]
    version: 3.13.1
