---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: odysseus-bastion-workspace
spec:
  capacity:
    storage: 60Gi
  accessModes: ["ReadWriteMany"]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  claimRef:
    namespace: odysseus
    name: odysseus-bastion-workspace
  mountOptions:
    - vers=4
    - _netdev
  nfs:
    server: 192.168.10.200
    path: /mnt/apps/odysseus-bastion
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odysseus-bastion-workspace
  namespace: odysseus
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: ""
  volumeName: odysseus-bastion-workspace
  resources:
    requests:
      storage: 60Gi
