---
apiVersion: v1
kind: ConfigMap
metadata:
  name: odysseus-ssh-config
  namespace: odysseus
data:
  config: |
    Host bastion
        HostName 192.168.10.43
        User ubuntu
        IdentityFile /app/.ssh/id_bastion
        IdentitiesOnly yes
        UserKnownHostsFile /app/.ssh/known_hosts
        StrictHostKeyChecking accept-new
        ConnectTimeout 10
        ConnectionAttempts 3
        ServerAliveInterval 15
        ServerAliveCountMax 3
  known_hosts: |
    192.168.10.43 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKUi2iW6pMaqS1T25aacWlicRiIkmaQYvQddblBgNlR6
