apiVersion: v1
kind: Secret
metadata:
    name: odysseus-data-seed
    namespace: odysseus
type: Opaque
stringData:
    .seed-managed-by: ENC[AES256_GCM,data:H+D0Ez/2+DZEk1WK8IrFT+Hfb29XxIZRxik6UzmE5FxmrxYsuXBtTPFJDXpF+am0jiVPj4DXrAM=,iv:S9s1dJVFeS0YIe7cqCGfG3JQzEnn8GWU1uOTMpjEcEI=,tag:dO8NWa2figV50veOyL6/4A==,type:str]
    memory.json: ENC[AES256_GCM,data:5qoGZ7lf+5qkZQCshjvJ28cPduKzj6dXvrrmHhfqCRHyvYrbMHr+SRNOQ9RJy5bHEdt7AAY7rc/1FRSjF+QzPed66DI4PtC3danrSKuKiNw6nPhsGYrXESQY5IVN97wMVKWlh4X2+Qa7bePHXlNGmwLAGwtj77cgVWmpw5fS7uEDfq7o0Xp1hM0nn1Gw6OO9FRep4wTUNnz0gc6zOOdusycgDa8JSs7RaTcPeE5ccZ4ezAJJwBUa+qX0LcnS/boD9Ncb4G71GvVcwn78V5C0rsSMNhq7Zgn97nTNtoRbcxD08gfRRWjscueIRGbkUh1zs4bRKfLgqaIiIeENZzvxn89B07CesOtKL6edwDY9ortDJkX5pjdeLODF4KvYRJ0Z+7C4qfdDGezKdr+zUetqgikdGY9Uagw7kOU7NXr/7RUeRvMD+sp93wjwEQxen2t+BYgeBwVD1cAt7oKvE+I8L+WSITBJbd7hbgrd7iWWn8PJTHfL+RKHrlMgHI3K+M3VFoOmr8mQiLZpL7Sfmcc8DyuwUT+sg4hVltZbAJtYlA2LvRAMqNNNI/t/X3yWIOBWyIj5Mpnz+k0qbv2udaxO8sUi3IHg6fjHReWlZshvU75ummlQ4EC5J0vJ6qaNy5bRewVFeAHLB7JKl64M73uMUWQH5CKz5Bm7uVh1mGi3Po2Zm/W6QMve8C0drMPywiTiPklo7ac+odt9pIH1O80AP+MtSygcxPTqZSJ5wELFkCkhb31o9YCCnK7vEgyamTy+2OXKVZpRfHj3zJoTTkQ0z2Fsx3mBRVv6/qyZiRe0dEVPmtFg3++seCdf3aU+rJYsOvtfyxclFld9ed9vG1lmNWBsFnCjaSov+mOkv5LUE62l+B5ERdjpNK6qCS9XfFVT2Dg9zguqOZI5/gqdOtoAeRbQNd+RQC13cJXkd5c9hveZNlpLmRnL4mu+h+js0JY5A2qmKKR/JJV+w9LE8rw4IGPihv/3lzrI5bGQcSxsTdlfhzDS+isCzbMGy9D03/znoGZae1WPDpFPU2ZFOo/IdELiF7vFdupGTCAGuxMcFxDVR/ZC5NDtGlgJs7e0gaGYhd0oOo//hFUFcFldJZV4nd7Pi1uJ0vZjo62a6mfura8GNT8GNt7AP2GGCdkAmv3DsMmf1MN9nbtavrGbTUq1Q0Tzbvtz9hKEeYtNKMuBTeQv00q0k4Bs4dYE9fCI14R6FkdH2Ks59A8WZHLFdg==,iv:ImFoYo1BEXA9EsPHF5XinlB3OPRaX5WR9TqlBsENYxM=,tag:0kLepB3BPJAGjkoi1nj/Og==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2RlVFVzVuTXpuWTlUSFRN
            alhpZlRhc0RxTnp1MVQxUHFLK2oyZjE3Z0VVCmNDZjJSWmlUTDA5d0J5MkV2aEky
            SmVyUDFGbHhaMjVobWV1TVN6dUZ1U00KLS0tIGJudG9QVVpwV213cEFOT2Q2ekRS
            U0xFQzBjMllUU1FZK05wZUFKNk1pV0kKJabzoHeutHHMasyQwcGNSusQXHpXqSJV
            0eShlPldhP/U0moUNn4+BGryDb8zPaS01aQLUwPBMm+YAsE9ZOPCbg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1586thf5vkcdf5lcn3zwjpu8ltkwyq8efrhj8lr0vdrrt9k5f3qgsxeg7gx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-14T07:43:40Z"
    mac: ENC[AES256_GCM,data:ylAwxDCrm8HFEA+ukLku7Ml5rkoHc+mfg5s9RC2aJMkIqCYWGrkk9r8hmpm5vFRWiDqgn3AvHbq4Hs7TYF93SIhH7nKHbE6pQtB477DDDFdHik/zbQj+8jP4j5blFPBphnsKR20s9m4qHmEIA5z8PVAlowEl+amO7sVA7e3amfw=,iv:XHlMyN5riqPwzZY/dyo4B/90cPt3PxgIDKGUuAtJVZo=,tag:QLzPM3Jf7kVn+hVWJBod9g==,type:str]
    version: 3.13.1
