apiVersion: v1
kind: Secret
metadata:
    name: odysseus-secrets
    namespace: odysseus
type: Opaque
stringData:
    ODYSSEUS_ADMIN_PASSWORD: ENC[AES256_GCM,data:Lrv1Tb/CBLM76WuAxHtncaNO3JU+7A==,iv:CR1FX8Kj4YQv/Me21rdthVwe65pEYn/5ikHELDrXn40=,tag:Z60sP/wtZsvjazxrZ4VRBg==,type:str]
    SEARXNG_SECRET: ENC[AES256_GCM,data:heU0WDKci0VoiQgjp3wLAZaafyoPMllNakMBp8uLZRo4VBoDD14wgwBfHdSncO13FPw5+2asBHwV3BdxjvO58w==,iv:R7yKRifMcXajP6e7MS6B3z/lGEW8zPDSC9hwTw0YkgA=,tag:dZRy/N7On5hhAd9yYMi/7A==,type:str]
    OPENAI_API_KEY: ""
    HF_TOKEN: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4dWlTSUs2aUtHVk1BK05N
            N1hrZTJDWFNSdHY2YXJDLzRnZHNSYU13KzFNCmNqOSt3bTBhcXJqbkJtcE9oUjEy
            NzkzaXIrdVRrWGNxUm82K2pyclExTW8KLS0tIHFXZUFxT0Z1NEJXOTZ0aWNjS2U3
            Rm5qdzhyUWE5ZStnSkJvQTVlTUkxeDgKbQrpWOnUQ2c4O6gJrUeTsGZdy9A3Uj1V
            8BQ0FeMeB4dQP5uQ847JInzrEJjVlUXELxp+g+sImVZ/qBY8zUe/0g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1586thf5vkcdf5lcn3zwjpu8ltkwyq8efrhj8lr0vdrrt9k5f3qgsxeg7gx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-07T19:35:32Z"
    mac: ENC[AES256_GCM,data:vMEp+K4T1tlQFs9gnSPQjx8VoIEPYoX6RKBqFrFm4WMOre1AUkNj0YmiUxVq3CBXOiFXQ71gFNTNQcszgpTQLroUi09EfySv3SnvYlMe0gTeE8ih8/ReEW7fa+Trm3a/GEDZvsDC2mYFkcfJQ8z1f/+XrHpboNot53UvTWj5dVI=,iv:4DyEkvwiRaE7G39szuwuNx+Z15FkDO3tZAuMx8pSTOo=,tag:ZFefln41JC8jIXWx8isl/Q==,type:str]
    version: 3.13.1
