---

apiVersion: v1
kind: Endpoints
metadata:
  name: pegaprox-ui
  namespace: traefik-system
subsets:
  - addresses:
      - ip: 192.168.10.21
    ports:
      - name: https
        port: 5000
        protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: pegaprox-ui
  namespace: traefik-system
  labels:
    app: pegaprox-ui
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: https
      port: 5000
      protocol: TCP

---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: pegaprox-insecure
  namespace: traefik-system
spec:
  insecureSkipVerify: true
  serverName: pegaprox.epaflix.com

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pegaprox-http
  namespace: traefik-system
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`pegaprox.epaflix.com`)
      kind: Rule
      middlewares:
        - name: redirect-https
          namespace: traefik-system
      services:
        - name: pegaprox-ui
          port: 5000

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pegaprox-https
  namespace: traefik-system
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`pegaprox.epaflix.com`)
      kind: Rule
      priority: 10
      middlewares:
        - name: security-headers
          namespace: traefik-system
        - name: authentik-forwardauth
          namespace: traefik-system
      services:
        - name: pegaprox-ui
          port: 5000
          scheme: https
          serversTransport: pegaprox-insecure
  tls:
    certResolver: cloudflare
    domains:
      - main: epaflix.com
        sans:
          - "*.epaflix.com"

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pegaprox-outpost-https
  namespace: traefik-system
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`pegaprox.epaflix.com`) && PathPrefix(`/outpost.goauthentik.io/`)
      kind: Rule
      priority: 15
      services:
        - name: authentik-server
          namespace: app-authentik
          port: 80
  tls:
    certResolver: cloudflare
    domains:
      - main: epaflix.com
        sans:
          - "*.epaflix.com"
