---

apiVersion: v1
kind: Endpoints
metadata:
  name: truenas-ui
  namespace: traefik-system
subsets:
  - addresses:
      - ip: 192.168.10.200
    ports:
      - name: https
        port: 8443
        protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: truenas-ui
  namespace: traefik-system
  labels:
    app: truenas-ui
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: https
      port: 8443
      protocol: TCP

---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: truenas-insecure
  namespace: traefik-system
spec:
  insecureSkipVerify: true
  serverName: truenas.epaflix.com

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: truenas-http
  namespace: traefik-system
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`truenas.epaflix.com`)
      kind: Rule
      middlewares:
        - name: redirect-https
          namespace: traefik-system
      services:
        - name: truenas-ui
          port: 8443

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: truenas-https
  namespace: traefik-system
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`truenas.epaflix.com`)
      kind: Rule
      priority: 10
      middlewares:
        - name: security-headers
          namespace: traefik-system
        - name: authentik-forwardauth
          namespace: traefik-system
      services:
        - name: truenas-ui
          port: 8443
          scheme: https
          serversTransport: truenas-insecure
  tls:
    certResolver: cloudflare
    domains:
      - main: epaflix.com
        sans:
          - "*.epaflix.com"

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: truenas-outpost-https
  namespace: traefik-system
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`truenas.epaflix.com`) && PathPrefix(`/outpost.goauthentik.io/`)
      kind: Rule
      priority: 15
      services:
        - name: authentik-server
          namespace: app-authentik
          port: 80
  tls:
    certResolver: cloudflare
    domains:
      - main: epaflix.com
        sans:
          - "*.epaflix.com"
