services:
  nvidia-gpu-exporter:
    image: docker.io/utkuozdemir/nvidia_gpu_exporter:1.14.0-nvml
    restart: unless-stopped
    network_mode: host
    command:
      - --web.listen-address=:9835
    environment:
      NVIDIA_VISIBLE_DEVICES: "all"
      NVIDIA_DRIVER_CAPABILITIES: "utility"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
