apiVersion: v1
kind: Secret
metadata:
    name: searxng-secret
    namespace: searxng
type: Opaque
stringData:
    secret_key: ENC[AES256_GCM,data:wJmPTHSywKBIJ0rYvS9faQS2rmFS1Ylfkq5AG7jOivUCLN5FaL8H+KZCVlV/KWRX5mumAfQMdSN4SxRNFB/L5g==,iv:RhTuZ3TJnSyVZ2twiI48tnWeLMAdyYp3fZmkQPTRvU0=,tag:WozlZZ1XkAEU2/eMz8TYvg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAra0dseTRwbEkxMFlyZU5k
            T3FzOVJrcFVDQ3dJSUk1OXlXOWtOQ2dneXhNCkxlWWVyTnNxM3BISlRrbll1aHJF
            TWthakMzalRvQ3VPY3VyNDZlQWovOGMKLS0tIHRZNWIwdUFOWkt4eVY1ck9UamhY
            T2FkU3B0djRKN0gxaTdPbnFOc1FUMEUKqKN+WEJfg+XJSFJew7JNekMRKfqvs4/y
            uBi5Hd2v3wh+f9sWjgdUJhSEbizyMny/RXdJBSxyL7JZzzfUl2hINA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1586thf5vkcdf5lcn3zwjpu8ltkwyq8efrhj8lr0vdrrt9k5f3qgsxeg7gx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-23T08:31:21Z"
    mac: ENC[AES256_GCM,data:PW4zrQS3hxqdaQ76mvOtS7jOyZSJWwJWL8fBgUW8OITd4KREdd0q42v1pMW7rS0zFKI4NqACRy4K9D02x/d/qiZG5A/QYXLUI2Qb+kutvYz6ZQPz57oMQeoMEKFBD2lyuu7Gbu7TeLl2V9d7YQwqKX+G6zeDSJ40T8H7FWAlkeQ=,iv:n3qSIOQjJXlGRfChs8fw/eJNd+XzhmCJ8GUfu2lcyFc=,tag:o1gc2r4qdJQVoijvQv39Gg==,type:str]
    version: 3.13.1
