---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vpn-picker
  namespace: servarr
  labels:
    app: vpn-picker
spec:
  namespaceSelector:
    matchNames:
      - servarr
  selector:
    matchLabels:
      app: vpn-picker
  endpoints:
    - port: http
      path: /metrics
      interval: 60s
