---

apiVersion: v1
kind: Service
metadata:
  name: iperf3-server
spec:
  selector:
    app: iperf3-server
  ports:
    - name: iperf3
      port: 5201
      targetPort: 5201
      protocol: TCP
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iperf3-server
  labels:
    app: iperf3-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iperf3-server
  template:
    metadata:
      labels:
        app: iperf3-server
    spec:
      nodeSelector:
        kubernetes.io/hostname: k3s-worker-61
      containers:
        - name: iperf3
          image: networkstatic/iperf3
          command: ["iperf3"]
          args: ["-s"]
          ports:
            - containerPort: 5201
              name: iperf3
          resources:
            requests:
              cpu: 500m
              memory: 128Mi
            limits:
              cpu: 2000m
              memory: 256Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iperf3-client
  labels:
    app: iperf3-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iperf3-client
  template:
    metadata:
      labels:
        app: iperf3-client
    spec:
      nodeSelector:
        kubernetes.io/hostname: k3s-worker-62
      containers:
        - name: iperf3
          image: networkstatic/iperf3
          command: ["sleep"]
          args: ["infinity"]
          resources:
            requests:
              cpu: 500m
              memory: 128Mi
            limits:
              cpu: 2000m
              memory: 256Mi

---
