apiVersion: v1
kind: Secret
metadata:
    name: argocd-image-updater-secret
    namespace: argocd
    labels: {}
type: Opaque
stringData:
    argocd.token: ENC[AES256_GCM,data:AE8kygowBuTAlmDELx+JVWBE+6ZPfz5kKVijFi5N74cNoV1EyviTC8Rx/New9Hw+62wfvERxeWVbtAcp6D9iYNEYHmaeXrzw/n+Xj69BkPD8mp6J+80uou0+1HbTTAfU94h9wOVJ7zNS2u0MTAt5JgBRmezB0iOvSCIGWFb8UM7f6Glv8Tf404Gxw7NvmY+aru8ntoRGfKjl9eURS4dEAamMoOaQD+P2Fr3Mm2HalKiX0Dz9GIjj4CqVOiiVuh5nFDvgfpNDaPW6QkPOwennny+0D7M3YOMEf4eLwPHcyYikY/3Czrueaa/NVi8ECGubd18d9IfILQ==,iv:5uUQ/O9Iv3MVoXUb3hQtu2YjWEeP8aVVEhI1BZ9Acz8=,tag:s6sqkafOr4UXJLwSO6yExQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzcDdNMThhaXcxdkY3U0R2
            b09QRWZmVGVZVUNUaTFMazM2UDg0bk5MUHlRCktSWHdtNEFJTDVrcVlTeDREYVNV
            V094NTVSZ1ZkeVJnbDNucyszMm9yTEkKLS0tIDBCY20wUWNqeEhaS3grRGtBTk93
            cGZCT29VV2lEMmhJNi9nbUt6anIrWmMK0g+5zZCqVfFkwOaRE/DfT+iW6S+y4FmS
            3YPHYVz9APLEqi9a1UwMax6rqOuHZFmdnWpWGERSLoCKe+7l8vOjyw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1586thf5vkcdf5lcn3zwjpu8ltkwyq8efrhj8lr0vdrrt9k5f3qgsxeg7gx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-25T21:14:04Z"
    mac: ENC[AES256_GCM,data:IOgEhUeL+3m12XeZLhWpgaQR1acc0eMn77vbU6RBtHm5ctndr0fJTchKpfYEwRjxLAtOem2rqFqyTuOGploLBs5g2JFl47w+4EX0IxorZ1d/HBEDmRXFiUSTg3VmQQgnsnxC36ThsOr2IQNRAUDPQjgI5ym0nSaLXlHD/KUprvc=,iv:CYVMwxsYbdXDAN37AtFe1RrKC5zTzaq65UM10hLmdgE=,tag:LPr+0OOTCRh+VWkbsQCODA==,type:str]
    version: 3.13.1
