apiVersion: v1
kind: Secret
metadata:
    name: git-creds
    namespace: argocd
    labels: {}
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:KgGI5Lv3vki/pBRTIhlhV2+eLnNIyaPNBYzV942nTB/82P5XeO0gMQ==,iv:tllvL12ZmLoB2t1aDyti+Zx8ri1P9ZhfvsFIjSYUK7A=,tag:yMXKX606Sp0oDrn2pgVL4g==,type:str]
    username: ENC[AES256_GCM,data:JGkk,iv:R1knKhStHpR17RJgFMk/5yjHSyYURLJAy2LPCB3wK6E=,tag:p2aljg7kKGKXDxKASQdIJQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3RHU0ZG43dERZRXVnSVVn
            bEx2R3N5aGpxejVuMWorYWd1eDhZNlRZVGdvCktZenJWVWZUSk93K2U3TlBzQUE5
            b3VFOHJRR21NTG95WHoyQnJVRTdGQ1kKLS0tIERLY3JpamJHSEh3eFY0MW9HSDdQ
            VzNGTys1Z3hTV2R3UVVIdU9teUxMYk0KarPsSQNlrwR/qDkJxMGK4+ZRUINSxv36
            BhHke4ybc7YPrDaJXnRQoR/8tx8YW5pCUNSkFd1u24iKN8L0036GKA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1586thf5vkcdf5lcn3zwjpu8ltkwyq8efrhj8lr0vdrrt9k5f3qgsxeg7gx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-25T21:14:03Z"
    mac: ENC[AES256_GCM,data:t6oyMlp1rULS+5+adkCSrtVk3szuqMwK0gkHSiSiBsjIsXcaWbVrN37DNWQdS/bDchltYTRgLTlOU8gZFMneLfOo6BYh+TruxHtYHh9RcnOSTAzmMtu/UUsvs64SeFbpXwpUKt9Ut/2zKMtiwN2Xt+jAlvQ1tW2JaXPrhUEBiKw=,iv:bKjR7fYawPK7IUUeOzob+i/pEuJgL9h7sLHbrD58J78=,tag:Vx9WQQgvkvaP8EdY639SlQ==,type:str]
    version: 3.13.1
