apiVersion: v1
kind: Secret
metadata:
    name: github-epaflix-repo
    namespace: argocd
    labels:
        argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:fmoL30hCQi9e8do5MHFNjXzmPaZTc9LcmUnvVJLQk/2wnCwrfx8VeQ==,iv:NE99Rv+YD9/HRchBbuQQ/IyweK2ZFkhWb0+8TawX1RA=,tag:bsy//fPkBCS0y9ujcitbHg==,type:str]
    type: ENC[AES256_GCM,data:606V,iv:s5+8NhFTHbhjYrJbFYwpOIBhjUjiEAZBiB/OBlAkBLM=,tag:jHtXyNbrPYGnuw7KwIHvrA==,type:str]
    url: ENC[AES256_GCM,data:ygOe4FB7UlxbIGoDIoB4moT8wJLQLUjBtr+UcWKKTDxNXh0mOCWY7R15vLA=,iv:OYVem1L0dE2u4GCeNvj76NDqrOJcjDS1EQyy5cvYhR0=,tag:cfQ8YNZ5EAJkMa4wCuY95Q==,type:str]
    username: ENC[AES256_GCM,data:RFrk,iv:EcVS3aZMx6llgnslbAOg4/Ieq4BaeybhartMsqRn7SM=,tag:TYPz8cuC90XyulRV3GjmQw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTcWI0VXk1amhDNXhpUHZR
            L0tXMTluS09BRzlvdVZYL0g0Z1lBcVVzR1RjCkpocU5sc0x1U2pGdENSU3o2dVdq
            OTRZTi9uUnVpbC9vazdWSGlRazcyeFkKLS0tIDhIc1VBR1JkUlc4dGY2YWNUMjNh
            TW5VckxmcGhlajJCWCtYVkRqcjNvMDQKP+vT1gq1FPtt6tTbmgA7nL/DfbmB1CA/
            Hz51ZfZ9pO/Xrrmy2S/onjN3xvQZgBM9s3p5//4a+0nUORt16/sp2w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1586thf5vkcdf5lcn3zwjpu8ltkwyq8efrhj8lr0vdrrt9k5f3qgsxeg7gx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-25T21:14:03Z"
    mac: ENC[AES256_GCM,data:iqEog+nIxyY5Y2x7gKDrDuOJaMmt7Fewc4joOgfAT49pVdKmaT4ki4jlw6F2hi4EFDR1mEzR9NU6bNFDEGiRjFNeIrVLBe3v8UarBKwpMnR8azEqSpRFymmBA/7Qi8LDLnntt5fxUSc0M9zEWVazjHzspvs+sOX22hSX5kJSf18=,iv:FRfJooR5QJc4XZOgVOffhNbC2dAqBdyT64oyJny7H7Y=,tag:X+r6qkYHhCexp/9ucfee5A==,type:str]
    version: 3.13.1
