---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-superuser
  namespace: postgres-system
type: kubernetes.io/basic-auth
stringData:
  username: postgres
  password: "<POSTGRES_PASSWORD>"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-app-user
  namespace: postgres-system
type: kubernetes.io/basic-auth
stringData:
  username: authentik
  password: "<AUTHENTIK_DB_PASSWORD>"
