server:

    local-zone: "bastion.epaflix.com." static
    local-zone: "takaros.epaflix.com." static
    local-zone: "evanthoulaki.epaflix.com." static
    local-zone: "syncthing.epaflix.com." static

    local-zone: "searxng.epaflix.com." static
    local-zone: "qbittorrent.epaflix.com." static
    local-zone: "prowlarr.epaflix.com." static
    local-zone: "bazarr.epaflix.com." static
    local-zone: "lingarr.epaflix.com." static
    local-zone: "newtarr.epaflix.com." static
    local-zone: "cleanuparr.epaflix.com." static

    local-zone: "remote-pi.epaflix.com." static

    local-zone: "ntfy.epaflix.com." static
