apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-config-secret
    namespace: observability
type: Opaque
stringData:
    alertmanager.yaml: ENC[AES256_GCM,data:qSB3z1AOebRIacgwMJJyj6y/hAHbQVdOphaGP/FBNSFsTuqGd1lt38aGf6647JezVsdMRSUCO+3iwvByiiBfMAzBspyxncuy1JLE/B6044hR8olfDHA2Tm5HOeOcCTMiaY6DlgtVEkkKsF9E0ySnctoXaA5aNrsPeDnVdMVk2R1O8O4UjfkiICbqMmSqVQ8gUmNyc8Lh5ddvt2LPb/T0CwfscMNmG/qoSVieo3zxIgjJooVOJIsA4PcxJMF1SZOT1fBly8/81suTVHVPrS6NQHg6f4nPYHgSnUznFQuOVZ6vnI3PRBcaUeFYX0D+SyKJ9h1bqz1z901kcpYj5fZ/NjhIPiM7+g5MH4QVUBCniZDawZNQNVAw7xpCFuIz8i80Aa4Ex0ms/NeSyHBHSNwoai67BxssSDgtHqRypz3xe9KHblwdxfGKanM4WldCjc3nMJ1Cb1YLnMWNBVnsG9MmTmQPQo6A/yz9SPqmEnttuX6yk0i8kuIiZKae/yjWB6o/1Lh0ogsZQmxhWzfmCayIqn6uOux6TYCiFVec8o/OruCjV0c3WLSUAtQevvPz3I1FPlXRAs05dzx4wwsDqhOGBsfBsrOTyzjmk1y0AjUT0ZmArSm8aNEeLchnBjDb4aFxTUwBHD1MrJroLaKCdWylq7MSCf1YCygiUGFcbMWrKe/tgq70LjE0jjX6cWbu5x3/bJwv+bfHP8MkBsd0MHr0XUX+2dIu3h8AWXo/LyqbBP2P6GLalwrt4ihbWcvE/gNn7JsIgTRRKqUcUAh8jydJIfHAH4VoYwr7LaNgLCtPYDLXrC07UvSKG7P+oUlpJTRr/QI6D1SUlPj4MKAKPO3zjxmaQeuAUyT6KVqdiocskorvWYW27TKMmbXEvVot4n53Pu1icXPgVerNC6Z4oSIfnLS/wNpQfc1PUr03uVjqg0lOvUYKN/1kZGBsCTu7GxHla9qFOUni96unNfZnUUXneQWzO8Xj0SXYD1kNShB8v1f8kvCMpYa9nWH78vlO7fpKmN/sQis9fYn1CmWphciChcHk6PTI3u+KijkxS3ufl1CoKFGbiQMIK7bDC93jXk0jeBrVKKMkHjIM/Mk5RJqj3RvnrGkA8+SW7xjhnx9uwWEV5Nchgb27qMrOLw9NgcWPbqcmTrRF17hsRkw=,iv:iYLfUyCBeFEVJ5j7V0GVmppE9ZZclQrQR75/ZIjBMzQ=,tag:LW3wK+dn9WUry1xPnF3xyg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBySG5xaTRDNWtOdGQ0MWN1
            TXc4MGo2L1dka1hYN3BDTENJaDNOeXRxV2hBCld5WEoxeGZ6YlNIamlKYlJFNkYw
            ZGRqVUZJcndsN0tldFNJclRZU2RPTkkKLS0tIFJjR1hhTWtLKzhXZW5QTXFZVUww
            ZEdjbloxRjZXdU8reHZzOUpZRjc3azQKS9nyBJzIkP45XY8U3zup2duTCRRtjTHB
            K0b/YLu5yheBwYkgbKdadOmBDXHE3ZgyEI4Z7B4+K0ydz7euY8J9Sw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1586thf5vkcdf5lcn3zwjpu8ltkwyq8efrhj8lr0vdrrt9k5f3qgsxeg7gx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-22T14:06:22Z"
    mac: ENC[AES256_GCM,data:D7U9OMr7SS1rypj97zAHB2RwNBZbJ/LQaqt0YT2InLtryBMCkBCBK5trbsd9lPeesdQquFY0sqRtqZy8xfNMqLmYM5lLuwC8E0Fcsa6fZ1aiIHwJBj8MsVhH9yw4y4gxSUfxwLGYiSH3HwR3xxhMu3jsBLjex44ZlJGNU2BEMaQ=,iv:zNQ4V7bi55xw+DTy0YkdvO/BkcBghTG9VQcJ+TaEMVE=,tag:1zmdvrhbMNh/VRFiE3EgTw==,type:str]
    version: 3.13.3
