apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: observability
type: Opaque
stringData:
    admin-password: ENC[AES256_GCM,data:edmnFfRwx15xJtRG,iv:xg1GXQbznb3Owehx7Mk/NPq8aGxHD/sPJOivqP690EQ=,tag:Uke//xGCrUCWnZsV6Or9Sw==,type:str]
    admin-user: ENC[AES256_GCM,data:Dr6nT7U=,iv:Feydj24fzuXmNdh+0szjgU//9+JgQ5BZMguXkmqqq0g=,tag:9ZHxseYoObh4CZHdZJqasg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsSnFWSXc2MXRTZ0tuNTh4
            aG9FRzJkRFdreXZaQ1V6bjlCMGh1WUNkQmpnCjh3RnpLWDhBR20wcGYvL3VWaVdF
            Vms4N1Qram1HRFFscnhaSGNNc2l3VEUKLS0tIE15ZmNPMjRRTk9HT2xzWVJrR25N
            ZjNlVUszMVJ2UGxNdUJZWEd4dDdxUTgKWvyv3ZEISzyicrFmlXxfteeJMVyBamJ/
            x1IPgkTcPYk8mSJvnwUtswni1+qObohexjs7vlzaG+A7OJUp3w9caQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1586thf5vkcdf5lcn3zwjpu8ltkwyq8efrhj8lr0vdrrt9k5f3qgsxeg7gx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-25T21:03:05Z"
    mac: ENC[AES256_GCM,data:mfOcBmi0MHO2KvUL40GOp6aikCMTBgu6IhJb7gEohhDZwGw5mAvZH+9xfACNl2rJaBL84CK/0Eg+Kz0tvFXrNd9UwaAUYEw/XfjAo2m24wh5qxEbeS7MFz7bnXQThD7eM75tcFg9oWzIsQTjgueQ97GrxbXv8hB5qsvsoFdzRXE=,iv:y5RiDz8Qof0L5pjiP5tBn5DUz+LYbxuBm/3+neZY04g=,tag:PkgZsKGDM8xW/0YlrQIR1Q==,type:str]
    version: 3.13.1
