apiVersion: v1
kind: Secret
metadata:
    name: grafana-db-secret
    namespace: observability
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:eCqdSD5OzclSbTzG,iv:mK1dj0TR5wfRPA6s6vIfJTA0AaTGNcjas72y6wRDjQg=,tag:f3WjYUKXKTnEsdJiK2JhSA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBObVFLMnpaUUQ4UDIwUzlz
            NUFoN1YvMVdWR2pKb2NHc3ROUFdNd0lGamxjCkdQcVJPellsa2YxVXRSWDVvbWlS
            aXJ6bFpHaDY2Wi9mcWs3UzhrTThmN3cKLS0tIGFXa1g2djFpMElsbTAyNE1aYjdZ
            d2NTQ0VSbGZ1b0dEaFVCSlJLM0JSYlkK2x/K1N6ikzafRfdfqSTMUbSzcWPHTFVV
            0op4o8VmDuNfnmIAoFDbR25VdTz/alqg5Ot30bibAwg+utU0XaM9lw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1586thf5vkcdf5lcn3zwjpu8ltkwyq8efrhj8lr0vdrrt9k5f3qgsxeg7gx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-25T21:03:05Z"
    mac: ENC[AES256_GCM,data:Tvw6ut6sb40VmEQBVDkSPSoeiOiF8nEJtT+XOQc2BUx/P+GShhCE4Uxy0ZXDat9caJhBJR5I055YDVOeMT1EpmVc5JcKDv/iYHMQZY07wWcC01mOW9fX5JHBJNO09UZAcg7NPghB9LaIGnRQ3L1qcgChPHlO2ELloEfNn51VdQM=,iv:CjhNXi9Y3aRa9DJRUxTqo+R7mjsfN7qhWQDlCoFI8QU=,tag:8DcaSxJfmNP2brSbCDTzkg==,type:str]
    version: 3.13.1
