apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: observability
type: Opaque
stringData:
    admin-password: ENC[AES256_GCM,data:1JiLz6KjhX2PbXA89Oc19cp7IGCRwg3j,iv:XapCyQ65iNkCBo5ZgsRGM+MSLOPuDOGDQvBxZaIoUIg=,tag:h6RejlEtu3CFLURbFkVdgA==,type:str]
    admin-user: ENC[AES256_GCM,data:Dr6nT7U=,iv:Feydj24fzuXmNdh+0szjgU//9+JgQ5BZMguXkmqqq0g=,tag:9ZHxseYoObh4CZHdZJqasg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsSnFWSXc2MXRTZ0tuNTh4
            aG9FRzJkRFdreXZaQ1V6bjlCMGh1WUNkQmpnCjh3RnpLWDhBR20wcGYvL3VWaVdF
            Vms4N1Qram1HRFFscnhaSGNNc2l3VEUKLS0tIE15ZmNPMjRRTk9HT2xzWVJrR25N
            ZjNlVUszMVJ2UGxNdUJZWEd4dDdxUTgKWvyv3ZEISzyicrFmlXxfteeJMVyBamJ/
            x1IPgkTcPYk8mSJvnwUtswni1+qObohexjs7vlzaG+A7OJUp3w9caQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1586thf5vkcdf5lcn3zwjpu8ltkwyq8efrhj8lr0vdrrt9k5f3qgsxeg7gx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-06T00:03:14Z"
    mac: ENC[AES256_GCM,data:bgORoTT/gT6+3S4+9WcdrgR7DGJ2IyZqG2IIyM4rzdfjWOjam0u2x9LJK8iASCbELp+zoQpIHaAOYGhMk1BgE5z9wELIAwz98tX8HbE4ZoTogIxEFH/4p6+MDFKIuYyFwd6GBm7bouHnGvXPXHeiA6EClO6WZ8lXQDD72LGQ7tU=,iv:ieH57NO9C74zL3P5jPgWSIFFafJiI+7Wh3bf6Ue1RLI=,tag:jE3zJh8l9scBe7cA7b1QkA==,type:str]
    version: 3.13.1
