apiVersion: v1
kind: Secret
metadata:
    name: grafana-oauth-secret
    namespace: observability
type: Opaque
stringData:
    client_secret: ENC[AES256_GCM,data:viqOlHEQK1SSw68p9bYSg/D5DpWa7bXadQkXtDyYgALuKEXmJKVMeFbxfNYpfnRfBdl3D4lmoesBOxA/0ETLz/tDUSw/DIMwDwzkLmrM3IDJbNoMrbf7aRRgjhQmn4payJIUzSwjilMee+mPxwSVg2lyhY+gK1pU6ueWMy8dzIs=,iv:SLdn5MNDpyzK/bYZ+k3ER8AMOEmGMW/M7PJ+YZF1jlQ=,tag:yItSWr6w7YEzYXG+KuRWpw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHazlKY3BrU2JXTUZ4KzZM
            OGRheE5WbjdOM0VpckxwRmpWU2hjL0x2Ukh3CllKZmZkWmFyVjR5QmxuN2FiNXJE
            OUplclM0K1h1UWM4d0ozM29tYjB2ZjQKLS0tIE9PeWM3Y2tJK0syaDZuczNUTDJq
            R1BqUmNZUzdRR0NMMFUvMldFYzl0Y1kKwKJIaTOn6Jpx7695sTgrDsBpL1cRva4J
            N3BhVCbeP1VETdA+sxYrXOuoOAJTOEjfGLOfy0Lj8xUPF3U5veCPtA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1586thf5vkcdf5lcn3zwjpu8ltkwyq8efrhj8lr0vdrrt9k5f3qgsxeg7gx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-25T21:03:05Z"
    mac: ENC[AES256_GCM,data:x8s7heIPXIkZVp+KvyLzVEpt06Y2EFcBqCoLchKh0wof3E7NbBsXvsGmNmghcY/J8lAmqrH6T1Y+01nvoVa06tynxfZPxzNojh7WtLokRWC16XEj502SoR89SQg2z16Sq/sJMxf7K8t338KF6k5+k4H+ztOdp1Gz2mRyRvw56xo=,iv:nQ0CDKcg6l/XN1/1Q66QlArbPLGwFwz/zC8R2cNMdEI=,tag:UsaE8s0mNl5whNUFpwKEcQ==,type:str]
    version: 3.13.1
