apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: observability-secrets
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - secrets/grafana-db-secret.enc.yaml
  - secrets/grafana-oauth-secret.enc.yaml
  - secrets/grafana-admin-secret.enc.yaml
  - secrets/alertmanager-config-secret.enc.yaml
  - secrets/pve-exporter-secrets.enc.yaml
