apiVersion: v1
kind: Secret
metadata:
    name: pve-exporter-secrets
    namespace: observability
type: Opaque
stringData:
    pve.yml: ENC[AES256_GCM,data:mHp2Iqlr4SK/U4SWeRsqwZ/s91Lq8FuWKfgv4l6+0XS8LoqnLT+52r0bPmeNIvfrhpIAEDA9FIyghrWXjQ3v9vS0Lrx6I15mentZBgFt6xcGIiTWEXxgcs/uJiyadFsjDDQUMG/X87Igv1bqfbKBgalqGtoD2Lel,iv:d/qfHpcqZlSB1g+rc8opjr/JuJfmQyVwODMMzv7z9rg=,tag:jlPU3A2UjhSHXSOFy25Fcg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJQlBBQmo5NmpWYk81NVhv
            MnJ4VHBaN3RTYVByZXpWbjlxQzFLb1JselFzCmJBeEpwNHpxNDBzM0t6UGpmd0hG
            RHJrMGV3Mno5UldqOStpbDJvck94MGsKLS0tIG10UGd5dnBkSklPSUZJRDVKQ3FJ
            Z1NkWmJJRHBsaVZtWmNhcEVZM3FiTG8KOcuwO9Hi384uWpbCn+4d4CQUtfxaL/sa
            oFCP35AgmJ4UQiu+6y7QXk9dk/Xx85GvmLE20I2yCHoI+jWgmK2prA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1586thf5vkcdf5lcn3zwjpu8ltkwyq8efrhj8lr0vdrrt9k5f3qgsxeg7gx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-25T21:03:05Z"
    mac: ENC[AES256_GCM,data:TEazu8dDljUIKPsi69hisd384VA2/LsmHoLuOLULSBuB81S60QBWFg3Shq8Koy5gbz6Fnx4XzkZc4ZJWLpHOoSk9ioH2W6OaDbCiWfWHGWIuaFptwg+X85fLxV4DFpeHOrho+SY3Mksk/YcPQIOPMJRUNRU0seupj6cTM4Kxyvc=,iv:oAfeVg36R99NXA+3YDFmEzRdCdsU84i3djR+wrveM9g=,tag:JqZD4SRhGpuqUKERfixBRg==,type:str]
    version: 3.13.1
