apiVersion: v1
kind: Secret
metadata:
    name: pve-exporter-secrets
    namespace: observability
type: Opaque
stringData:
    pve.yml: ENC[AES256_GCM,data:OVuQ2eUH5AjhF5FrCV/wMS9udNgd18UrgMSglsHsA/ddAjZfN2nJyCv23vPzz5mLtpBMZQ4/AmVMCXoSc7dBBpIJSRNk29qRVtGoQhmJhZnjy/K6WUY0/cEqvrvCG0bqu17CB3jYmHEN4CO+QAGx32KnLMo70V9rk6dUAnYyL2xUVE8=,iv:Eak928ZYbb+rpMcAqndjVTv2JkOi3THSdFar1h797D4=,tag:ksV6vNte7qBThWXDFFRD9g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzQUdvaHlucmhIU29MdUVP
            V1FTSHBML29WMW5EZlpNLzZlaFRSMXZ5Y204CkpVVi9jaGY1TkR1MFVNOGoydVg1
            b0VxQmkwREdwVGt5VjdZS09ZYjV1dHMKLS0tIDZUUEpXMTc5TkJqVDJYdjVWdk43
            ZDAzVTd2MnFUdG9VaFozQ1FDSGFkQncKuln9M0WxqMDfhJMK/5KB1SnXNEtH7Ssr
            +cPltVaFCInQMoKqbL7PvluQUCN9sOakcGnkQz4i9uRUZQiO+suZyg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1586thf5vkcdf5lcn3zwjpu8ltkwyq8efrhj8lr0vdrrt9k5f3qgsxeg7gx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-25T21:32:46Z"
    mac: ENC[AES256_GCM,data:SD55R471hchLwsRPz3MIynclyeVWW3FW15CW5+c+FeBWX+6OJKzl109tvlFyHyR1pgsW00w+T3jxpB0eBphsASSmJNCtnd95AjFbOqQlymtLPLK/mA5lwO/effEosjElHMlLP4l6wGprK1VNR1qdkx8AXkuyxijE94n1dbSeKRU=,iv:DnmDtVC9zgGWnKc2Hw5xunaOCkQ6bfAsDsO/WHwJokk=,tag:58r/tsOBY0djCzgADIL+vg==,type:str]
    version: 3.13.1
