
chromadb:
  isPersistent: true
  persistDirectory: /data
  data:
    volumeSize: "2Gi"
    storageClass: local-path
    accessModes: ["ReadWriteOnce"]

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: "1"
    memory: 1Gi
