---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cpa-manager-plus-data
  namespace: remote-pi
  labels:
    app.kubernetes.io/name: cpa-manager-plus
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
