apiVersion: v1
kind: Secret
metadata:
    name: mcp-hub-gmail
    namespace: mcp-hub
    annotations:
        mcp-hub.epaflix.com/revision: 20260924T101552Z
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:yr6x2ag=,iv:3wVWuO5xFQYQIELkoJpGyZ/zrZdh5r87XLjO5KdRKvk=,tag:3FYK3syGll+WQBZk4Uak1A==,type:str]
    client-secret: ENC[AES256_GCM,data:G287Ews=,iv:vdRehw/lmOhJhm0/1EZo/B/m4IwYdXFGXvPGjzGtns8=,tag:mzfDnqrnuXhJGrdANj15aA==,type:str]
    refresh-token: ENC[AES256_GCM,data:BK5V7hI=,iv:kcD6r1StBM1Uknntd5BHZE2TzhoZTrcWgdRtzxrKw8I=,tag:ghD8BpAF77m55E/fxG/NCA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByK3dyaGJuSzRnaEZUZDlM
            NWpBN1A1VkRJVE1XTldDM2Q0bXFod0pKcjJvCngwWGJBTWltbnBRWSs1MXhWb0Jn
            dHlUdHNSWkhpRk1LaW9nc2JuNEw0K3MKLS0tIFN3SFRKM2w2T3VaaUorRm9MWFNo
            SFZYVG54VjdEcVl1K2NKYWkyeEdiS0kKuTDDSN6jMWUG2r3NucunN2aCv4AChAsE
            Mi771HVl2TtQKfKe93C2EP2GYW+wFfT6L8XwJdcjljSZ4ARjMixZIw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1586thf5vkcdf5lcn3zwjpu8ltkwyq8efrhj8lr0vdrrt9k5f3qgsxeg7gx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-24T10:15:52Z"
    mac: ENC[AES256_GCM,data:4ecubTHY6mbHHdRhIVEuZwaZXg+q2FNlN4cPm3YxV8UQeVioLpK+qFOgjFnOB2qT0uf+JIpgn7C3oyeZ2zQzJb+Ljt6DLhQADvh3PHkiwY9viFoWxbrfjw7I67vNfnv4qAwmH89gwzeAaS+Wnd7JXru39m6EZwC3Bap0TzSAIY4=,iv:Aed/galkZq1JAb87Obe/sPY21EoBPIr/IUv1/Vbo0s4=,tag:xWDRIwHA6RYpqdvMqEyqKQ==,type:str]
    version: 3.13.3
