apiVersion: v1
kind: Secret
metadata:
    name: mcp-hub-jev
    namespace: mcp-hub
    annotations:
        mcp-hub.epaflix.com/revision: 20260927T113632Z
type: Opaque
stringData:
    openrouter-key: ENC[AES256_GCM,data:urk2Rp77AlsUMvb/ppTI+z7qdDFS/BR31oE/ndX+u070AJMSgP7qe+e8QDpKsYfJVSVqcO2SUcS8LZ9OKwthik4+jEjuA0lV/w==,iv:mX5X6dTPKGSxeG/McSvsYD3SBazwyijS0vWQgNPa6BQ=,tag:pq1CIn/rxGV7lxk80nrt4A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByaVVsU1N6ODJZdVNSOTJm
            L1FaTmxDM09Bbk9SbFMxZVBWcTVyY21qaWxzCnpPZHAzTzhNOUo0ZTlqdVNGdU5F
            RkkyS01iTmVFOFUxb3p6V0t5V1dFbDQKLS0tIEZ6NFE0RVdvQWJkaDR3bzVORDV1
            WWdsV0Z4SUlmTnZub1BTa0FpWGpPd28KJ+KxmXYsRu6Y7yVxg240Jja6fHb1stnr
            IDqYP7wlY3RfpDJq4i3lUa3rPEEqMh6Fr5OKtZh0MXzpxV1oUHknPQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1586thf5vkcdf5lcn3zwjpu8ltkwyq8efrhj8lr0vdrrt9k5f3qgsxeg7gx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-27T11:36:34Z"
    mac: ENC[AES256_GCM,data:eIj4SjlaxbGy09yeisidOx9WkjSQWp2VwY4WVRN/7fCVsE1rzKZpAzwP2g8FDUxtUMFxRiBCScDIUUM8dg2GIii3JUdcoakxy1s8JNaCYjjwEKXKjuwtIchOrEXpXkYguC7eqIhsin2zSYjltuffEJBQNiJKptxR8xq1LaOW3fo=,iv:yWFLrNb4JBhYWxa6m8GwaAIa7dkShsSET8RayhIKlZ0=,tag:ZUXUJIvSiodilktJw2R6xg==,type:str]
    version: 3.13.3
