apiVersion: v1
kind: Secret
metadata:
    name: mcp-hub-token
    namespace: mcp-hub
    annotations:
        mcp-hub.epaflix.com/revision: 20260924T101924Z
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:QoNRFrdVS8L0BUrMlAAhph37UbAmbiWQSlbPX7gAt79TO+wLDR0E7HKncg==,iv:u0kY2cCWBy9tiMy/2ySNaZU0JzmrkoZiVPcyruULIWM=,tag:0FBfMMEz6NyWno3qXIJ14g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKalREbFk0Yis5Qjg4RHpS
            UFZZakMvNEc3UkJLbXVKVE5PcHJ6VkRwV21zCjNGbFlDNytIbE9HeFFCWXVhTTRk
            b29Sb2FaR1RGYWU3cHlOeWZSWUVMamsKLS0tIGpwTXA4S3ZEcFE0OU0vS0NMamwr
            aEl1UkVyWTAxbEdLc3A2RlgzQ1ZCZ1EKC23q2zrJ6m0+1HeVI9rs2Xa/1gdxKPXC
            gGWKd4LkZis46VcvbalQ//+mGD+mPREpawpONyblRlOO88Tnr5LT8A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1586thf5vkcdf5lcn3zwjpu8ltkwyq8efrhj8lr0vdrrt9k5f3qgsxeg7gx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-24T10:19:24Z"
    mac: ENC[AES256_GCM,data:IRno+6fl6TmDSjfT8a3+c+xE7MdquhxOLTmqAH1eNdVso4KfP5l3oDS+3n7ysHS0yT5fEDMC6T8VyqUrteBCzNAWQEs8FFKkkKbEjL+QWJYW3CGbZ1scG3KE+UfRFiYyGtUweFH3AGF+dHQD4V+G18fvqET/FuXmAUGWMD/2Cgo=,iv:9Jy58ZGFYkeT+4CKLOZYavDDwUx2nZ/ZiMn1GGZi74I=,tag:Y7dhKCirzO81ff/03+Ua5w==,type:str]
    version: 3.13.3
