apiVersion: v1
kind: Secret
metadata:
    name: mcp-hub-vaultwarden
    namespace: mcp-hub
    annotations:
        mcp-hub.epaflix.com/revision: 20261003T204347Z
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:5keHkRTxAO1b6aHdzHMfI6IQeaUJaFyf10qGde3+mHxjYVjyH4U6/08=,iv:vmupUMWkT5yK5WxLnFp3jUlkOZf1BMFVYbifd0EeBpk=,tag:LGcutOA4YXFGB5Ka3OoALg==,type:str]
    client-secret: ENC[AES256_GCM,data:GWfJ7XUDhEWCX6wodR7/qeBIW+mwl418tySLHAXK,iv:VYIBw6+QnXJDFfLsWsubs9llFGn4Yi+eSyQERYNtY5c=,tag:lDb4zwCDMe2S8C6NVuziWg==,type:str]
    password: ENC[AES256_GCM,data:G4ob+MFiSUAo1iCR,iv:h8Bz5ehMIIh7VWAdfPWl8mIVboKOaYPj8jQYqiBDfa4=,tag:epvKQ+ort83JbA2wTGZgzQ==,type:str]
    hub-secret: ENC[AES256_GCM,data:a9vjtJzKTzepnI2tcKeLWRTBvKacmFFXqB+r5zQHXxMIJhkxrUcnZJkCeQ==,iv:B7jXxPHsbv7+gZtM4dufT4em8XA94kVinbEXb7ccCiw=,tag:h0doTYiXzzbmr7rmASptBg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVZGZ3NFg1b1ZsNm1uSC91
            K2luNjV4VUJ2dm5hd3BURXBaQ3BPNGlVV1FnCmhBalNKMkR0L0pMa1BTNGtaWWlK
            UUsySFBpVzV1alBrTUNxNUhDY2NuNzgKLS0tIGFHamZjaXZMVUQ3M0JkM1dUUlZ5
            U2Qxd1lxUDc4aDFwQkZnNEVuMUN6Z1kKums9ZWG0W8mvNR31gZElVhkV94zVr/7j
            tSNl8fa7XqVFW1Y5Q/YXlHaloKA8hSBKR2eLwtQw35pbdB09UxWNhQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1586thf5vkcdf5lcn3zwjpu8ltkwyq8efrhj8lr0vdrrt9k5f3qgsxeg7gx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T20:43:47Z"
    mac: ENC[AES256_GCM,data:Cbl07dzn71E4dM+Vm/BfkemjaD2elO71uV7Jq607hmxCwpbc91iiGoMatjY4DxsMPSsCgSw+PoRI3RugZHLXaGpl6lHpYMn5aWM0EzZErpaqcbfiAcx1RgopNShbzxxjuj+VB63ZAQM7kwycu+sWafb6DErm26Nly87r8HjBEII=,iv:ydS67bVJCX5bxLHAC3kzij0pVsdcvHSHUD1DcUVD3yY=,tag:f1CKgdW4JBLHroSFTmj7IQ==,type:str]
    version: 3.13.3
