apiVersion: v1
kind: Secret
metadata:
    name: t3code-jev
    namespace: t3code
type: Opaque
stringData:
    openrouter-key: ENC[AES256_GCM,data:LnzFRHllFdoTaB8x/z0YgBNyHLZ5qtveCr+Ahe38tGOTqtaGeLy+Ox/h9CCb9EHoBg3UBEo0ZwjIiRe9IjzGVTRgZgZA2kkvUw==,iv:qEx8Z3w3wfpRS/vpTLmDBScudqvJt0TZKIFZtnZmCL0=,tag:8wLJawYB0i1QsjlorznT2g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhU3VkVHg0WVVldW5rbmFQ
            algycGN0Ylp2QlhCTVRRL05rMTV4MFNqM0gwCjZYTWFiZ1p0dFVRWjNXVFhDMTdt
            cXBBQU1WM1RmaHlhUTBGQjVxYnRuR2MKLS0tIDlZamtqdXBIeGMzU3Rzc0gvbmhD
            WEV6Y04xalZ0SnJHVllaZkk5ZXlSOVEKvtuCBCB60J2cF8K3yhMqudPRvxJobFIW
            v00IAwDnZP/a8VVw+1GD2lQhQHRDlzRTnb31+CSkLkxx3rpY1SDY6Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1586thf5vkcdf5lcn3zwjpu8ltkwyq8efrhj8lr0vdrrt9k5f3qgsxeg7gx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-22T12:17:23Z"
    mac: ENC[AES256_GCM,data:Urtx1oNQGOtQBwZ/e4/4he93CPEiON6lfNJRzmNLIZ2pnnJp2AOIs32ZMiplV6MS5bvYSJZoDk0mW/ZBjkZI/PpXM/n2g/nIXxmGZ3yWnMuCOxf9rKReAwIcFUG/aP/YX2ND4HfGXF+BfVhXFg/v0WAmQQH1YGM+TbIduHAlEq8=,iv:EMSbg8dK+eKdgAo8s8aUrK4Jjv32+N7rmNFmXv+8E2M=,tag:Z9PhQlmy9Ei0C4RqziRWFQ==,type:str]
    version: 3.13.3
