apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: t3code-secrets
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - jev-secret.enc.yaml
  - private-agent-config.enc.yaml
  - cliproxy-secrets.enc.yaml
  - github-ssh.enc.yaml
  - mcp-hub-client.enc.yaml
