#!/usr/bin/env bash
# Fixture suite for check-sops-encrypted.sh.
#
# Uses a throwaway Git repository, stages real blobs, and invokes the real hook.
# Every concrete-looking fixture value is synthetic and intentionally unusable.
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
hook="$repo_root/.github/hooks/check-sops-encrypted.sh"
tmp="$(mktemp -d)"
output="$(mktemp)"
trap 'rm -rf "$tmp"; rm -f "$output"' EXIT

pass_count=0
fail_count=0

pass() {
  pass_count=$((pass_count + 1))
  printf 'ok - %s\n' "$1"
}

fail() {
  fail_count=$((fail_count + 1))
  printf 'not ok - %s\n' "$1" >&2
  if [ -s "$output" ]; then
    # Guard diagnostics contain paths, document numbers, and key names only.
    sed 's/^/  /' "$output" >&2
  fi
}

expect_pass() {
  local name=$1
  shift
  : >"$output"
  if (cd "$tmp" && bash "$hook" "$@") >"$output" 2>&1; then
    pass "$name"
  else
    fail "$name"
  fi
}

expect_fail() {
  local name=$1
  shift
  : >"$output"
  if (cd "$tmp" && bash "$hook" "$@") >"$output" 2>&1; then
    fail "$name"
  else
    pass "$name"
  fi
}

reset_repo() {
  git -C "$tmp" reset --hard -q "$baseline"
  git -C "$tmp" clean -fdqx
  mkdir -p "$tmp/fixtures"
}

write_genuine_sops_fixture() {
  local path=$1
  mkdir -p "$(dirname "$path")"
  cat >"$path" <<'YAML'
# Generated by SOPS 3.13.3 from a synthetic, unusable fixture value.
apiVersion: v1
kind: Secret
metadata:
    name: synthetic-encrypted
stringData:
    password: ENC[AES256_GCM,data:VuyzQHtUbNRmXVeG3RMTV309y4bNRu5f0+Bj0OwbmU2n0Q==,iv:RNDthdDhhzkizI5WOJSrSNdfCKZ8JegefvE7CcvatHY=,tag:xbScufs/KO1hh2W6eWw9pg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHdjVRMCtMOVdja3Z5NjJm
            RENSUEk2djZERittczAvWGpRUUI2TzY3RkRZCkxhL2NDYTJZaWFKd3c3VGJsajRV
            UVF5aU91U3ZBL3g0Z3ZBRnlaRnl6eUUKLS0tIE0xRFJsUmo0QnFERHRvOHJ3c2px
            R1VSRCtKbGE2YTRnTXcwRjgzTEM5WnMKBETwaCH+fsQb3HGpkqZjlBqLvGPqTEyf
            41vlyVVWeHaXvYmoJo3Tf5aNV5iplKD4p118KfQ0Iu9lzY1jIUViLw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1586thf5vkcdf5lcn3zwjpu8ltkwyq8efrhj8lr0vdrrt9k5f3qgsxeg7gx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-06T15:38:53Z"
    mac: ENC[AES256_GCM,data:kXJ1/fMNQPmPA9BT1js6ZrtY7MwNCqqL73/lqWn7RCZw0mmV1tYmpn93XeHz/np9HRYd6Eeo4YNFwbfACV6FnwRU4sqbzGBViywx1XE17euMscO3ygmSblu3qASKvfW9xnemiWG+PW7FmhqyahozvNyqWk1Ls/a6U98kBz4KhbM=,iv:WEakktGWCcbnLfQozntwRhhwZRWozjJSlNCRhbei0Io=,tag:n5S44VKL//ZKZh0vzvENjg==,type:str]
    version: 3.13.3
YAML
}

plaintext_templates=(
  "2-k3s/05.traefik-deployment/certificates/cloudflare-origin-cert.yaml"
  "2-k3s/06.postgres/cluster/postgres-secret.yaml"
  "2-k3s/06.postgres/operator-kustomization/barman-manifest.yaml"
  "2-k3s/07.authentik-deployment/secret-app.yaml"
  "2-k3s/08.servarr/seerr/authentik-oidc-secret.yaml"
  "2-k3s/08.servarr/_shared/secrets/postgres-secret.yaml"
  "2-k3s/10.observability/grafana-admin-secret.yaml"
  "2-k3s/10.observability/grafana-config/oauth-secret.yaml"
  "2-k3s/10.observability/grafana-db-secret.yaml"
  "2-k3s/10.observability/pve-exporter/secret.yaml"
  "2-k3s/11.argocd/oidc-secret.yaml"
  "2-k3s/12.renovate/secret-app.yaml"
)

git -C "$tmp" init -q
git -C "$tmp" config user.name "Synthetic Fixture"
git -C "$tmp" config user.email "fixture.invalid@example.invalid"
printf 'charts/\n' >"$tmp/.gitignore"
for path in "${plaintext_templates[@]}"; do
  mkdir -p "$tmp/$(dirname "$path")"
  cp "$repo_root/$path" "$tmp/$path"
done
git -C "$tmp" add .
git -C "$tmp" commit -q --no-verify -m "fixture baseline"
baseline="$(git -C "$tmp" rev-parse HEAD)"

# A comment-only change to every existing plaintext template must stay editable.
for path in "${plaintext_templates[@]}"; do
  printf '\n# fixture: comment-only edit\n' >>"$tmp/$path"
done
git -C "$tmp" add "${plaintext_templates[@]}"
expect_pass "comment-only edits to all 12 plaintext Secret files pass"

# The one concrete non-sensitive exception is constrained to its image field.
reset_repo
barman="2-k3s/06.postgres/operator-kustomization/barman-manifest.yaml"
printf '\n# fixture: comment-only barman edit\n' >>"$tmp/$barman"
git -C "$tmp" add "$barman"
expect_pass "active barman image Secret passes its narrow validator"

# The image exception applies only to data.SIDECAR_IMAGE. This known-prefix
# annotation is synthetic and unusable, but every non-exempt field must still
# pass through the same classifier used by an ordinary Secret.
reset_repo
python3 - "$tmp/$barman" <<'PY'
from pathlib import Path
import sys
path = Path(sys.argv[1])
text = path.read_text()
text = text.replace(
    "metadata:\n  name: plugin-barman-cloud-f998mh5292\n",
    "metadata:\n  annotations:\n    synthetic.example/review: github_pat_SYNTHETIC_BARMAN_ANNOTATION_000000\n  name: plugin-barman-cloud-f998mh5292\n",
    1,
)
path.write_text(text)
PY
git -C "$tmp" add "$barman"
expect_fail "barman image exception does not exempt credential-shaped annotations"

reset_repo
python3 - "$tmp/$barman" <<'PY'
from pathlib import Path
import sys
path = Path(sys.argv[1])
text = path.read_text()
text = text.replace(
    "data:\n  SIDECAR_IMAGE: |\n",
    "data:\n  SYNTHETIC_EXTRA_FIELD: <SYNTHETIC_EXTRA_FIELD>\n  SIDECAR_IMAGE: |\n",
    1,
)
path.write_text(text)
PY
git -C "$tmp" add "$barman"
expect_fail "barman path does not grant blanket trust to extra payload fields"

# Generic templates can add legitimate fields without a per-file policy edit.
reset_repo
postgres="2-k3s/06.postgres/cluster/postgres-secret.yaml"
printf '  optional-port: "5433"\n  optional-password: "<OPTIONAL_PASSWORD>"\n' >>"$tmp/$postgres"
git -C "$tmp" add "$postgres"
expect_pass "new safe template keys do not require a policy update"

# Synthetic token-shaped text under a non-sensitive key exercises the global
# known-prefix/entropy classifier.  It is not a real or usable credential.
reset_repo
mkdir -p "$tmp/fixtures"
cat >"$tmp/fixtures/concrete-secret.yaml" <<'YAML'
# Synthetic only: this token-shaped value is deliberately not a real credential.
apiVersion: v1
kind: Secret
metadata:
  name: synthetic-concrete
stringData:
  username: "github_pat_SYNTHETIC_NOT_A_REAL_TOKEN_000000000000"
YAML
git -C "$tmp" add fixtures/concrete-secret.yaml
expect_fail "credential-shaped plaintext under a non-sensitive key fails"

# Synthetic punctuation-heavy input reproduces the reviewed entropy bypass.
# It is deliberately constructed test data, not a real or usable credential.
reset_repo
cat >"$tmp/fixtures/punctuation-entropy.yaml" <<'YAML'
apiVersion: v1
kind: Secret
metadata:
  name: synthetic-punctuation-entropy
stringData:
  username: 'V7!mQ2@xR9#kL4$zN8%pT6^w'
YAML
git -C "$tmp" add fixtures/punctuation-entropy.yaml
expect_fail "punctuation-heavy high entropy under a non-sensitive key fails"

# Exactly 18 distinct synthetic characters reproduce the reviewed short-value
# bypass. Shannon entropy density is about 4.17 bits per character.
reset_repo
cat >"$tmp/fixtures/short-high-entropy.yaml" <<'YAML'
# Synthetic only: this is constructed classifier input, not a real credential.
apiVersion: v1
kind: Secret
metadata:
  name: synthetic-short-high-entropy
stringData:
  value: 'aB3$dE5&gH7*jK9!mN'
YAML
git -C "$tmp" add fixtures/short-high-entropy.yaml
expect_fail "18-character high-entropy value under a non-sensitive key fails"

# Internal whitespace and printable Unicode must not disable entropy analysis.
# Both values are constructed synthetic character sets, not usable credentials.
reset_repo
cat >"$tmp/fixtures/whitespace-unicode-entropy.yaml" <<'YAML'
apiVersion: v1
kind: Secret
metadata:
  name: synthetic-whitespace-unicode-entropy
stringData:
  spaced-label: 'V7!mQ2@xR9# kL4$zN8%pT6^w'
  unicode-label: 'αβγδεζηθικλμνξοπρστυφχψω'
YAML
git -C "$tmp" add fixtures/whitespace-unicode-entropy.yaml
expect_fail "internal whitespace and printable Unicode do not bypass entropy checks"

# Kubernetes deploys Secret objects nested under List/SecretList items.  The
# checker rejects those containers rather than skipping their nested payloads.
reset_repo
cat >"$tmp/fixtures/secret-list.yaml" <<'YAML'
# Synthetic only: this nested value is deliberately not a real credential.
apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: synthetic-nested-secret
    stringData:
      password: SYNTHETIC-CONCRETE-NESTED-PASSWORD
YAML
git -C "$tmp" add fixtures/secret-list.yaml
expect_fail "Secret nested inside a Kubernetes List cannot bypass validation"

# A sensitive scalar is still hard-gated when its key ends in a reference-like
# suffix.  This repeated word is synthetic and intentionally low entropy.
reset_repo
cat >"$tmp/fixtures/scalar-password-ref.yaml" <<'YAML'
apiVersion: v1
kind: Secret
metadata:
  name: synthetic-scalar-reference
stringData:
  password-ref: violet-violet-violet-violet
YAML
git -C "$tmp" add fixtures/scalar-password-ref.yaml
expect_fail "scalar password-ref is not exempt from placeholder enforcement"

# Arbitrary lowercase angle-bracket text is not an approved placeholder.  This
# synthetic passphrase shape exercises the narrowed whole-value grammar.
reset_repo
cat >"$tmp/fixtures/passphrase-placeholder.yaml" <<'YAML'
apiVersion: v1
kind: Secret
metadata:
  name: synthetic-passphrase-placeholder
stringData:
  password: <violet-violet-violet-violet>
YAML
git -C "$tmp" add fixtures/passphrase-placeholder.yaml
expect_fail "passphrase-shaped angle-bracket value is not a placeholder"

# Embedded YAML must be parsed and walked; replacing the nested placeholder
# with another clearly synthetic token shape must fail without printing it.
reset_repo
pve="2-k3s/10.observability/pve-exporter/secret.yaml"
python3 - "$tmp/$pve" <<'PY'
from pathlib import Path
import sys
path = Path(sys.argv[1])
text = path.read_text()
text = text.replace(
    "<PROXMOX_API_TOKEN_VALUE>",
    "github_pat_SYNTHETIC_NESTED_NOT_A_REAL_TOKEN_000000000000",
)
path.write_text(text)
PY
git -C "$tmp" add "$pve"
expect_fail "credential-shaped value hidden in embedded pve.yml fails"

# Every string is offered to the safe YAML parser.  This synthetic one-line
# block scalar must become a mapping whose nested sensitive key is hard-gated.
reset_repo
cat >"$tmp/fixtures/one-line-embedded.yaml" <<'YAML'
# Synthetic only: this marker is intentionally not a real credential.
apiVersion: v1
kind: Secret
metadata:
  name: synthetic-one-line-embedded
stringData:
  config: |-
    password: SYNTHETIC-NOT-A-CREDENTIAL
YAML
git -C "$tmp" add fixtures/one-line-embedded.yaml
expect_fail "one-line embedded YAML with a sensitive field fails"

# Merely containing a placeholder is not enough: the whole sensitive value
# must be one approved placeholder token.
reset_repo
cat >"$tmp/fixtures/partial-placeholder.yaml" <<'YAML'
# Synthetic only: the suffix is a marker, not a real credential.
apiVersion: v1
kind: Secret
metadata:
  name: synthetic-partial-placeholder
stringData:
  password: "<PASSWORD>-SYNTHETIC-CONCRETE"
YAML
git -C "$tmp" add fixtures/partial-placeholder.yaml
expect_fail "placeholder alongside concrete text fails"

reset_repo
write_genuine_sops_fixture "$tmp/fixtures/encrypted.enc.yaml"
git -C "$tmp" add fixtures/encrypted.enc.yaml
expect_pass "genuinely SOPS-generated document-local encrypted Secret passes"

# A bare ENC-looking scalar plus a stub mapping is not a SOPS envelope or real
# metadata.  Every marker is synthetic and intentionally unusable.
reset_repo
cat >"$tmp/fixtures/bare-enc.enc.yaml" <<'YAML'
apiVersion: v1
kind: Secret
metadata:
  name: synthetic-bare-enc
stringData:
  password: ENC[SYNTHETIC-PLAINTEXT-PASSWORD]
sops:
  marker: synthetic
YAML
git -C "$tmp" add fixtures/bare-enc.enc.yaml
expect_fail "bare ENC marker with stub SOPS metadata fails"

reset_repo
write_genuine_sops_fixture "$tmp/fixtures/mixed.enc.yaml"
cat >>"$tmp/fixtures/mixed.enc.yaml" <<'YAML'
---
apiVersion: v1
kind: Secret
metadata:
  name: synthetic-plaintext-second-document
stringData:
  password: "SYNTHETIC_CONCRETE_NOT_A_REAL_PASSWORD"
YAML
git -C "$tmp" add fixtures/mixed.enc.yaml
expect_fail "SOPS metadata in one document cannot bless another Secret document"

reset_repo
write_genuine_sops_fixture "$tmp/fixtures/wrong-suffix.yaml"
git -C "$tmp" add fixtures/wrong-suffix.yaml
expect_fail "SOPS Secret without the encrypted-file suffix fails"

reset_repo
cat >"$tmp/fixtures/configmap.yaml" <<'YAML'
apiVersion: v1
kind: ConfigMap
metadata:
  name: ordinary-config
# A key name alone does not matter outside a Secret document.
data:
  password: ordinary-configuration-text
YAML
git -C "$tmp" add fixtures/configmap.yaml
expect_pass "non-Secret YAML passes"

# Generated chart caches are ignored, but the SOPS guard does not use their
# path as a bypass.  A non-Secret chart template is outside this guard's scope;
# a chart Secret with an unapproved sensitive value is still rejected.
reset_repo
chart_dir="$tmp/vendor/charts/demo/templates"
mkdir -p "$chart_dir"
cat >"$chart_dir/configmap.yaml" <<'YAML'
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-synthetic"
YAML
git -C "$tmp" add -f vendor/charts/demo/templates/configmap.yaml
expect_pass "non-Secret vendored chart template passes the Secret guard"

reset_repo
mkdir -p "$chart_dir"
cat >"$chart_dir/secret.yaml" <<'YAML'
# Synthetic chart fixture; the template expression is not a credential.
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-synthetic"
stringData:
  password: "{{ .Values.syntheticPassword }}"
YAML
git -C "$tmp" add -f vendor/charts/demo/templates/secret.yaml
expect_fail "force-added chart Secret is not exempt by path"

# Full-tree mode must catch a bypassed commit even when the staged diff is empty.
reset_repo
mkdir -p "$tmp/fixtures"
cat >"$tmp/fixtures/bypassed.yaml" <<'YAML'
# Synthetic only: this value is intentionally not a real credential.
apiVersion: v1
kind: Secret
metadata:
  name: synthetic-bypassed
stringData:
  token: "SYNTHETIC_CONCRETE_NOT_A_REAL_TOKEN"
YAML
git -C "$tmp" add fixtures/bypassed.yaml
git -C "$tmp" commit -q --no-verify -m "synthetic bypass fixture"
expect_pass "cached mode ignores unchanged tracked files"
expect_fail "full-tree mode catches a bypassed plaintext Secret" --full-tree

printf '%s\n' "1..$((pass_count + fail_count))"
if [ "$fail_count" -ne 0 ]; then
  printf '%s fixture test(s) failed\n' "$fail_count" >&2
  exit 1
fi
printf 'All %s fixture tests passed.\n' "$pass_count"
