apiVersion: v1
kind: Secret
metadata:
    name: authentik-app-secrets
    namespace: app-authentik
stringData:
    AUTHENTIK_EMAIL__FROM: ENC[AES256_GCM,data:JUmZHcPz8+EEC+OLSqBBoQ==,iv:plUkA/9XCth1vAg5vhqWNN1iO3XgS1I+FPUD73CeTRI=,tag:MidqAeJQn2kM+Xugt8Annw==,type:str]
    AUTHENTIK_EMAIL__HOST: ENC[AES256_GCM,data:j+/NEhx8w3fC2y2/iJyeJMs=,iv:FE/dDRgTrXK9GPIXS9gOpfhslFePcq2EMxgnpLMwGCU=,tag:68Ve78ipM6PzZrdc63D5Ng==,type:str]
    AUTHENTIK_EMAIL__PASSWORD: ENC[AES256_GCM,data:bE7jnWsCr8enc4vJjopjk+gOXhveh4TOmA==,iv:MjyYjZmMp51OYTDQWDceqGGKbNZTjaqyNbEDUrDNK/s=,tag:kK64COax9BHM/SgqTRfZDA==,type:str]
    AUTHENTIK_EMAIL__USERNAME: ENC[AES256_GCM,data:ywc/HLwdXvsXzzt2DlS+rA==,iv:O7Ys3aVd1bCuUbe4X/muKWZ4KaFq6fvno0FB8N7ke3g=,tag:amOETcfI8P8zywq4dnBrrQ==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:wY3EuIDH2WuCe8ogP8GYh5mcK9Q=,iv:mYPG19MkeNgyXEk4YQ7LqqbYJA1vO2mHONJLihue4UE=,tag:YHO8DYoPZAHmqSRIxIP4Iw==,type:str]
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:/IMPe7XWNdrtN8aGPZISREZSmzw=,iv:ZLjaRUaHIPFj2+qHGKpSVPWnFkHeH+DSGh4iRDxoC1k=,tag:cAyzVK67sQpbPlKOBrCmSA==,type:str]
    AUTHENTIK_BOOTSTRAP_PASSWORD_HASH: ENC[AES256_GCM,data:EK2qDjLuMoM1jQbsYnoPWAAWzMdjLQ5r4DId+jQmG2gMNzz+EV/boxgQvTkmQurLKzdvU104CSPYLRC8Sj8SGnKgeZHUxX/l3ZLJ0thZVLeXoLsrOyOPCF8=,iv:ylWyvRlukC3IF6SSKgPrvFSzDVWIl/6yMFyTzHzvAQ8=,tag:lbWUy0NO/1j9o5yCupzguA==,type:str]
    AUTHENTIK_BOOTSTRAP_EMAIL: ENC[AES256_GCM,data:K5my3DhizO0cL0Z7BLBEcw==,iv:8KHfEc6v8IdQPmPOq2yJzasNNCIrtLRpVqGD+zwoLYU=,tag:3RWFkZDNJ9DdFV859hOl2g==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmSm9ML2tMRlYrbytmempZ
            RlJPMjRkTytQYjJacFFESnI1TXplRVlwMmdnCldJMTZpbFE0dkNyT3VzM1dhTnBJ
            MnQzVHZOdzJ2MlhVZTV1cTNzNlRDUjQKLS0tIFo5VVVYL1lGUmRUWENCRE9MMUd6
            L3V6dEN0TWdzaDFxTmpnemNXWSt4YlEKbNcLCAdaBmLgI7Xw51e9ki9JdyDahKnF
            avrhcIp/eEGiXgxJpHsIcEp8Qt94eZf9KaKZa8aNUP03lC0iOAhF9Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1586thf5vkcdf5lcn3zwjpu8ltkwyq8efrhj8lr0vdrrt9k5f3qgsxeg7gx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-21T16:48:28Z"
    mac: ENC[AES256_GCM,data:UA3R7bFly8QuEt3rVQXM5MqP/rjwxUm/f16XF3q2tWA4OJEZxwdO66sIvL+L6kKJTSt0fPUfEONOcCwKIDbCObiz8EWUm7c6YqNa7VyBrx79fIqxNvEtgo0u9QqG4Lofsh6O7SQdcO8GItjqafeRjb3E/VOUPzU9H63PDt3yDpw=,iv:7NhoRZVsjPTMVKjiCh9Tt77lUPwRL5KCGZiYGlxOZto=,tag:+hmbL3rZ6XWrBeE8nUMcJw==,type:str]
    version: 3.13.3
