apiVersion: v1
kind: Secret
metadata:
    name: authentik-app-secrets
    namespace: app-authentik
stringData:
    AUTHENTIK_EMAIL__FROM: ENC[AES256_GCM,data:JUmZHcPz8+EEC+OLSqBBoQ==,iv:plUkA/9XCth1vAg5vhqWNN1iO3XgS1I+FPUD73CeTRI=,tag:MidqAeJQn2kM+Xugt8Annw==,type:str]
    AUTHENTIK_EMAIL__HOST: ENC[AES256_GCM,data:j+/NEhx8w3fC2y2/iJyeJMs=,iv:FE/dDRgTrXK9GPIXS9gOpfhslFePcq2EMxgnpLMwGCU=,tag:68Ve78ipM6PzZrdc63D5Ng==,type:str]
    AUTHENTIK_EMAIL__PASSWORD: ENC[AES256_GCM,data:bE7jnWsCr8enc4vJjopjk+gOXhveh4TOmA==,iv:MjyYjZmMp51OYTDQWDceqGGKbNZTjaqyNbEDUrDNK/s=,tag:kK64COax9BHM/SgqTRfZDA==,type:str]
    AUTHENTIK_EMAIL__USERNAME: ENC[AES256_GCM,data:ywc/HLwdXvsXzzt2DlS+rA==,iv:O7Ys3aVd1bCuUbe4X/muKWZ4KaFq6fvno0FB8N7ke3g=,tag:amOETcfI8P8zywq4dnBrrQ==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:wY3EuIDH2WuCe8ogP8GYh5mcK9Q=,iv:mYPG19MkeNgyXEk4YQ7LqqbYJA1vO2mHONJLihue4UE=,tag:YHO8DYoPZAHmqSRIxIP4Iw==,type:str]
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:AojLQPBLHYSBP6TpT/A5gl32W/OIBsILS7Sb/+O4ewU5BHXmeOwmikyHNEJu/nHV/IM=,iv:qiZ+BmMCjpl7UQYMsz+DiIdtfSdU1J8yQ5HQIvquCrs=,tag:oXF+aVlYzn6Ib1rQcJKang==,type:str]
    AUTHENTIK_BOOTSTRAP_PASSWORD_HASH: ENC[AES256_GCM,data:EK2qDjLuMoM1jQbsYnoPWAAWzMdjLQ5r4DId+jQmG2gMNzz+EV/boxgQvTkmQurLKzdvU104CSPYLRC8Sj8SGnKgeZHUxX/l3ZLJ0thZVLeXoLsrOyOPCF8=,iv:ylWyvRlukC3IF6SSKgPrvFSzDVWIl/6yMFyTzHzvAQ8=,tag:lbWUy0NO/1j9o5yCupzguA==,type:str]
    AUTHENTIK_BOOTSTRAP_EMAIL: ENC[AES256_GCM,data:K5my3DhizO0cL0Z7BLBEcw==,iv:8KHfEc6v8IdQPmPOq2yJzasNNCIrtLRpVqGD+zwoLYU=,tag:3RWFkZDNJ9DdFV859hOl2g==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmSm9ML2tMRlYrbytmempZ
            RlJPMjRkTytQYjJacFFESnI1TXplRVlwMmdnCldJMTZpbFE0dkNyT3VzM1dhTnBJ
            MnQzVHZOdzJ2MlhVZTV1cTNzNlRDUjQKLS0tIFo5VVVYL1lGUmRUWENCRE9MMUd6
            L3V6dEN0TWdzaDFxTmpnemNXWSt4YlEKbNcLCAdaBmLgI7Xw51e9ki9JdyDahKnF
            avrhcIp/eEGiXgxJpHsIcEp8Qt94eZf9KaKZa8aNUP03lC0iOAhF9Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1586thf5vkcdf5lcn3zwjpu8ltkwyq8efrhj8lr0vdrrt9k5f3qgsxeg7gx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-22T05:45:45Z"
    mac: ENC[AES256_GCM,data:Y567+nRegMnHF1sVNgF9yaIVcwXgwe0q2bT0yA4FQiA6K1cnqUM7Wx4CvBLAzrkxSHJDnrftNtw/fWbsqIskXaEPtC/EyQFoYurqAlaWoTwGxZNUcyUyeoF7umYQK2Lqv3uOxHmAK2ElET19J8re7jHAl0X7nQNMxi8eC9VsymE=,iv:eSrqgniOJroseT41EiLfhcX4QMIEEoo9hZblzMkVqWM=,tag:P8uYXT/RtaWcmNDwm+I+qw==,type:str]
    version: 3.13.3
