---
apiVersion: v1
kind: Secret
metadata:
  name: authentik-app-secrets
  namespace: app-authentik
type: Opaque
stringData:
  AUTHENTIK_SECRET_KEY: "<AUTHENTIK_SECRET_KEY>"
  AUTHENTIK_POSTGRESQL__PASSWORD: "<AUTHENTIK_DB_PASSWORD>"
  AUTHENTIK_EMAIL__HOST: "<SMTP_HOST>"
  AUTHENTIK_EMAIL__USERNAME: "<SMTP_USERNAME>"
  AUTHENTIK_EMAIL__PASSWORD: "<SMTP_PASSWORD>"
  AUTHENTIK_EMAIL__FROM: "<SMTP_FROM>"
