---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: bazarr-internal
  namespace: servarr
spec:
  entryPoints:
    - internal
  routes:
    - match: Host(`bazarr.epaflix.com`)
      kind: Rule
      services:
        - name: bazarr
          port: 6767
  tls:
    certResolver: cloudflare
    domains:
      - main: epaflix.com
        sans:
          - "*.epaflix.com"
