---
apiVersion: v1
kind: ConfigMap
metadata:
  name: airvpn-bluetit-config
  namespace: servarr
data:
  bluetit.conf: |
    airconnectatboot            quick
    airvpntype                  wireguard
    airport                     1637

    airwhitecountrylist         nl,de,se

    airblackserverlist          Cygnus,Hassaleh,Kajam

    country                     NO
    forbidquickhomecountry      yes

    networklockpersist          iptables
    allowprivatenetwork         yes
    allowping                   yes

    airipv6                     no
    air6to4                     no

    ignorednspush               yes

    tunpersist                  yes

    airkey                      Default
