---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: qbittorrent-internal
  namespace: servarr
spec:
  entryPoints:
    - internal
  routes:
    - match: Host(`qbittorrent.epaflix.com`)
      kind: Rule
      services:
        - name: qbittorrent
          port: 8080
  tls:
    certResolver: cloudflare
    domains:
      - main: epaflix.com
        sans:
          - "*.epaflix.com"
