---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SpyrosPsarras/epaflix.git
    targetRevision: main
    path: 2-k3s/06.postgres
  destination:
    server: https://kubernetes.default.svc
    namespace: postgres-system
  syncPolicy:
    automated:
      selfHeal: true
      prune: false
    syncOptions:
      - ServerSideApply=true
  ignoreDifferences:
    - group: ""
      kind: Service
      jsonPointers:
        - /spec/clusterIP
        - /spec/clusterIPs
        - /status
    - group: ""
      kind: PersistentVolumeClaim
      jsonPointers:
        - /status
        - /spec/volumeName
    - group: postgresql.cnpg.io
      kind: Cluster
      name: postgres-cluster
      jsonPointers:
        - /status
        - /spec/bootstrap
        - /spec/imageCatalogRef
        - /spec/imagePullSecrets
        - /spec/inheritedMetadata
    - group: postgresql.cnpg.io
      kind: Pooler
      name: postgres-pooler
      jsonPointers:
        - /status
    - group: postgresql.cnpg.io
      kind: ScheduledBackup
      name: postgres-daily-backup
      jsonPointers:
        - /status
