---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SpyrosPsarras/epaflix.git
    targetRevision: main
    path: 2-k3s/11.argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  ignoreDifferences:
    - group: ""
      kind: Service
      jsonPointers:
        - /spec/clusterIP
        - /spec/clusterIPs
        - /status
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /spec/replicas
    - group: ""
      kind: Secret
      name: argocd-secret
      jsonPointers:
        - /data
        - /stringData
    - group: ""
      kind: Secret
      name: argocd-initial-admin-secret
      jsonPointers:
        - /data
        - /stringData
    - group: ""
      kind: Secret
      name: argocd-redis
      jsonPointers:
        - /data
        - /stringData
