---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: remote-pi
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SpyrosPsarras/epaflix.git
    targetRevision: main
    path: 2-k3s/17.remote-pi
  destination:
    server: https://kubernetes.default.svc
    namespace: remote-pi
  syncPolicy:
    automated:
      selfHeal: true
      prune: false
    syncOptions:
      - ServerSideApply=true
  ignoreDifferences:
    - group: ""
      kind: Service
      jsonPointers:
        - /spec/clusterIP
        - /spec/clusterIPs
        - /status
    - group: ""
      kind: PersistentVolumeClaim
      jsonPointers:
        - /status
        - /spec/volumeName
    - group: postgresql.cnpg.io
      kind: Database
      jsonPointers:
        - /status
    - group: postgresql.cnpg.io
      kind: DatabaseRole
      jsonPointers:
        - /status
