---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deal-finder
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SpyrosPsarras/epaflix.git
    targetRevision: main
    path: 2-k3s/24.deal-finder
  destination:
    server: https://kubernetes.default.svc
    namespace: deal-finder
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
  ignoreDifferences:
    - group: ""
      kind: Service
      jsonPointers:
        - /spec/clusterIP
        - /spec/clusterIPs
        - /status
    - group: postgresql.cnpg.io
      kind: Database
      jsonPointers:
        - /status
    - group: postgresql.cnpg.io
      kind: DatabaseRole
      jsonPointers:
        - /status
