---

apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  epaflix.server: |
    epaflix.com:53 {
        errors
        cache 30
        forward . 192.168.10.51 192.168.10.52 192.168.10.53
        log
    }
