---

global:
  domain: argocd.epaflix.com
  securityContext:
    fsGroup: 999

crds:
  install: false

configs:
  params:
    server.insecure: true

  cm:
    url: https://argocd.epaflix.com
    admin.enabled: false
    application.resourceTrackingMethod: annotation
    kustomize.buildOptions: --enable-helm --enable-alpha-plugins --enable-exec
    resource.exclusions: |
      - apiGroups:
          - ""
        kinds:
          - Endpoints
    oidc.config: |
      name: authentik
      issuer: https://auth.epaflix.com/application/o/argocd/
      clientID: $argocd-secret:oidc.authentik.clientId
      clientSecret: $argocd-secret:oidc.authentik.clientSecret
      requestedScopes:
        - openid
        - profile
        - email
        - groups
      requestedIDTokenClaims:
        groups:
          essential: true

  rbac:
    policy.default: role:readonly
    policy.csv: |
      g, ArgoCD Admins, role:admin
    scopes: "[groups]"

  cmp:
    create: false

server:
  deploymentAnnotations:
    secret.reloader.stakater.com/reload: "argocd-redis"
  ingress:
    enabled: false
  service:
    type: ClusterIP
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 512Mi

controller:
  statefulsetAnnotations:
    secret.reloader.stakater.com/reload: "argocd-redis"
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      memory: 1Gi

repoServer:
  deploymentAnnotations:
    secret.reloader.stakater.com/reload: "argocd-redis"
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 512Mi
  volumes:
    - name: custom-tools
      emptyDir: {}
    - name: sops-age
      secret:
        secretName: sops-age
        defaultMode: 0440
  volumeMounts:
    - name: custom-tools
      mountPath: /custom-tools
    - name: sops-age
      mountPath: /var/sops
      readOnly: true
  env:
    - name: SOPS_AGE_KEY_FILE
      value: /var/sops/keys.txt
    - name: XDG_CONFIG_HOME
      value: /.config
    - name: PATH
      value: /custom-tools:/usr/local/bin:/usr/bin:/bin
  initContainers:
    - name: install-ksops
      image: viaductoss/ksops:v4.3.3
      command: ["/bin/sh", "-c"]
      args:
        - |
          set -e
          echo "Copying ksops + kustomize into shared volume..."
          cp /usr/local/bin/ksops /custom-tools/
          cp /usr/local/bin/kustomize /custom-tools/
          echo "Done."
      volumeMounts:
        - name: custom-tools
          mountPath: /custom-tools

applicationSet:
  enabled: true

notifications:
  enabled: false

dex:
  enabled: false

redis-ha:
  enabled: false

redis:
  enabled: true
  deploymentAnnotations:
    secret.reloader.stakater.com/reload: "argocd-redis"

redisSecretInit:
  enabled: false
