---

apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
type: Opaque
stringData:
  oidc.authentik.clientId: "<ARGOCD_OIDC_CLIENT_ID>"
  oidc.authentik.clientSecret: "<ARGOCD_OIDC_CLIENT_SECRET>"
