---
apiVersion: v1
kind: Service
metadata:
  name: postgres-pooler
  namespace: postgres-system
  labels:
    app: postgres-pooler
    service-type: pooler
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.10.108
  selector:
    cnpg.io/poolerName: postgres-pooler
  ports:
    - name: pgbouncer
      port: 5432
      targetPort: 5432
      protocol: TCP
  sessionAffinity: None
