apiVersion: v1
kind: Secret
metadata:
    name: filebrowser-oidc
    namespace: filebrowser
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:vvfOppWw74hl6kcVAYDKh1PQvNuuAZEwvbJBmgyc9uHJPMf9QKjGYg==,iv:55qVubOVeuas58UELoZI01ceRA685kq9Zq3GdXSGvQU=,tag:ZA2ASoLDVaSJdIJYd9No8A==,type:str]
    client-secret: ENC[AES256_GCM,data:3PrLIYwRlQ8+Y1Dgbig/y6PaTpmZktRZvVtiFTeIneUnpyxAilUX4yIvxWSnTdXNsEGUyroRz+N8vtcNqQpqhX1l4+pdpyVLm/VPqewnznuq9CPUv53nP5QcxZHXe/KsNDPhAmL5ucGF8GAzkr21rhzveY9/vjwCNsgT3l3pOJs=,iv:AXcIdexiTqzqp7UJKWVlw6eza9bUTbnHAviUDIhMHuE=,tag:gRGbfNUIueVG54aqaOgyNQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1KzFCZWhSSUJyVVFKVGJp
            dnRpWjl2Y3h6OVV3YzRlUEE4M20zT2lrVEZNCmN5MEtkbjRHbFMybE5uVHRsM1FP
            S0kvNmQwc0ttUzlZRFJDa3ZPUi92TTgKLS0tIFhkVjB4aDdKNVRncGJZYmM1ZEdJ
            b3BSN25tV0FyaCtBSW5wUTRldHVFaDgKTzIZxfarPmxcR7NyZHKoet+VadyruY98
            AiN448ExLwsgBDzamN9XST9CCJJNm1AKZh7KWJZ8hD9y4nQyzhlIkg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1586thf5vkcdf5lcn3zwjpu8ltkwyq8efrhj8lr0vdrrt9k5f3qgsxeg7gx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-25T20:14:23Z"
    mac: ENC[AES256_GCM,data:oZCeQB2gySYb6rn7/Hy3/BgzdOjh6eF+F7ym+kKT8V6cu2alVZ096tql6zVI/iTc2jnc/1Ejw9N0C7ejud/9JJFfYFnbvSgMKnlvQsibIXwvP9dxxB8QVNy6sm8S5WWGcYfLUfZ2SCdrs2NIPzGKzV7rsu3oLakzSaFoo913p7M=,iv:pXzXV6fYctcR8v0GI3ESw8+H56NqU1D47xcZ7XQnXic=,tag:GQAvNGFTSaASrojQq+3cAA==,type:str]
    version: 3.13.1
