apiVersion: v1
kind: Secret
metadata:
    name: deal-finder-db-role
    namespace: postgres-system
    labels:
        app.kubernetes.io/name: deal-finder
        app.kubernetes.io/component: database
    annotations:
        argocd.argoproj.io/sync-wave: "-2"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:/3zF0i39OMwQ0A==,iv:j0u3RS3JEsGVBCFx6m2zzOn8LTmuZNPU+z9/YEfp874=,tag:yFaX109ioSXJ8h2pwHBAyA==,type:str]
    password: ENC[AES256_GCM,data:gMOp5iCidm4ZOe9JvmOoBLxuW0aqKS+FWzqNUoWy9EQ1Uwt3o1+2CmCBig==,iv:Xj1w3SimeL2206W47R6a1X1Ixky94mEZmGX0FzAx3K4=,tag:Fe2dHEiH2DTv45wEZUkpow==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPRW9mWWZPa3RrMXdqMVE2
            SFMvc1d0emY4cnI0K0hJWHFjWUUrOTZJK3hNCnRMT2s4NGtnRXhONUg5UkM1OVVT
            aWtNRFV6elBMN3p4bkRSUit0elZTUTgKLS0tIHVHcGRYK2JNS3NDbngxRWZMZVFZ
            NVJXUytsVXZrQnNJdE5VWlpMR2tsMEkKSvE/Bwu+mRUshmFVGWTqS4rUd4seKtFw
            nCaocaCDaBukoKuZdrtxUd1t9MjVLF3HDOFO51ihqQ1WNtRu5q8eWw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1586thf5vkcdf5lcn3zwjpu8ltkwyq8efrhj8lr0vdrrt9k5f3qgsxeg7gx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-26T14:59:47Z"
    mac: ENC[AES256_GCM,data:xfmUzW6oqE2w1KaG8q3Y/82lQW8vkMJXS9CH5jk6ubWuWj1TWodp6pCvXQoQDxWbIbl8mxk+t2++TntULSLV76zzO15gex/X5aREXu3FMDLvhkWxwFN+ukBF5YtlhwG+qf5/0bbcTuWmprDlX0h3nz9uz/B8+PzZBV0FyLRD0o8=,iv:jE/KLZZ/O6heRQbpiVNrF6Ev9WHXNlmDf9244b5gmBs=,tag:tRURBkicfu/eUUD3NOhGLw==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: deal-finder-secrets
    namespace: deal-finder
    labels:
        app: deal-finder
    annotations:
        argocd.argoproj.io/sync-wave: "-2"
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:gsfY1F6tG6iPAwrfx/NQjRFews1DisRAPxPZGMaRF9pRWO5gZVgqhJG6ZiFdrSpBNLcH7lb+QBNqnTYewnwBWfCeClWbwj267KuhctcwJD29Ij2Fv/pmWHd6IgO0cewNgE/J3rFrarGwRKg5tPPG1DgInpKlNv9V5Viy,iv:2K3XLXsymZqC6b2S9Y3O/gRo5HUrUqXWGO4mm3lhWdY=,tag:Es7myl8aI4GdvthGZjrEqQ==,type:str]
    EBAY_CLIENT_ID: ENC[AES256_GCM,data:BONLBRh0ItbBTZoKFPjsi1kHJLZkByglpm3k5gOk7dPc5hBgVoghNg==,iv:iTRWIleouXlNIZGXjiXJEDsw6x+G5xtIXy1ZpRE+elo=,tag:MvEXLg4hF5LwTXl2GIFtFg==,type:str]
    EBAY_CLIENT_SECRET: ENC[AES256_GCM,data:2ANyLy2vgDyJficJmStXkyeUSSb1xd5ca1tkwjIFlfIk0WsH,iv:VqrWWgX4OCEjVWz3dLZvT0EgNzCdey7gHUmTUr+iYJQ=,tag:jgrYa30biLyz6GzWVgjoWw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPRW9mWWZPa3RrMXdqMVE2
            SFMvc1d0emY4cnI0K0hJWHFjWUUrOTZJK3hNCnRMT2s4NGtnRXhONUg5UkM1OVVT
            aWtNRFV6elBMN3p4bkRSUit0elZTUTgKLS0tIHVHcGRYK2JNS3NDbngxRWZMZVFZ
            NVJXUytsVXZrQnNJdE5VWlpMR2tsMEkKSvE/Bwu+mRUshmFVGWTqS4rUd4seKtFw
            nCaocaCDaBukoKuZdrtxUd1t9MjVLF3HDOFO51ihqQ1WNtRu5q8eWw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1586thf5vkcdf5lcn3zwjpu8ltkwyq8efrhj8lr0vdrrt9k5f3qgsxeg7gx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-26T14:59:47Z"
    mac: ENC[AES256_GCM,data:xfmUzW6oqE2w1KaG8q3Y/82lQW8vkMJXS9CH5jk6ubWuWj1TWodp6pCvXQoQDxWbIbl8mxk+t2++TntULSLV76zzO15gex/X5aREXu3FMDLvhkWxwFN+ukBF5YtlhwG+qf5/0bbcTuWmprDlX0h3nz9uz/B8+PzZBV0FyLRD0o8=,iv:jE/KLZZ/O6heRQbpiVNrF6Ev9WHXNlmDf9244b5gmBs=,tag:tRURBkicfu/eUUD3NOhGLw==,type:str]
    version: 3.13.3
