apiVersion: v1
kind: Secret
metadata:
    name: minio-backup-credentials
    namespace: postgres-system
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:Gfx3yrqpkDZwyWS3NAyS,iv:Ph1LJ1na8KBy9OqVOyToLxulMYuHEiJj7LKptK020bU=,tag:qBH3KR2aPFiWZHr4xq9r4g==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:HxdBXksy2xG1uvt5h5i2aLrjUV4oEdOSuDeGD5e6Iw==,iv:aEr0C2CzmlPz2zCFwJgPZVPqZ00Bkk9mtLJ4yO+g6Ns=,tag:E6EuZW/r7ODntutVf6EmWA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArWUpmdTR3aks0N09TWWZP
            Q3RGZ2ZnaURNQ0pOUSswT1YrYlZOWTI1bHk0CjhNeEJtdkZodnpRVmg2NXNtK2FQ
            UTI0cU5rMHo5TkVUMEREKytoYjZreXcKLS0tIFF3QjFmYmluK0ZKWk1oZk5Qb2F4
            SDVZbytKVXVkY0FWQjdRSFcxWUtGTU0KPtxPG4SdGG28hwsQB/5KvsZ7pQxFj6WW
            Lnf5/srFwqwO/k4Amjem3xpPg6J7HD5u92353qEqpx3vTLVve7RVeg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1586thf5vkcdf5lcn3zwjpu8ltkwyq8efrhj8lr0vdrrt9k5f3qgsxeg7gx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-25T20:54:29Z"
    mac: ENC[AES256_GCM,data:5gnXk0oOlUHUNdtPP8m8vyqpSraej1yBv+UvmmErT/TRY/UqQqA0iK6O6G1Tz+A6PWYvgrMCU7qHIa8tNaH+ixQJ/TarkjnNDlOJeX/1F/sBbzLOjm/gDcMRbVByCyaKFyJjpFvujP4A+8Jgq5Vk7AqSYH8Nfy/W/Ds57ar8dCc=,iv:xllCSiiXi9beaZCl9pZoviZK6xo90KdQRRdaS8wpdNI=,tag:gR6WsThSP7Bb/oPuEwktcw==,type:str]
    version: 3.13.1
