---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unpackerr
  namespace: servarr
  labels:
    app: unpackerr
  annotations:
    secret.reloader.stakater.com/reload: "unpackerr-secret"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: unpackerr
  template:
    metadata:
      labels:
        app: unpackerr
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: unpackerr
      containers:
        - name: unpackerr
          image: ghcr.io/hotio/unpackerr:release
          env:
            - name: PUID
              value: "568"
            - name: PGID
              value: "568"
            - name: UMASK
              value: "002"
            - name: TZ
              value: "Europe/Oslo"
            - name: UN_INTERVAL
              value: "2m0s"
            - name: UN_START_DELAY
              value: "1m0s"
            - name: UN_PARALLEL
              value: "1"
            - name: UN_SONARR_0_URL
              value: "http://sonarr:8989"
            - name: UN_SONARR_0_API_KEY
              valueFrom:
                secretKeyRef:
                  name: unpackerr-secret
                  key: UN_SONARR_0_API_KEY
            - name: UN_SONARR_0_PATHS_0
              value: "/media/downloads"
            - name: UN_SONARR_0_PROTOCOLS
              value: "torrent"
            - name: UN_SONARR_0_DELETE_DELAY
              value: "5m0s"
            - name: UN_SONARR_1_URL
              value: "http://sonarr2:8989"
            - name: UN_SONARR_1_API_KEY
              valueFrom:
                secretKeyRef:
                  name: unpackerr-secret
                  key: UN_SONARR_1_API_KEY
            - name: UN_SONARR_1_PATHS_0
              value: "/media/downloads"
            - name: UN_SONARR_1_PROTOCOLS
              value: "torrent"
            - name: UN_SONARR_1_DELETE_DELAY
              value: "5m0s"
            - name: UN_RADARR_0_URL
              value: "http://radarr:7878"
            - name: UN_RADARR_0_API_KEY
              valueFrom:
                secretKeyRef:
                  name: unpackerr-secret
                  key: UN_RADARR_0_API_KEY
            - name: UN_RADARR_0_PATHS_0
              value: "/media/downloads"
            - name: UN_RADARR_0_PROTOCOLS
              value: "torrent"
            - name: UN_RADARR_0_DELETE_DELAY
              value: "5m0s"
          volumeMounts:
            - name: media
              mountPath: /media
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "1Gi"
              cpu: "1"
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: servarr-media
