apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: t3env-private-config
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - env/private-agent-config.enc.yaml
