apiVersion: v1
kind: Secret
metadata:
    name: t3env-vault-access
    namespace: remote-pi
type: Opaque
data:
    identity: ENC[AES256_GCM,data:v1PA0Qo7oTEXeoSebMi5Dd5XSueLy6n+oF4RxFtDxvAv3dnu6Yq19GLMp3YN1ECS7VShB+NTt4JF6Pl+QEHjUvcahRWRIYu3cHjBZGFc7+HwTV2gBIuwxiWINXzNZoGOZ1T9lc9xpvCBjaTpxvuIwm+b7F/dxwVUkX3LLEYlKbDqJN+nRPW+qk86eiZ0xVGuGJdysb1aniHlYZCX1XCMBFNUfx06RbIrXe8cacLcXy2npeJdlOwULBvFy4a5omuWugBxHWrn+GvtPd8bw2STzsSnOxHMbXxWavO6jWoIIaLbd88YqELVBpW/v+arf6vjdnQtetD5ZSCEltzP34YDgsxxZwnjk3nScL7abxPOLxNYKVJK5A2uNTxumYv6eP7oiq6GyYvAc4ahcAIClCnwzgIjB/DPZydbShtiFt8VM5niMfE4yJneirM5sFdzzKgGeaBkfYjVV6VdYw3J1uh/4NrwD+VEA4lyUI7tZ3v+aY9tqUzTnLwylnzGVx40MRz26RWLovpLyZ0me1u1xOqfVMq9RVKfIUcmZGyXIM0/D4tmFyz29lghAvW6OVVXYLzYgcAzyOF3wss4MgBMvUVpMtNMPhfNUZ1VZVx9/H3oAzHhdALMBeI7Qz/oXK4M9pEH7GPc49Fu6eg06qfdiUt3paKDjRHtvSly6JUckvk+cR2iH6mCr6QVb7ydBJEienjtrEcDiRRGNMIKsWcxQDO95WRVZcg=,iv:e0rDAr6yjOG2sRTQME9k1Hb/2M+RWWzLx0zR0qw7u+M=,tag:Cof1cZmXFhtZj3bXfS5SEg==,type:str]
    known_hosts: ENC[AES256_GCM,data:6AXdmncSuwQDT4/R5uKXDyQuXriAFQrHCOZFHddkBs5Rn/Y6Szv0ipZCKw//p2720OYi5OVccc4xt9PtebT0BBFxFPl+74J9h6NdQeY/zKFBXo6F8zppOLrs+yUBxUJ9cvQwRR8A4LKI+q6e2f4//qjugPhvKngSEoDYUwBzKuU=,iv:IM+JvSIKA/ZGBMK3J25Oa3fruh8a3j+JpSlS3hHvhU8=,tag:ptxai9U/BAu+1vGf0Kl8WQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKbGZ4dWNyN2FZd01TN0dN
            d3l4a2tlSFFRekIyZTBLRndiUkczUHd5TG1NCldYa2RoYi9UVmFySGt3UHJFVHdX
            cU16OXNCM0MzTkRyaWFLdUdkOEs4VGcKLS0tIHR3SUxVamdtb3NUZ29hcWhJNGpN
            cDJzOHFzZmR2dGlKS0ZjMEN2MUdTcjAK7AzPbBmaAgCV24W66KvRinxAP0e9nGm8
            dJy3ApiGxJX9MVlxpVGmzYwsYQeaVCjqHopzRX1K0gHOb76K23kpbQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1586thf5vkcdf5lcn3zwjpu8ltkwyq8efrhj8lr0vdrrt9k5f3qgsxeg7gx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-13T18:14:11Z"
    mac: ENC[AES256_GCM,data:uQvsyOBorRzM067MxrNpPQ6eCBGxN5ZYGNZDc30SwmpMy5WwxTtouXt06yBko3hETIKd2J0UAlTpJuOvZ68I/4bBymFA8l/smgSPiLLDpE+gs05+GtvoJYJ/IQz8JQHqKdN4HWLIptZQP97IP2TCJeldUgjL2zeNQP8k1R+QcUk=,iv:W/7FziuhgmQ6Mp+9T2J5S1qvAp/GxDsz4uFOKOWsnRg=,tag:gLHfobxU70E8aFA5hxeI8Q==,type:str]
    version: 3.13.3
