apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: syncthing-secrets
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - vault-passphrase.enc.yaml
  - keepass-hub-secret.enc.yaml
