"""Write homelab.conf (ssh_config) from the .lan DNS records.

Every `address=/<name>.epaflix.lan/<ip>` line preceded by `# ssh-user=<user>`
becomes `Host <name>`. Keys and host-key policy come from a per-machine file,
~/.ssh/homelab-identity.conf, included for these hosts only:
homePC and the laptop point it at Bitwarden, the t3code pod at its vault agent.

Usage: gen-homelab-ssh.py [--check]   (--check exits 1 if homelab.conf is stale)
"""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
DNS = ROOT / "1-proxmox/pihole/dnsmasq.d/30-epaflix-lan.conf"
OUT = ROOT / "1-proxmox/ssh/homelab.conf"


def hosts(text):
    user, found = None, []
    for line in text.splitlines():
        if m := re.fullmatch(r"#\s*ssh-user=(\S+)\s*", line.strip()):
            user = m.group(1)
            continue
        if m := re.fullmatch(r"address=/([a-z0-9-]+)\.epaflix\.lan/(\d+\.\d+\.\d+\.\d+)", line.strip()):
            if user:
                found.append((m.group(1), m.group(2), user))
        user = None
    names = [n for n, _, _ in found]
    if len(names) != len(set(names)):
        sys.exit("duplicate host name in " + str(DNS))
    return found


def render(found):
    out = ["# Generated by 1-proxmox/ssh/gen-homelab-ssh.py from",
           "# 1-proxmox/pihole/dnsmasq.d/30-epaflix-lan.conf. Do not edit; add a",
           "# '# ssh-user=<user>' line above a DNS record instead.", ""]
    for name, ip, user in found:
        out += [f"Host {name}", f"    HostName {ip}", f"    User {user}", ""]
    out += [f"Match final host {','.join(ip for _, ip, _ in found)}",
            "    Include ~/.ssh/homelab-identity.conf", ""]
    return "\n".join(out)


if __name__ == "__main__":
    text = render(hosts(DNS.read_text()))
    if sys.argv[1:] == ["--check"]:
        sys.exit(0 if OUT.exists() and OUT.read_text() == text else "stale: run 1-proxmox/ssh/gen-homelab-ssh.py")
    OUT.write_text(text)
