---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: neutarr-internal
  namespace: servarr
spec:
  entryPoints:
    - internal
  routes:
    - match: Host(`neutarr.epaflix.com`)
      kind: Rule
      services:
        - name: neutarr
          port: 30262
  tls:
    certResolver: cloudflare
    domains:
      - main: epaflix.com
        sans:
          - "*.epaflix.com"
