---
apiVersion: v1
kind: Secret
metadata:
  name: pve-exporter-secrets
  namespace: observability
type: Opaque
stringData:
  pve.yml: |
    default:
      user: root@pam
      token_name: grafana
      token_value: <PROXMOX_API_TOKEN_VALUE>
      verify_ssl: false
