---
apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: deltasync
  namespace: postgres-system
  labels:
    app.kubernetes.io/name: deltasync
    app.kubernetes.io/component: database
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  cluster:
    name: postgres-cluster
  name: deltasync
  ensure: present
  login: true
  passwordSecret:
    name: deltasync-db-role
  databaseRoleReclaimPolicy: retain
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: deltasync
  namespace: postgres-system
  labels:
    app.kubernetes.io/name: deltasync
    app.kubernetes.io/component: database
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  cluster:
    name: postgres-cluster
  name: deltasync
  owner: deltasync
  ensure: present
  databaseReclaimPolicy: retain
