apiVersion: v1
kind: Secret
metadata:
    name: deltasync-secrets
    namespace: deltasync
    annotations:
        argocd.argoproj.io/sync-wave: "-2"
type: Opaque
stringData:
    db-password: ENC[AES256_GCM,data:GehfXLaFCGGl7O/6Kaa+FurkHjtp4V5O0Vq7yRkmGlc=,iv:ZcHQoE6ZCwO6CmPE3Ikb6doG/boEB/wg9kSK1lTyqyY=,tag:g/IKfc3keKr33cmS05IxSA==,type:str]
    admin-password: ENC[AES256_GCM,data:de+HzJbCnF9iOWHXv1fnEaFUENtWxigtSbMq8o7WWU0=,iv:k6rFIEGoNTpbVTkMtkiQxb4m04XMw4J2+JRE9QHUHNE=,tag:MD+dEMetKWjd5/Bhi/vt5A==,type:str]
    admin-token: ENC[AES256_GCM,data:wl8e8erZhM6hQ0OlYEHjGoLI6Xn5+N0DlWkOaH9kdK7k/ayQtKz4FYE4Ww==,iv:wF2rSVaArx4UsmzQ/bAypfmJWVhf4rSpAhoSVSnI/4k=,tag:bWJV4RBIGQTn9W6crJ660g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4ak4rVktVMU50SEtlaEJo
            RmFneGV3d0J6T095dTk1ZEovZzhhNkR6QUFNCkVaMGNzK09KZ0htNVFKREtMNG5T
            M0h3Rm1WcE82WU4yUCtaK3hNVm5jdXcKLS0tIENvdjJoWVovc2pyRFIvY0dRem0v
            LzZYZStJM0NzWG5NVE5CN0h1eEZFQXcK8smBxB+nSCeOibyNmNvqxT53+Jj7zlI1
            OsSJBFNIxbsGm4mvNKg7hl5hJBF4/gd+FOCd/bnTlmP7DGutdBFt1w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1586thf5vkcdf5lcn3zwjpu8ltkwyq8efrhj8lr0vdrrt9k5f3qgsxeg7gx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-29T08:31:52Z"
    mac: ENC[AES256_GCM,data:F0msR9xUAJZL+Nn/CxLNE/uo4kLfgeORMsR4pOu3ZDNo8zEPvF3QpgH5sNUr9lPHq9pXl1QEaOebAYx1BP58nbUSJpsV672DgYC3nQkaWKBEz+QnhHUo5ayQ5FZe+Sot0/H/TzAOsFRPH3fU92h5SBhFLxMdByASS6Ib6kpzvgw=,iv:f4c5xdlwuz2qTbD5iEue+1spC0doIHwOvyZYV++gFfg=,tag:YhN0IkYpa7xhSxk73L/cLQ==,type:str]
    version: 3.13.3
