apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-credentials
    namespace: cloudflare-tunnel
type: Opaque
data:
    tunnel-id: ENC[AES256_GCM,data:SVuv2yKcRKujCTtnW/WreyMbfXkIs9lqEEVv1/guCmfh97S6aQ5m4cbWGtsK8Zxh,iv:F47bxVirHIZHkvzCpA1XEttYhL9WVAgsRYH9ocxQpvs=,tag:dfkEglymgTrKi2PPDHFDpQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:LqIQrNWNu/6dOB5CJmFVcO6pdW3ImXbDMEfQSgQk8t+NCqFmiHOnXAq3gZUxVnw2p0YDXvPCksOtmT947aWnOUtWa0hpER+uJ+4XjPVb3XY6oT2no/jpYmcvzhYAluBBhRM6wy4DAFoEtJnUyUyaIQYclQ6dX/cVHxj75S03EKRX/aWuYInj9vDsJuavdG6aAkqZjay0AQxSqlLD98lD/artIFMCbE2ef+ZiolUsIZxn5n5yfhk6TYyy46RB91Uhocp0O/46ClmJ+8/jaocUTLfZDeYGOKAtClDTp2qwsdOC3CVqqkAgUXHP/CYRUd+gW7wSdfHMdpkCdb2S6fE9bu+rFhY73+d0dSwgBAI5eoKXxjbsWd0qgYViDhyJHVee7pSuSg==,iv:9vr34V3N6hzQ2okRz7SeKIxcFFs7ttJtSsB5J7ao+Ak=,tag:40OaJzTbFRvSrC2eWanP5Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvZ2FrYytkWk5NNWVhckRF
            d0xlRUtveDVWYmk2cDhTWWhYQnlvSnM0NWdJCmdyUXhpYWFWVzVvcU9UdU5UZjRj
            bEovaytqbEJOY09ZandvSUJEaE80bWcKLS0tIDhyMkJTajV2TWFLMDgvZ295bXdT
            dnlPYllqYk1oVVZjeVdML2VKb0hYOUUKEQGYudSiz+ELk578HxyK8o0OrlmwyAhX
            XP0zhQ/SwZiza29dHC8Xf3QGGV5RYkeS6/YzByNMqcxwZLnOnWPYkQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1586thf5vkcdf5lcn3zwjpu8ltkwyq8efrhj8lr0vdrrt9k5f3qgsxeg7gx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-30T14:33:25Z"
    mac: ENC[AES256_GCM,data:e2M8Qh09M2YcA6gV5kJKYps9GrRSWhbYYNu423b4UjCti3g8a7G+UIHo2YR8CERG/I4BAMFvD8bNSf8yqHfN9d8llTziNyVSiextxd5mYdQGd3nqi3nESE4+Xxi/EhX7YjcKwJ05xdYwpYNsiIE5dtZywHSC0kZqKzjR/JJ4zIc=,iv:ILtB2l/8rV2+jXLO53G/ySuFYGDnYQYWckFyJnCOwUc=,tag:dhR307iypH9zO5zUP2faaQ==,type:str]
    version: 3.13.3
