---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: cleanuparr-internal
  namespace: servarr
spec:
  entryPoints:
    - internal
  routes:
    - match: Host(`cleanuparr.epaflix.com`)
      kind: Rule
      services:
        - name: cleanuparr
          port: 30263
  tls:
    certResolver: cloudflare
    domains:
      - main: epaflix.com
        sans:
          - "*.epaflix.com"
